### PR TITLE
Enhancement: Use ergebnis/composer-normalize instead of localheinz/composer-normalize

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] uses `ergebnis/composer-normalize` instead of `localheinz/composer-normalize`

Related to https://github.com/ergebnis/composer-normalize/issues/266.

💁‍♂ For reference, see https://localheinz.com/blog/2019/12/10/from-localheinz-to-ergebnis/.

### CODE REVIEW

**Comment by localheinz** [comment]
Ha, hang on, this needs some work!

**Comment by localheinz** [comment]
Build failure is related to https://github.com/ergebnis/composer-normalize/pull/235.

**Comment by ondrejmirtes** [comment]
Yeah, I need the 1.1.0 version instead of 2.0.

**Comment by localheinz** [comment]
@ondrejmirtes 

I'll sort something out early next week - I'm expecting friends this weekend, otherwise I'd sort it put over the weekend!

🤞

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
