### PR TITLE
fix IntegerRange math edge case

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Awesome, thank you! This thing might be ready for release :)

**Comment by staabm** [comment]
I am not 100% convinced the newly added test is more correct then the previous assumption

**Comment by ondrejmirtes** [comment]
Can you elaborate?

**Comment by staabm** [comment]
after the lunch walk I guess its correct as we changed it.

doing this range-math for a few days now, and my brain kind of melted.
its more or less brainfuck ;-)

**Pull request merged**
