### PR TITLE
object type: accomodate to properly resolve template type bound

### PR DESCRIPTION
**Pull request by hrach**
closes phpstan/phpstan#2763

### CODE REVIEW

**Comment by hrach** [comment]
Finally. I was missguided about hundred times. Wrong fixes, fixes that broken something elsewhere later, etc. etc. Also, another (major) codechange for another PR... Please take a look, sometimes it's a magic for me.

**Comment by ondrejmirtes** [comment]
Yeah, I like this much better 👍 Although the `if ($type instanceof TemplateType)` as first thing in `isSuperTypeOf` implementation feels dirty. Why `instanceof CompoundType` with `isSubTypeOf` call later doesn't work?

**Comment by hrach** [comment]
> Why instanceof CompoundType with isSubTypeOf call later doesn't work?

Because I didn't know what is it exactly :D Ok, I've tried to rework it. Actually, many interfaces and theirs methods would benefit of documenting their meaning.

**Comment by ondrejmirtes** [comment]
I'd like the number of `if ($something instanceof SomeType)` to go down, especially in `Type::isSuperTypeOf` implementations. Because with them, adding a new type becomes exponentially more work...

I'm really grateful for your contribution :) I'd say that after 22 hours, you're an expert now in this area :D

**Comment by ondrejmirtes** [comment]
Look at CompoundType implementations - it's a hack used to when `accepts` or `isSuperTypeOf` needs special handling for some types... Since TemplateType is one of them, it should work without an extra if...

**Comment by ondrejmirtes** [comment]
Oh, you’ve already changed the code. Doesn’t something in TemplateObjectWithoutClassType also need to change? (I’m on mobile.)

**Comment by hrach** [comment]
> Doesn’t something in TemplateObjectWithoutClassType also need to change? (I’m on mobile.)

Need investigation, obviously we are missing more tests, changing it doesn't fix/break anything.

**Comment by ondrejmirtes** [comment]
Works great, thank you! Not sure what's going on in TemplateObjectWithoutClassType and why it doesn't need the changes...

**Pull request merged**
