### PR TITLE
implement isInteger() on Type

### PR DESCRIPTION
**Pull request by staabm**
Refs https://github.com/phpstan/phpstan/issues/8224#issuecomment-1295816430

### CODE REVIEW

**Comment by staabm** [comment]
Memo to me: adjust per loose comparison rules

**Comment by ondrejmirtes** [comment]
> Memo to me: adjust per loose comparison rules

No. Only an integer is an integer.

**Comment by ondrejmirtes** [comment]
It's up to `Type::looseCompare()` to tell that `int == string` might be true by asking `$otherType->isInteger()->or($otherType->isString())` in `IntegerType::looseCompare()`.

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by herndlm** [comment]
👍 I wanted to do the same later today :)

**Comment by staabm** [comment]
We also need it for bool and float :-)

**Comment by staabm** [comment]
I am working on bool now

**Comment by herndlm** [comment]
Go ahead, I won't be working on something today any more.

**Comment by staabm** [comment]
working on isFloat now

**Pull request merged**
