### PR TITLE
Lazier return in `UnionType->isSuperTypeOf()` (~40% faster)

### PR DESCRIPTION
**Pull request by staabm**
2.0.x variant of https://github.com/phpstan/phpstan-src/pull/3692

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
After https://github.com/phpstan/phpstan-src/pull/3692 is merged, you need to do `git merge origin/1.12.x` locally, fix the conflicts and push the merge commit here.

**Comment by staabm** [comment]
here we go

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by ondrejmirtes** [comment]
No, you didn't do what I meant :( I have to go back.

**Comment by ondrejmirtes** [comment]
You should have merged 1.12.x which already contained your PR but you didn't do that.

**Comment by ondrejmirtes** [comment]
This is what you did:

Screenshot 2024-11-30 at 14 06 32

The problem is that the merge conflict was not resolved. Your commit from 1.12.x was not in 2.0.x. When I did `git merge origin/1.12.x`, there was a conflict still.

This is what I meant:

Screenshot 2024-11-30 at 14 07 36

Please bear that in mind next time :) Thanks.

**Pull request merged**
