### PR TITLE
Remove incorrect overrides in PHP8 for proc_get_status

### PR DESCRIPTION
**Pull request by Firehed**
Related to #288: the more-precise return shape is overridden with a less-specific version when running under PHP8. This removes the override which seems to have come from an external import.

I'm not sure what's up with the original removal of `|false`, which doesn't seem to match up with the [official docs](https://www.php.net/manual/en/function.proc-get-status)

### CODE REVIEW

**Comment by VincentLanglet** [comment]
The official doc is flag as `(PHP 5, PHP 7)`

A lot of `false` value were removed in php 8 https://www.php.net/releases/8.0/en.php#consistent-type-errors-for-internal-functions

**Comment by Firehed** [comment]
Huh, I wasn't under the impression that was a type error which would cause the `return false`. In that case I'll update this to match override to the more-specific signature. Thanks.

**Comment by ondrejmirtes** [comment]
Hi, the line could just be removed with the same effect. PHPStan uses official php-src stubs on PHP 8 so it will be inferred from that (and merged with functionMap.php): https://github.com/phpstan/php-8-stubs/blob/main/stubs/ext/standard/proc_get_status.php

**Comment by Firehed** [comment]
Should I roll back to the previous version then? That is what I originally did.

**Comment by ondrejmirtes** [comment]
Yes, the first commit was sufficient 👍

**Pull request merged**
