### PR TITLE
Fix SoapFault constructor type

### PR DESCRIPTION
**Pull request by ahmedash95**
The file is updated manually as I couldn't find if there is a generator or not.

Addresses https://github.com/phpstan/phpstan/issues/8111

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Could you please add a test to make sure it's fixed? Because there are multiple sources of these headers, it's not obvious this is actually gonna fix that. (PhpStorm stubs are also wrong in PHPDocs, would be nice to send a PR there too.)

**Comment by ondrejmirtes** [comment]
Oh, you did already :)

**Comment by ahmedash95** [comment]
I had to split the exceptions so everyone has its own function scope. because the test was reporting only the first `throw` statement.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
