### PR TITLE
Add ArrayAccess rule to AppendedArrayItemTypeRule

### PR DESCRIPTION
**Pull request by nishimura**
Fixes https://github.com/phpstan/phpstan/issues/2858

`PHPStan\Rules\Arrays\OffsetAccessAssignmentRule` is reporting offset errors of `ArrayAccess` in current version.

This commit changed the handling of the `ArrayDimFetch` in the `NodeScopeResolver`, so I'm not sure if this approach was appropriate, but the existing tests did not fail.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, this doesn't follow my suggestions from https://github.com/phpstan/phpstan/issues/2858#issuecomment-575609396 so I worry it's not going to work correctly.

**Comment by nishimura** [comment]
Thanks for confirmation.
Added code to check `TKey` in ` ObjectType::hasOffsetValueType`.
But I couldn't see the difference in behavior in the error report.

Offset assignments check (2) is here: https://github.com/phpstan/phpstan-src/pull/111/commits/69098c9cc0d594910b86920b6a8d76e5e858ff5c#diff-42252e494c0e4501981e0c7252319ad9R66

**Comment by nishimura** [comment]
Even if it revert the change of `NodeScopeResolver`, it works for the first error.
If there are multiple errors, the type will change and no more errors will be reported.
I can't come up with a way to report all errors without changing the `NodeScopeResolver` ...

**Comment by ondrejmirtes** [comment]
I've realized that we already have OffsetAccessAssignmentRule, but it checks keys only. I thought it'd be better to add a new rule instead of trying to change AppendedArrayItemTypeRule.

So I did: https://github.com/phpstan/phpstan-src/commit/e71259c4fad1dcd597cb99a9ac980ca8dad7dbc4 (including your tests)

I also realized that your change of `hasOffsetValueType` has repercussions in already existing rule: https://github.com/phpstan/phpstan-src/commit/7e89f44b95faa584b647b5322b2b1732a0424441

So the only thing what remains is the change of type after assignment. I'll have to investigate what exactly causes it. Thank you!

**Comment by ondrejmirtes** [comment]
Solved: https://github.com/phpstan/phpstan-src/commit/c7db44769bb4c9c40200cec4e774a1e9386c1e4f?w=1

**Comment by nishimura** [comment]
Thank you very match!
I used the master branch to confirme the expected reports at https://phpstan.org/r/92461398-7b03-4dee-8363-1b2ad39b814c .

**Pull request closed without merging**
