### PR TITLE
PHP 8.4 runtime support

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Comment by thg2k** [comment]
What do you think of the implicitly nullable parameters deprecation in 8.4?

**Comment by ondrejmirtes** [comment]
@thg2k I don't understand the question. Can you be more specific about what you're asking?

**Comment by thg2k** [comment]
> @thg2k I don't understand the question. Can you be more specific about what you're asking?

I mean that those deprecation notices are a pain. I'm thinking about submitting an RFC to revert that

**Comment by ondrejmirtes** [comment]
@thg2k It's too late for that. And it was accepted unanimously so it's unlikely to be reverted.

**Comment by thg2k** [comment]
I know, but it's still an idiotic change, and reverting a deprecation should still be doable even in beta period, as it's not a new feature..

**Comment by ondrejmirtes** [comment]
This is the wrong place to discuss that.

**Comment by thg2k** [comment]
> This is the wrong place to discuss that.

I know, I was just asking your opinion en passant, as I value it.

**Pull request merged**
