### PR TITLE
Fix non-working type assertions in `NodeScopeResolverTest` cases

### PR DESCRIPTION
**Pull request by herndlm**
Discovered via https://github.com/phpstan/phpstan-src/pull/1991

### CODE REVIEW

**Comment by herndlm** [comment]
because I saw it here - most likely running the issue bot for `tests/`-only changes is overkill?

**Comment by staabm** [comment]
Maybe we should have a rule which detects when TypeInferenceTest included files don‘t contain asserts (or doesnt import the function)

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by ondrejmirtes** [comment]
> Maybe we should have a rule

Done https://github.com/phpstan/phpstan-src/commit/d0207ed79e94e4b4daceb0f83abb1f481ee3250b

**Pull request merged**
