### PR TITLE
Add \PHPStan\Reflection\ClassReflection::isThrowable

### PR DESCRIPTION
**Pull request by TravisCarden**
This is my first attempt to contribute to this project. Would the maintainers be open to contributions like this one? I've followed the contribution guidelines, and I think I've matched the coding and testing conventions of the codebase.

### CODE REVIEW

**Comment by TravisCarden** [comment]
Well, I can't say as I understand the failures below. I can't even run `make phpstan` on those versions of PHP (7.2, 7.3, 7.4) due to PHP 8-only features already used in the codebase.

**Comment by staabm** [comment]
Thanks for contributing.

What are you trying to achieve with this PR? whats the motivation behind it? Why do you need it?

would `$classReflection->is(Throwable::class)` also work for your use-case?

**Comment by TravisCarden** [comment]
👋 Hi, @staabm! In short, I need to know whether a given class can be thrown as an exception so I can require it to implement a project-specific exception interface. But I've tried your suggested code, and it works just as well (besides being more elegant, I think). I just didn't know the feature existed. Now that I do, I'm not sure an `::isThrowable()` method really adds much value.

Incidentally, I didn't give a second look at `::is()` because I expected it to do something different based on its name. Since `::isSubclassOf()` is basically analogous to PHP's `is_subclass_of()`, I would have expected this method to be named `::isA()` as analogous to PHP's `is_a()`. Had it been, I think I would have correctly intuited its intent. Maybe that's helpful DX feedback. `¯\_(ツ)_/¯`

In any case, thank you for your recommendation; that will simplify my code nicely. And thanks for the chance to contribute. I may propose some other ideas later. 🙂

**Comment by staabm** [comment]
Ok cool. We appreciate any contribution, thx for giving it a try.

**Pull request closed without merging**
