### PR TITLE
Improve resolving constants with namespace aware logic

### PR DESCRIPTION
**Pull request by TheNorthMemory**
Fixed phpstan/phpstan#7352 with or without (sub)namespace.

Let https://phpstan.org/r/73109e28-2ab1-492a-a60c-1f38d3765db3 passed.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
This change does not work as you can see in the build failures.

**Comment by TheNorthMemory** [comment]
> This change does not work as you can see in the build failures.

I've checked and passed by `php vendor/bin/paratest --no-coverage tests/PHPStan/Rules/PhpDoc/IncompatibleClassConstantPhpDocTypeRuleTest.php` locally. Wait a moment, let me check the cases by the github actions.

**Comment by TheNorthMemory** [comment]
Got the failed cases logic. While there were the namespaced classes, this change is affected that all the veriables always resolved as  `Fully qualified name` such as to access the internal constant `true`. It is resolved as `__namespace__\true`, eg:

```diff
diff --git a/tests/PHPStan/Analyser/data/bug-1447.php b/tests/PHPStan/Analyser/data/bug-1447.php
index 53cffc336..e07c271c6 100644
--- a/tests/PHPStan/Analyser/data/bug-1447.php
+++ b/tests/PHPStan/Analyser/data/bug-1447.php
@@ -7,7 +7,7 @@ class Tst {
        function _initArgs($abc): void
        {
                foreach ($abc as $k => $v) {
-                       if ($v === 'a') $e = true;
+                       if ($v === 'a') $e = \true;
                        else if ($v === 'b') $e = true;
                        else if ($v === 'c') $e = true;
                        else if ($v === 'd') $e = true;
```

In my opinions, all the failed cases must refer to them with their fully qualified Name as in.  @ondrejmirtes What's your opinions?

**Comment by ondrejmirtes** [comment]
> In my opinions, all the failed cases must refer to them with their fully qualified Name

That's not how PHP behaves: https://3v4l.org/fgSbX

**Comment by TheNorthMemory** [comment]
> That's not how PHP behaves: https://3v4l.org/fgSbX

I see. I'll resolving this problem soon.

**Comment by TheNorthMemory** [comment]
This PR is following the normal behaviors as

> Inside a namespace, when PHP encounters an unqualified Name in a class name, function or constant context, it resolves these with different priorities. Class names always resolve to the current namespace name. For functions and constants, PHP will fall back to global functions or constants if a namespaced function or constant does not exist.

see  https://www.php.net/manual/en/language.namespaces.fallback.php

All the tests passed except the BCs now.

**Comment by rvanvelzen** [comment]
This does not fix the actual root cause, which is a bug in `InitializerExprContext::parseNamespace()`. Maybe you can try [this simpler fix](https://github.com/phpstan/phpstan-src/compare/1.7.x...rvanvelzen:bug-7352) instead?

**Comment by TheNorthMemory** [comment]
> This does not fix the actual root cause, which is a bug in `InitializerExprContext::parseNamespace()`. Maybe you can try [this simpler fix](https://github.com/phpstan/phpstan-src/compare/1.7.x...rvanvelzen:bug-7352) instead?

Ah... It's true and simple.

**Comment by TheNorthMemory** [comment]
Closed by https://github.com/phpstan/phpstan-src/compare/1.7.x...rvanvelzen:bug-7352

**Pull request closed without merging**
