### PR TITLE
github: Highlight stub files with php syntax highlighter

### PR DESCRIPTION
**Pull request by adaamz**
https://github.com/github/linguist#overrides

I merged this PR to my fork's master, so you can preview how it will look like: https://github.com/adaamz/phpstan-src/blob/master/stubs/ArrayObject.stub

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Nice :)

**Comment by ondrejmirtes** [comment]
Can you add the same thing for neon to be highlighted as YAML?

**Comment by ondrejmirtes** [comment]
Love it :)

**Comment by staabm** [comment]
Thx for the inspiration.. just proposed YAML GitHub wide Syntax Highlighting for NEON files in https://github.com/github/linguist/pull/4845

**Pull request merged**
