### PR TITLE
Pass verbosity to workers and show stack trace on error

### PR DESCRIPTION
**Pull request by benja-M-1**
This PR allows displaying the stack trace when an error is thrown in a worker. The stack trace is only displayed when either `-v`, `-vv` or `-vvv` is passed to the `analyse` command.

I believed the message could also be improved. For example, the error says "[...] in file src/...". However, it is the analysed file, not the file in which the error occurred. 

This is the result:
image

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Please modify it a bit - if you see the stack trace already, you don't have to run it with `--debug`.

And if the stack trace output isn't enabled, the correct advice is `-v`, not `--debug`.

**Comment by benja-M-1** [comment]
Ineed, I updated the help message.

**Comment by ondrejmirtes** [comment]
This still isn't  correct. The message "Run PHPStan with -v option" is going to be printed even when the user is already running with "-v".

Please modify the message so that it makes sense in both cases, and please post screenshots of both cases. Thanks.

**Comment by benja-M-1** [comment]
Hi @ondrejmirtes, 

I have updated the message to change whether the option has been set or not.

Here is a screenshot without `-v` option and with `-v':
image
image

**Comment by ondrejmirtes** [comment]
Perfect, thank you.

**Pull request merged**
