### PR TITLE
[WIP] update of symfony components to version 5

### PR DESCRIPTION
**Pull request by flug**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, sorry, not interested in this yet.

**Comment by flug** [comment]
why ?

**Comment by flug** [comment]
your project use several symfony related components that will be having a new version in the near future. if not kept up to date many projects related to your risk of being blocked. I don't understand why you don't want to update the dependencies?

**Comment by ondrejmirtes** [comment]
Symfony 5 is not even in beta yet. Symfony has LTS releases. Next version of PHPStan (0.12) will be distributed with PHAR only (see contents of phpstan/phpstan repository) so there's no risk of dependencies conflicts.

**Pull request closed without merging**
