### PR TITLE
remove money_format from php8

### PR DESCRIPTION
**Pull request by Th3Cod3**
Fix: phpstan/phpstan#9954

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Please remove all the functions that were removed on PHP 8. Also a test would be nice. In CallToNonexistentFunctionTest.

**Comment by ondrejmirtes** [comment]
I did a few modifications that were necessary.

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by Th3Cod3** [comment]
Sorry, I just modified the prototypes of the functions that were changed in the php8 update.

**Comment by ondrejmirtes** [comment]
First please verify on phpstan.org/try that it's actually needed.

**Pull request merged**
