### PR TITLE
more precise `SpecifiedTypes` phpdocs

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I worry the casts actually need to stay there because PHP arrays are messy. They'll automatically cast numeric strings to integers which will lead to type errors.

**Comment by staabm** [comment]
hmm so the cast-errors should be baselined?

**Comment by ondrejmirtes** [comment]
You can use the inline ignore PHPDoc

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
