### PR TITLE
Keep non nullability if right expr is `NeverType`

### PR DESCRIPTION
**Pull request by rajyan**
fixes https://github.com/phpstan/phpstan/issues/5351

~~I haven't found yet why the second test case passes without this fix.~~

The test wasn't what I intended. fixed

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Please do it only for explicit NeverType. Otherwise it's perfect 😊

**Comment by herndlm** [comment]
@rajyan just wanted to say that I love the "small" fixes you're doing here and there. I was mostly too scared of NodeScopeResolver yet :) 
Update: I could've written that on Twitter too, sorry for another notification Ondrej. Again 😅

**Comment by rajyan** [comment]
@ondrejmirtes 
Thank you, fixed!

@herndlm @ondrejmirtes 
Thanks for your words.
PHPStan helped me a lot and greatly helping the PHP community. I want to know more about this tool, and make it greater if I can!

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by ondrejmirtes** [comment]
@herndlm This is usually what I have in mind when I tag an issue with "Easy fixes" milestone, it shouldn't be more than a few lines of code (but of course I can be wrong).

**Comment by ondrejmirtes** [comment]
@rajyan Can you please add regression tests for this issue and make sure it fails when your fix is reverted? Thank you. https://github.com/phpstan/phpstan/issues/4747

Also, this example https://phpstan.org/r/9879d278-5c2d-42ca-81e8-06e87bef529c from https://github.com/phpstan/phpstan/issues/4885 should work but doesn't. Can you please look into it? Thanks.

**Comment by rajyan** [comment]
@ondrejmirtes 
I will try to take some time today or tomorrow:+1:

**Comment by herndlm** [comment]
> @herndlm This is usually what I have in mind when I tag an issue with "Easy fixes" milestone, it shouldn't be more than a few lines of code (but of course I can be wrong).

small as in, a few lines of code, but timing-wise it might take hours to think and get into it (at least for outsiders) ;)
but makes total sense!

**Pull request merged**
