### PR TITLE
Add RedefinedParametersRule

### PR DESCRIPTION
**Pull request by paulbalandan**
Closes https://github.com/phpstan/phpstan/issues/8025

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by ondrejmirtes** [comment]
Did you please look into this?

> Research what PHP version considers this as an error. I remember a situation that such code was present in a library (React.PHP maybe) and it started failing only on PHP 8.0 or so.

**Comment by paulbalandan** [comment]
> Did you please look into this?
> 
> > Research what PHP version considers this as an error. I remember a situation that such code was present in a library (React.PHP maybe) and it started failing only on PHP 8.0 or so.

I did not look really at reactphp. I just tried redefined parameters at 3v4l.org and changed the PHP version from 7.2 up. All are failing.

**Comment by ondrejmirtes** [comment]
Alright 😊

**Pull request merged**
