### PR TITLE
Add regression test for anonymous class in trait

### PR DESCRIPTION
**Pull request by herndlm**
Regression test for https://github.com/phpstan/phpstan/issues/6472 which was also fixed by https://github.com/phpstan/phpstan-src/pull/946.

Feel free to just close this if not needed.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
What’s the error if you revert the fix please?

**Comment by herndlm** [comment]
```
1) PHPStan\Analyser\AnalyserIntegrationTest::testBug6472
Failed asserting that actual size 1 matches expected size 0.

Emitted errors:
- Method Bug6472\B::b() has parameter $array with no value type specified in iterable type array
  in <....>/phpstan-src/tests/PHPStan/Analyser/data/bug-6472.php (in context of class Bug6472\B) on line 20

```

**Comment by ondrejmirtes** [comment]
Please move the test to the rule that reports this error.

Usually regresion tests belong either to NodeScopeResolverTest, or to a unit test of a specific rule.

AnalyserIntegrationTest should be reserved only for bugs that crash PHPStan/infinite recursion etc.

**Comment by herndlm** [comment]
Moved. If the fix is reverted I get
```
1) PHPStan\Rules\Methods\MissingMethodParameterTypehintRuleTest::testBug6472
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'
+'20: Method Bug6472\B::b() has parameter $array with no value type specified in iterable type array.
+    💡 See: https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-iterable-type
 '

```

**Comment by ondrejmirtes** [comment]
Perfect, thank you.

**Pull request merged**
