### PR TITLE
Adding editorUrl to add clickable file urls to output

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Closes https://github.com/phpstan/phpstan/issues/4984

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
@ThomasLandauer Can you plase develop it locally and start pushing into the PR when you think you're done? I can imagine how doing everything without testing locally must be really cumbersome...

**Comment by ThomasLandauer** [comment]
* I didn't add any regex for `editorUrl` - not only cause I don't know how ;-) But also cause I have zero idea how those links look like for other editors: Maybe they don't support a line number at all, maybe they want the line *before* the file, maybe whatever ...
* I'm waiting for feedback first, then I'll come up with a docs-PR
* Some stuff like `is_string()` is maybe not necessary - don't know how an empty/null string is injected and how thorough you want those checks.

> Can you plase develop it locally and start pushing into the PR when you think you're done?

Sorry, no, I've never done that ;-)

**Comment by ondrejmirtes** [comment]
I'm sorry, I can't accept untested code like that.

**Comment by ThomasLandauer** [comment]
OK, I'm following https://github.com/ThomasLandauer/phpstan-src#building now, and it's working fine so far. But as soon as I add `%file%` to `phpstan.neon`, I'm getting:

> In Helpers.php line 75:
> Missing parameter 'file'.

Your plan was to use them as placeholders like this, right?:
```neon
editorUrl: 'atom://core/open/file?filename=%file%&line=%line%'
```
If yes, it looks like this is not working ;-) Which other syntax do you suggest?

**Comment by ondrejmirtes** [comment]
You need `%%` in this case.

**Comment by ThomasLandauer** [comment]
OK, done - is working for me. So closing this in favor of new attempt at https://github.com/phpstan/phpstan-src/pull/515

**Pull request closed without merging**
