### PR TITLE
Slightly reduce comparing and calling methods for trivial optimizations

### PR DESCRIPTION
**Pull request by zonuexe**

### CODE REVIEW

**Comment by zonuexe** [comment]
I've rebased this branch for the `1.11.x` release.

**Comment by ondrejmirtes** [comment]
There's a build failure https://github.com/phpstan/phpstan-src/actions/runs/8709007959/job/23887737566

**Comment by zonuexe** [comment]
@ondrejmirtes Thank you, fixed it.

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
