### PR TITLE
Constant arrays without an explicit class string should not resolve

### PR DESCRIPTION
**Pull request by rainbow-alex**
…the class name.

Fixes https://github.com/phpstan/phpstan/issues/3428

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Perfect, thank you! Can you test dev-master once it builds in 10-15 minutes to verify this fixes your issue, or that there's another path we need to fix? Thanks :)

**Comment by rainbow-alex** [comment]
I already ran this change against our code and the errors are no more! :)

Thanks for the quick feedback on this issue and the PR!

**Comment by ondrejmirtes** [comment]
Alright :) With the current cadence of bugfixes i expect this to be released in 1-2 days :)

**Comment by ondrejmirtes** [comment]
Oops, merged too soon, can you send a PR that fixes these failures? :) Thanks: https://github.com/phpstan/phpstan-src/runs/756749503?check_suite_focus=true

**Comment by rainbow-alex** [comment]
I noticed the builds failing, but it will be a few hours before I can fix this, sorry.

**Comment by ondrejmirtes** [comment]
I'll have to look into those failures, we probably created a BC break which will need to be solved.

**Pull request merged**
