### PR TITLE
Silent @ operator should use & $errno check

### PR DESCRIPTION
**Pull request by samsonasik**
refs verified in rector-src and my `ErrorHeroModule` module with test code for `@` 

- https://github.com/rectorphp/rector-src/pull/1577#pullrequestreview-840460805
- https://github.com/samsonasik/ErrorHeroModule/blob/18b691e880d6e068dd94d17bffcfdd54518d2a4a/src/HeroTrait.php#L112

### CODE REVIEW

**Comment by samsonasik** [comment]
Also referenced by PHP documentation https://www.php.net/manual/en/language.operators.errorcontrol.php#language.operators.errorcontrol

**Comment by samsonasik** [comment]
All green 🎉

**Comment by ondrejmirtes** [comment]
Can you please explain the behaviour of this code before/after with some examples? Thanks.

**Comment by samsonasik** [comment]
As I commented at https://github.com/rectorphp/rector-src/pull/1577#pullrequestreview-840460805, I tried the code in rector-src, with only check `error_reporting() === 0`, it will end up getting error:

```bash
 [ERROR] Could not process "/Users/samsonasik/www/rector-src/src/Application/FileProcessor.php" file, due to:           
         "mkdir(): File exists". On line: 26     
```

for the following code:

```php
@mkdir('test');
@mkdir('test');
```

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
