### PR TITLE
Fixed stub types for SplFixedArray

### PR DESCRIPTION
**Pull request by dktapps**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I don't get these changes. They do the exact opposite of what you asked. The `offsetGet` can never return null because it throws an exception.

**Comment by dktapps** [comment]
I'm not sure how you drew that from my issye, but this is in fact the correct behaviour. SplFixedArray will return null for offsets that exist but aren't yet initialized. https://3v4l.org/GBc56

**Comment by ondrejmirtes** [comment]
Oh thanks, I tested if for an offset that was outside the length bound and it thrown an exception instead.

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
