### PR TITLE
Add missing iterable stubs

### PR DESCRIPTION
**Pull request by jdecool**
Some `iterable` class missing in stubs.

This PR add some of them: `FilterIterator`, `CallbackFilterIterator` & `RecursiveCallbackFilterIterator`.

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
New generic classes also need to be added to this array https://github.com/phpstan/phpstan-src/blob/89c16a61a4cb341eeccdf41237e063f75b847ca2/conf/config.neon#L25 so that we don't start requiring user to specify their type variables everywhere.

**Comment by ondrejmirtes** [comment]
The integration tests found this error:

```
 ------ ----------------------------------------------------------------------- 
  Line   tests/Composer/Test/Package/Archiver/ArchivableFilesFinderTest.php     
 ------ ----------------------------------------------------------------------- 
  29     Property                                                               
         Composer\Test\Package\Archiver\ArchivableFilesFinderTest::$finder      
         type has no value type specified in iterable type                      
         Composer\Package\Archiver\ArchivableFilesFinder.                       
         💡 See:                                                                 
         https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-i  
         terable-type                                                           
 ------ ----------------------------------------------------------------------- 
```

The `ArchivableFilesFinder` class extends `FilterIterator`. It's a concern for me why:

1) The error hasn't been reported previously (it should be).
2) It's started to be reported now.

What I suspect that this is some kind of mix up between implicit and explicit `mixed` which got changed with generics.

Can you please debug this? Thanks.

**Comment by jdecool** [comment]
> Can you please debug this? Thanks.

I didn't leave a comment after my last push to warn you that I was watching this issue.

I'm going to debug it, I'll let you know when I found something.

Thanks.

**Comment by ondrejmirtes** [comment]
I'd be happy if the error "type has no value type specified in iterable type" wasn't started to be reported in this situation even after this PR - so this build should continue to be green even for Composer codebase.

**Comment by jdecool** [comment]
Hi @ondrejmirtes after working a little on this PR, I've to admit that I'm not sure how to fix this issue.

Couldn't we update the integration tests?

**Comment by ondrejmirtes** [comment]
One idea - try to rebase on top of dev-master, it might be fixed.

**Comment by ondrejmirtes** [comment]
Thank you! I merged it and will deal with the errors on master :)

**Comment by jdecool** [comment]
Thanks @ondrejmirtes 

You make an awesome work with `phpstan`

**Pull request closed without merging**
