### PR TITLE
Add support for @phpstan-throws

### PR DESCRIPTION
**Pull request by VincentLanglet**
I messed up with the PR https://github.com/phpstan/phpstan-src/pull/291

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I see the problem. It's not your fault.

**Comment by ondrejmirtes** [comment]
Please rebase on top of master, the build should pass. Thanks.

**Comment by VincentLanglet** [comment]
Sure, rebase done !

**Comment by ondrejmirtes** [comment]
The tests related to this PR are failing.

**Comment by VincentLanglet** [comment]
@ondrejmirtes I made some fixes. Can I do something for the `Build/Phpstan` failures ?

**Comment by ondrejmirtes** [comment]
@VincentLanglet Thank you, I'm working on a fix right now :)

**Pull request merged**
