### PR TITLE
Be stricter about getcsv and str_getcsv return types

### PR DESCRIPTION
**Pull request by mind-bending-forks**
This is a suggestion...

See: phpstan/phpstan#4993.
Example: https://phpstan.org/r/1c1e8795-2cde-48bb-95b5-25aa6d1925d4

I'm not sure whether `non-empty-array` is valid syntax in the `functionMap.php` file though, since I haven't seen any other examples?

`make tests` didn't produce any errors.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I'm not sure how the type `non-empty-array<int,string>|array{null}` will get normalized in practice and whether it actually adds any value. Can you write some test using NodeScopeResolverTest? Thanks.

**Comment by mind-bending-forks** [comment]
Sorry if I'm not understanding how things work... but is there a `PHPStan\Testing::assertNotOfType`, logical inverse of `PHPStan\Testing::assertType`? For example:

```php
assertType('false|string', false); // passes test
assertType('false|string', true); // fails test
```

whereas

```php
assertNotOfType('false|string', true); // passes test
assertNotOfType('false|string', false); // fails test
```

Thanks.

**Comment by ondrejmirtes** [comment]
Only `assertType('false', false);` will pass tests.

**Comment by mind-bending-forks** [comment]
I was trying to work out how to achieve something like this:

```php
assertNotType('non-empty-array<int,string>|array{null}', []);
assertNotType('non-empty-array<int,string>|array{null}', [0]);
```

**Comment by ondrejmirtes** [comment]
There's only assertType, an expression has a type, it does not have a "not type".

**Comment by mind-bending-forks** [comment]
Well, that confirms that I am not understanding then... (: I suppose I was looking to determine whether a value (e.g. `false` or `[]`) was compatible with or incompatible with a (union) type e.g. `'string|false'`. At least, that's what I assumed `assertType` would be doing, but it seems not.

**Pull request closed without merging**
