### PR TITLE
[FIX] SimpleXmlElement construct can throw exceptions

### PR DESCRIPTION
**Pull request by VincentLanglet**
See https://www.php.net/manual/fr/simplexmlelement.construct.php

Example: `new SimpleXmlElement('foo')`

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, it'd be much more effective to submit `@throws` annotation to https://github.com/jetbrains/phpstorm-stubs. PHPStan will pick it up from there. Ping me there once you do.

**Comment by VincentLanglet** [comment]
Ok the PR is opened https://github.com/JetBrains/phpstorm-stubs/pull/1020

But there will be nothing to do on this repository ?
Isn't weird to keep the line `'SimpleXMLElement::__construct' => ['hasSideEffects' => false],` ?

**Comment by ondrejmirtes** [comment]
That's correct. See this commit https://github.com/phpstan/phpstan-src/commit/9c39e0f382092e74dbbe83f7da3f65a8d92f81e9

**Comment by VincentLanglet** [comment]
it's merged @ondrejmirtes https://github.com/JetBrains/phpstorm-stubs/pull/1020

**Comment by VincentLanglet** [comment]
I'm still getting an error here: https://github.com/pepakriz/phpstan-exception-rules/pull/143

What is needed for this to be fixed ? A new phpstan release even if the PR was made on phpstorm stubs ?

**Comment by ondrejmirtes** [comment]
That's expected, the stubs are baked right into the PHAR. There's some incompatibility with the latest version that I need to look into. One test is failing and I don't know why:

```
1) PHPStan\Rules\Methods\MissingMethodParameterTypehintRuleTest::testRule
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
     💡 You can turn this off by setting <fg=cyan>checkGenericClassInNonGenericObjectType: false</> in your <fg=cyan>%configurationFile%</>.
 119: Method MissingMethodParameterTypehint\CollectionIterableAndGeneric::acceptsCollection2() has parameter $collection with generic interface DoctrineIntersectionTypeIsSupertypeOf\Collection but does not specify its types: TKey, T
     💡 You can turn this off by setting <fg=cyan>checkGenericClassInNonGenericObjectType: false</> in your <fg=cyan>%configurationFile%</>.
+170: Method MissingMethodParameterTypehint\SerializableImpl::unserialize() has parameter $serialized with no typehint specified.
 180: Method MissingMethodParameterTypehint\CallableSignature::doFoo() has parameter $cb with no signature specified for callable.
+194: Method MissingMethodParameterTypehint\SerializableImpl2::unserialize() has parameter $data with no typehint specified.
```

**Comment by ondrejmirtes** [comment]
Updated: https://github.com/phpstan/phpstan-src/commit/6bbd6290c9987267c9ceebec4bace314549a7b73

**Pull request closed without merging**
