### PR TITLE
Add non regression test for issue 8713

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/phpstan/phpstan/issues/8713

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
1) Test can run only on PHP 8+
2) Test file needs to have lint comment so that it's linted only on PHP 8+
3) This belongs on 1.9.x.

**Comment by ondrejmirtes** [comment]
Please read your diffs before you push them :)

**Comment by ondrejmirtes** [comment]
Also running the test locally would help, I see multiple problems there.

**Comment by VincentLanglet** [comment]
> Please read your diffs before you push them :)

Sorry :(

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
