### PR TITLE
progress on named argument helper

### PR DESCRIPTION
**Pull request by staabm**
implement details mentioned in https://github.com/phpstan/phpstan-src/pull/1305#issuecomment-1124874931 and remaining parts from https://github.com/phpstan/phpstan-src/pull/1301#issue-1232704394

### CODE REVIEW

**Comment by staabm** [comment]
regarding 

> And similarly, if someone calls foo(1, 2) (named arguments were not used, but some required arguments are missing), we can also return null to prevent some nasty bugs in the extensions.

atm the helper returns the call-args as is, since the helper only cares about args containing named-args.
I don't see this requirement related to the named-arguments-helper - isn't this case already handled somewhere within phpstan-core?

just added a test to demonstrate the helper returns the call unchanged.

-----

I think the helper is mostly complete as requested. next question would be on how to handle the returned `null` value. should it just be turned into a `ErrorType` on the calling sides?

**Comment by ondrejmirtes** [comment]
This is what I meant: https://github.com/phpstan/phpstan-src/pull/1313/commits/c7969d082acfe7ee1ded1f0e125ca1e6b7b1a51b?diff=unified&w=1

There's still one test failure, please fix it. And I guess it's still not called for all relevant extension types, right?

> I don't see this requirement related to the named-arguments-helper

I plan to rename the class to "ArgumentsNormalizer" in the next step so the name will no longer lie about the purpose.

**Comment by staabm** [comment]
> And similarly, if someone calls foo(1, 2) (named arguments were not used, but some required arguments are missing), we can also return null to prevent some nasty bugs in the extensions.

I have this change prepared locally but it still has some issues. at best we can merge here and progress in a new PR..?

**Comment by ondrejmirtes** [comment]
>  at best we can merge here and progress in a new PR..?

Yes :) Thank you!

**Pull request merged**
