### PR TITLE
functionMap: ZipArchive::open() returns true on success, int (error c…

### PR DESCRIPTION
**Pull request by dktapps**
…ode) on failure

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
What about `true|ZipArchive::ER_*` instead?

**Comment by dktapps** [comment]
that works? Hm, I had no idea.

**Comment by ondrejmirtes** [comment]
In that case I recommend you to check the documentation: https://phpstan.org/writing-php-code/phpdoc-types#literals-and-constants

the functionMap goes through the same parser.

**Comment by dktapps** [comment]
build failure is bogus, doesn't look related to the PR

**Comment by ondrejmirtes** [comment]
Thank you! Let me know if you find out more function types that could be upgraded with constants like this :)

**Comment by dktapps** [comment]
@ondrejmirtes Sure. I'm not actively scouring for them, but I stumble across them quite often during development :)

**Pull request merged**
