### PR TITLE
Fix OOM

### PR DESCRIPTION
**Pull request by ondrejmirtes**
Closes https://github.com/phpstan/phpstan/issues/6896
Closes https://github.com/phpstan/phpstan/issues/6911

### CODE REVIEW

**Comment by staabm** [comment]
In phpstan-dba I am also persisting Type* objects to a file.
Hopefully dropping these set_state methods will not kill this feature for me :)

**Comment by ondrejmirtes** [comment]
Oh, good to know. Maybe you could persist their description only, and then unserialize the description using TypeStringResolver?

**Comment by staabm** [comment]
Will double check tomorrow

**Comment by ondrejmirtes** [comment]
Don't worry, I'm not gonna release a BC break, I'm gonna keep the cleanup for 2.0 :) Just suggesting something that I'm probably gonna do here too.

**Comment by herndlm** [comment]
nice pragmatical solution for the MemoryCacheStorage

**Pull request merged**
