### PR TITLE
feat: add utility `Exclude`, to exclude values from union

### PR DESCRIPTION
**Pull request by Kocal**
Hi!

This PR adds a new utility "type" `exclude`, inspired by [`Exclude` from TypeScript](https://www.typescriptlang.org/docs/handbook/utility-types.html#excludeuniontype-excludedmembers).

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, if you need this, you can achieve it with a custom TypeNodeResolverExtension in your project. Right now I don't want this, for multiple reasons:

1) It breaks if someone has a class called `Exclude`.
2) Not all types are subtractable - it doesn't always work.

The type description syntax for this is `mixed~string` for example, but it actually doesn't show up in error messages.

**Comment by Kocal** [comment]
This is understandable, but so does it mean PHPStan will never introduce some TypeScript utility type like `Pick`, `Omit`, `Partial`... ?

**Comment by ondrejmirtes** [comment]
The problem with that is that everyone wants these to behave differently. I recently read a tweet from TypeScript maintainer that he regrets these are actually included in TS, specifically for this reason.

So a 3rd party package with custom TypeNodeResolverExtension for these utility types would be the way to go.

**Comment by ondrejmirtes** [comment]
This is the tweet: https://twitter.com/SeaRyanC/status/1540022634846466048

I hope I understood it correctly.

**Comment by Kocal** [comment]
Hum alright, I didn't know about this tweet and it makes sens. 

Thanks!

**Pull request closed without merging**
