### PR TITLE
Acknowledge that array<string, something> may still have integer keys

### PR DESCRIPTION
**Pull request by dktapps**
This "feature" is extremely annoying to me, more so because PHPStan will complain if I cast a key that came from iterating over an `array<string, something>`.

Personally, I think this should _not_ be benevolent at all - it's bit me on the ass more times than I can count, and I would much appreciate if PHPStan reported it properly.
But in keeping with the rest of the code, and to just shut it up about useless casts, I opted for the BUT.

Opening this to get CI feedback since it's a pain to run the tests on Windows.

### CODE REVIEW

**Comment by staabm** [comment]
could you create a snippet on phpstan.org to show a example when a `array<string, ...>` can contain an `int`?

**Comment by dktapps** [comment]
@staabm it's really easy to reproduce. Use a numeric string as an array key and it gets casted to int.

I limited the change to getIterableKeyType() since iteration seems to be the only place where it's actually a problem. The rest of the time the key casting doesn't matter, but for iteration it's a major pain in the ass and the cause of a significant percentage of PM crashes.

**Comment by dktapps** [comment]
On local, I changed this to use a non-benevolent union type, and discovered 25 places in PM where this problem could legitimately occur. I **really** think this should be treated with non-benevolence.

**Comment by johnbillion** [comment]
This is indeed true. TIL. https://3v4l.org/o7VWB

**Comment by dktapps** [comment]
If you use strict_types=1 it will bite you on the ass at some point. It's very annoying to me that PHPStan doesn't report the problem. I ended up banning direct iteration on arrays with string keys (see https://github.com/pmmp/PocketMine-MP/commit/269231c2283375b7a1794a0d03c1e1b05b9dcf4a) but it doesn't completely solve the problem (e.g. array_key_first/last and array_rand() will still bite me at some point).

**Comment by ondrejmirtes** [comment]
This is a hard problem and I don't want to make all of these errors rain on PHPStan's users...

**Comment by ZebulanStanphill** [comment]
It would be good to at least acknowledge this shortcoming in the docs somewhere though, right?

@dktapps Would you consider making your custom rule available as a separate extension? I might want to use it in my own project.

**Comment by dktapps** [comment]
> It would be good to at least acknowledge this shortcoming in the docs somewhere though, right?
> 
> @dktapps Would you consider making your custom rule available as a separate extension? I might want to use it in my own project.

I guess I can do that.

**Pull request closed without merging**
