### PR TITLE
use conditional parameter for is_a() via stub

### PR DESCRIPTION
**Pull request by staabm**
is_a: if third argument is false then do not allow string in first argument

refs https://github.com/phpstan/phpstan/issues/4371

### CODE REVIEW

**Comment by staabm** [comment]
remaining errors are caused by the more strict parameter type

**Comment by ondrejmirtes** [comment]
What about `string` instead of `class-string`? That preserves the previous behaviour.

**Comment by staabm** [comment]
> What about `string` instead of `class-string`?

I am fine with that.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
