### PR TITLE
Composer > Define allowed plugins

### PR DESCRIPTION
**Pull request by ruudk**
Needed for Composer 2.2.0 (found with 2.2.0-RC1)
```
composer self-update --preview
```

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Is this also needed for https://github.com/phpstan/extension-installer ? Please send a README update to that repo as well, thanks.

**Comment by ruudk** [comment]
I think people that use the extension-installer in _their project_ need to approve it. It will be a default Composer feature that people will become familiar with. Not sure what to add to that readme

**Comment by ondrejmirtes** [comment]
Well to mention the same configuration we added here.

**Comment by ruudk** [comment]
There you go: https://github.com/phpstan/extension-installer/pull/41

**Pull request merged**
