### PR TITLE
generics: disallow variance definition other than in class or interface

### PR DESCRIPTION
**Pull request by hrach**

### CODE REVIEW

**Comment by hrach** [comment]
Build failures seems unrelated.

**Comment by ondrejmirtes** [comment]
I'd like to hear @muglug's opinion whether it makes sense to allow and read @template-covariant above functions and methods.

My opinion is that it's not entirely wrong to use that, in a world where you're able to materialize function `foo<T of Foo>` as a type - invariant version would only accept `foo<Foo>`, covariant version would also accept `foo<Bar>` where Bar extends Foo.

**Comment by hrach** [comment]
Yes, I will have to give it a thought. I wanted to disable it here as there is no point having declaration site variance for functions but it is actually use-site variance with the same syntax :D

**Comment by muglug** [comment]
`@template-covariant` doesn't really make sense to me for methods – does it exist in other languages?

**Comment by hrach** [comment]
Ok, seems its not supported anywhere, I researched some langs and added this info explicitly into table: https://hrach.dev/posts/variance-elsewhere/

**Comment by ondrejmirtes** [comment]
Please fix the build and I'll merge it (PHP 8 tests are now expected to fail.)

It's enough to run GenericsIntegrationTest locally and commit the updated JSON files.

**Comment by hrach** [comment]
Done, thanks!

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
