### PR TITLE
Add debugger function

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes https://github.com/phpstan/phpstan/issues/3765

### CODE REVIEW

**Comment by szepeviktor** [comment]
I'm totally clueless.
Add a noop command (in this PR) and a rule that does the actual work???

**Comment by ondrejmirtes** [comment]
There are many rules in this codebase itself... The core logic of this rule would look something like this:

```php
public function getNodeType(): string
{
    return FuncCall::class
}

public function processNode(Node $node, Scope $scope): array
{
    if ($node->name !== '\PHPStan\dumpType)') {
        return [];
    }

    return [$scope->getType($node->args[0]->value)->describe(VerbosityLevel::describe())];
}
```

**Comment by szepeviktor** [comment]
Here I am. I hope someone helps me (me === not a developer).

**Comment by ondrejmirtes** [comment]
Superseded by: https://github.com/phpstan/phpstan-src/commit/c24c8ef699a8cd3b73d355bfd1e7d0b0ff4fc11f

Thanks.

**Comment by szepeviktor** [comment]
Thank *you*

**Pull request closed without merging**
