### PR TITLE
Fix incorrect array size when using unset

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/6488

### CODE REVIEW

**Comment by staabm** [comment]
build failures seem unrelated and should be fixed by https://github.com/phpstan/phpstan-src/pull/972

**Comment by ondrejmirtes** [comment]
Please rebase because of the conflict (add new lines at the bottom of the dataProvider, not the top), otherwise 👍

**Comment by staabm** [comment]
rebased

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
