### PR TITLE
Improve wording of the NonexistentOffset, BooleanAndConstantConditionRule and BooleanOrConstantConditionRule

### PR DESCRIPTION
**Pull request by VincentLanglet**
Related to https://github.com/phpstan/phpstan/issues/8187#issuecomment-1286169876

I feel like 
```
Offset 'c' does not exist on array{c?: int}.
```
is confusing and 
```
Offset 'c' might not exist on array{c?: int}.
```
is better.

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
We can't do this because it'd break existing baselines. We can do this only with a new bleedingEdge toggle.

A similar thing could be fixed in BooleanAndConstantConditionRule and BooleanOrConstantConditionRule where the message still uses `&&` and `||` even for logical `and` and `or` operators.

**Comment by herndlm** [comment]
new bleeding edge toggle kind of means that it will get into the next major automatically, right?
sounds like a good solution then, otherwise it would need to be remembered / noted down :)

**Comment by ondrejmirtes** [comment]
Exactly, and no rebase nightmare either.

**Comment by VincentLanglet** [comment]
Yeah, I'll update the PR

**Comment by VincentLanglet** [comment]
> We can't do this because it'd break existing baselines. We can do this only with a new bleedingEdge toggle.

Done

> A similar thing could be fixed in BooleanAndConstantConditionRule and BooleanOrConstantConditionRule where the message still uses `&&` and `||` even for logical `and` and `or` operators.

Done

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
