### PR TITLE
Optimize `NonexistentOffsetInArrayDimFetchCheck`

### PR DESCRIPTION
**Pull request by herndlm**
This special handling for constant arrays should not be needed and the nested dim loop can break the outer type loop already if it found something to report ($report will not get any more true than true :)).

### CODE REVIEW

**Comment by herndlm** [comment]
hmm it looks like this is reverting parts or all of the levels changes of the recently merged https://github.com/phpstan/phpstan-src/pull/1684. I was not entirely sure about this there and I'm not sure about it here..

oooh I think I know why now.. `TypeUtils::map()` basically aborts when it finds an unmatched type in https://github.com/phpstan/phpstan-src/blob/1.8.8/src/Type/TypeUtils.php#L212. The 2 new array type getters don't do that. So I guess this PR here should be fine, but that behaviour change is a bit dangerous

**Comment by herndlm** [comment]
I'm leaning more and more to adding very specific methods to the two array types that can be used in the return type extensions for the array functions. E.g. `filter()`. I added some recently already anyways, like `ConstantArrayType::pop()` or so.  I think we could get rid of most of the `getArrays()` and `getConstantArrays()` calls with all the conditional logic then and slim down the extensions but blow up the types. I can try it out maybe tomorrow with one if you're interested. And for rules like this one we shouldn't even need them preferably Maybe that's a good way to move forward. Not sure what to do with the two new methods then and if they really should be part of the API :)

Anyways, not much related to this PR which should be ready

**Comment by ondrejmirtes** [comment]
> I'm leaning more and more

Yes please :)

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
