### PR TITLE
Use TypeUtils::getOldConstantArrays in array_reduce extension

### PR DESCRIPTION
**Pull request by herndlm**
This is only doing emptyness checks and for that optional keys don't need to be considered AFAIK.

### CODE REVIEW

**Comment by herndlm** [comment]
What if I eventually manage to get rid of all `getConstantArrays`? Deprecate it? Not in favor of the internal `getOldConstantArray` I guess? 😅

One of my plans is to try to get rid of `ConstantArrayType::powerSet` as much as possible, preferable make it hard to use it indirectly. But there's still a bit of work needed for that. And a plan of what to use instead then for e.g. `ConstantArrayType::getAllArrays`, `TypeUtils::flattenTypes`, `TypeUtils::getArrays`, and of course `TypeUtils::getConstantArrays`. Good thing though is: some of them are rarely used yet.

**Comment by ondrejmirtes** [comment]
I'd expect to deprecate both methods on TypeUtils and just introduce Type::getConstantArrays() that would basically behave the same way as getOldConstantArrays and would be a drop-in replacement.

Yeah, and deprecate places that call powerSet too.

**Comment by herndlm** [comment]
sounds like a plan and I have a goal then :) sorry for jumping between things btw, but this here is bugging me also for a while already..

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
