### PR TITLE
Correct \Phar::decompress() return data type

### PR DESCRIPTION
**Pull request by peter-gribanov**
Correct `\Phar::decompress()` and `\PharData::decompress()` return data type.
Fix https://github.com/phpstan/phpstan/issues/2908

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Can you rewrite the existing items instead of adding duplicate keys at the end? Thank you.

**Comment by peter-gribanov** [comment]
@ondrejmirtes sorry for this. The file is too large and i cold not find the definition of Phar.

**Comment by peter-gribanov** [comment]
Add fix for `\Phar::compress()` and `\PharData::compress()`.
https://www.php.net/manual/en/phar.compress.php#refsect1-phar.compress-returnvalues
https://www.php.net/manual/en/phardata.compress.php#refsect1-phardata.compress-returnvalues

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
