### PR TITLE
Accept derived template types

### PR DESCRIPTION
**Pull request by arnaud-lb**
Template types in non-parameter locations are extra strict about what they accept, as they will only accept a type strictly equal to themselves (same name, scope, bound, and implementation).

This PR relaxes this a bit so that template types recognizes that they can be derived. They will now accept an other template type with equal name+scope and whose bound is a sub-type of the accepting type's bound.

I believe that this is still correct because as long as two template types have the same name+scope, they are in fact the same type.  

This fixes https://github.com/phpstan/phpstan/issues/5844 and https://github.com/phpstan/phpstan/issues/5706.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Awesome! Hold on, I'm looking into the failures.

**Comment by ondrejmirtes** [comment]
Oh yes, the fact these errors move to level 7 is actually nice.

**Comment by arnaud-lb** [comment]
I've just fixed the failures. Some rule errors have migrated from level 3 to level 7.

I'm not 100% sure about this PR, though. There may be some scenarios where the type will not be correct.

**Comment by ondrejmirtes** [comment]
It's fine, it's better than before and users will let us know if we missed something sooner or later :)

**Comment by ondrejmirtes** [comment]
phpstan-symfony still failing, I'm looking into it, otherwise it's good!

**Pull request merged**
