### PR TITLE
Support array-shapes in "array_merge"

### PR DESCRIPTION
**Pull request by voku**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Unfortunately I had to revert this extension: https://github.com/phpstan/phpstan-src/commit/53817aad4e13d06861381247ce3b8a1d79dcc167

It's because of performance impact on real-world projects. The extension itself may not be the fault but it proves that having more ConstantArrayType instances during analysis leads to a slowdown.

The only way I see is to build a benchmarking mode into PHPStan itself that would compare the analysis times of project files and point out which file slowed down after this commit. Then isolate what exactly in that file causes it and try to optimize that. Unfortunately it's not my priority right now.

**Comment by voku** [comment]
Understand. Is there a way we can overwrite the extension? Currently the first matched extension always winns.

**Comment by ondrejmirtes** [comment]
It's not possible. Everybody has to use the same `array_merge` extension that's in the core. I'd rather solve the problem than provide workarounds around it.

**Comment by voku** [comment]
> It's not possible. Everybody has to use the same `array_merge` extension that's in the core. I'd rather solve the problem than provide workarounds around it.

Maybe it's the "UnionType" change that has a bad performance impact? https://github.com/phpstan/phpstan-src/pull/641/files#diff-235402991c12d4f1091a88a9c19ed82c38749ed4e4dce1322474ed6c6d7fdcc8L40 Do you have a public repo to test the performance?

**Comment by ondrejmirtes** [comment]
I don't. Right now you'd have to try the commit where the extension was still in (before the reverts) and try observing the performance impact on some of your projects.

**Comment by ondrejmirtes** [comment]
Giving this another try :) https://github.com/phpstan/phpstan-src/pull/1653

**Comment by ondrejmirtes** [comment]
Oh, ArrayMergeFunctionDynamicReturnTypeExtension already supports constant arrays...

**Pull request merged**
