### PR TITLE
Add getOriginalNode() method on ClassPropertyNode

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by ondrejmirtes** [comment]
What do you need this for?

**Comment by samsonasik** [comment]
First, it is for consistency with other virtual node, 
Second, I was experimenting to set scope on original node on rector side, when calling `NodeScopeResolver::processNodes()`, while only detected is `ClassPropertyNode` over original `Property` node.

**Comment by ondrejmirtes** [comment]
The point of ClassPropertyNode is that it abstracts away Param and Property. It doesn't make sense to offer getOriginalNode because users would have to make if-else condition in their code about these two node types.

You can still hook your custom rector onto Param or Property, they do not disappear.

**Comment by samsonasik** [comment]
Ok 👍

**Pull request closed without merging**
