### PR TITLE
Add check for mixed

### PR DESCRIPTION
**Pull request by VincentLanglet**
This PR is not ready to be merged, it's more a try and a way to start the discussion about how can be improved the checks made on `mixed` type @ondrejmirtes.

With `testCallMethodsOnMixed`, I succeed to get an error for the call 
```
$valueMixed->fooMethod()
```
Every methods of `MixedType` was returning a `TrinaryLogic::createYes();`. A `TrinaryLogic::createMaybe();` seems more logic to me. But I need to see the impact for every others rules.

Since adding the check for the mixed seems to be a big change, I was thinking of a new level: I create the `checkMixed` argument in `RuleLevelChecker` and a level `9` for phpstan.

I don't know the role of the `$isExplicitMixed` property, so I didn't use it.
This seems to be the difference between
```
function foo($value) {}
```
And
```
/**
 * @param mixed $value
 */
function foo($value) {}
```

Maybe a way to do a less strict rule (and maybe avoid to create a new level) would be to report an error only for explicit mixed value...

Could close https://github.com/phpstan/phpstan/issues/845

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, this is a big undertaking that will need quite a lot of work over many PRs.

 It's not the right time in the development cycle to add a new level. I'd start just by adding `checkMixed` parameter which users can optionally turn on. Once we're happy with the checks, we can add the level 9.

Some remarks:

1) There are many rules that should be modified - method calls on mixed, property accesses, constant accesses, array fetches, putting into foreach, passing mixed as an argument to function/method, etc. The only thing that it's fine to do with mixed is passing it somewhere mixed is also expected.
2) Once these rules are implemented with `checkMixed` (and maybe even multiple parameters like that), and we do some real-world testing with real-world codebases, we might realize that it won't be a question of just a single level addition, but maybe multiple levels. But it's too soon for that now - we know too little of real-world implications.
3) We should only touch `PHPStan\Rules` and not `PHPStan\Type`. I always want `mixed` to nod to everything.
4) Maybe we can achieve the wanted behaviour by changing RuleLevelHelper, but we should go through the related rules to see the implications. Maybe we'll realized that we need to change each rule "by hand", which isn't a big deal since the tests for all rules should be modified (add something like `testCheckMixed` anyway).
5) The final PHPStan level should be about disallowing `MixedType` in any expression. But in real-world codebases this will lead to tens of thousands of errors. It's also too soon to do that.
6) The difference between implicit and explicit `MixedType` is as you said - missing typehint vs. `mixed` typehint. It might also be reported on different levels if we find it a good idea based on some real-world data.

**Comment by VincentLanglet** [comment]
> Hi, this is a big undertaking that will need quite a lot of work over many PRs.

I agree. I wanted to see if it was possible to help for this since I would like this feature.

> It's not the right time in the development cycle to add a new level. I'd start just by adding `checkMixed` parameter which users can optionally turn on. Once we're happy with the checks, we can add the level 9.

I removed the level 9.

> 1. There are many rules that should be modified - method calls on mixed, property accesses, constant accesses, array fetches, putting into foreach, passing mixed as an argument to function/method, etc. The only thing that it's fine to do with mixed is passing it somewhere mixed is also expected.

Yes, I tried with only one rule in order to see the difficulty.

> 3. We should only touch `PHPStan\Rules` and not `PHPStan\Type`. I always want `mixed` to nod to everything.

Why `mixed` should nod to everything ?

I understand that changing the `PHPStan\Type` will break a lot of stuff. But I feel like it's still easier to change `PHPStan\Type` rather than all the `PHPStan\Rules`. When someone will create a new Rule, he'll forget to do 
```
if (!$type->canCallMethods()->yes() || $type instanceof MixedType) {
```
And will check only `!$type->canCallMethods()->yes()`.

Maybe introducing a `StrictMixedType` type or a `$strict` property in the `MixedType` could be an idea. And the ruleHelper will return a stricter `MixedType` if the rule `checkMixed` is on.

Maybe the right call would be to return `TrinaryLogic::createMaybe()`  and change some `$foo->yes()` checks by `!$foo->no()`. But that's also a big change.

> 4. Maybe we can achieve the wanted behaviour by changing RuleLevelHelper, but we should go through the related rules to see the implications. Maybe we'll realized that we need to change each rule "by hand", which isn't a big deal since the tests for all rules should be modified (add something like `testCheckMixed` anyway).

If the work is made by changing `Type` instead of `Rule` we maybe can avoid to go through all the rules.

> 5. The final PHPStan level should be about disallowing `MixedType` in any expression. But in real-world codebases this will lead to tens of thousands of errors. It's also too soon to do that.

Do you mean that I should stop the PR ?

> 6. The difference between implicit and explicit `MixedType` is as you said - missing typehint vs. `mixed` typehint. It might also be reported on different levels if we find it a good idea based on some real-world data.

My personal needs was the following:
https://phpstan.org/r/ebe3319d-8579-4070-b1e8-cef359fe81ac
I wanted an error because I forgot to add the `instanceof` check.

In my case, I explicitly say the $value is mixed. So I had another idea to implement this: modify the `MixedType` and using the following check...
```
$this->isExplicitMixed ? TrinaryLogic::createMaybe() : TrinaryLogic::createYes();
```
This could lead to less errors in real-world codebases

When you don't use typehint for the $value, PHPStan won't report an error because he's lacking of informations to deduce something, but if you explicitly say it's mixed, you expect PHPStan to not treat the $value as having specific properties, methods, ... otherwise you would have used a more precise typehint, don't you ?
When I started to use PHPStan I was personally surprised this wasn't the default behaviour with mixed.

**Comment by VincentLanglet** [comment]
> My personal needs was the following:
> https://phpstan.org/r/ebe3319d-8579-4070-b1e8-cef359fe81ac
> I wanted an error because I forgot to add the `instanceof` check.
> 
> In my case, I explicitly say the $value is mixed. So I had another idea to implement this: modify the `MixedType` and using the following check...
> 
> ```
> $this->isExplicitMixed ? TrinaryLogic::createMaybe() : TrinaryLogic::createYes();
> ```
> 
> This could lead to less errors in real-world codebases
> 
> When you don't use typehint for the $value, PHPStan won't report an error because he's lacking of informations to deduce something, but if you explicitly say it's mixed, you expect PHPStan to not treat the $value as having specific properties, methods, ... otherwise you would have used a more precise typehint, don't you ?
> When I started to use PHPStan I was personally surprised this wasn't the default behaviour with mixed.

Based on my personal needs I made a smaller PR.

I introduced a `checkExplicitMixed` options. If you use it and the `MixedType` is explicitly mixed, you'll receive error if you try to access property, constant, method, offset, etc...

I made some change in the code: 
- Now, `array<ValueType>` is no the same than `array<mixed, ValueType>`, it would be more something like `array<implicitMixed, ValueType>`.
- In a similar way, `mixed[]` is not the same than `array`.
- When you write `public function ($foo)` the `$foo` param was explicitly mixed, now it's not if you don't say it in the PhpDoc.
I can't say if it's breaking change since the tests are still green.

Without these changes, using `checkExplicitMixed` would lead to a lot of errors in real code base. I think it's a smaller step this way, the rule is the following: 
"If you type-hint as mixed, it's an explicitly mixed and you'll receive error if you try to access property, method, etc on it".

This PR would need more tests for rule with error for explicitly mixed value. But if you have time, I would love to have your opinion on this @ondrejmirtes. Am I going in a good direction ? Would you be interested ?

**Comment by VincentLanglet** [comment]
@ondrejmirtes I have added multiple checks for explicitMixed.

Does this PR interest you ? I can add "Explicit mixed" check for every rules if so. It's pretty quick.

Thanks to the `shouldCheckMixed` methods, checking non explicit mixed should be easy too. But I think it's better to have two options `checkExplicitMixed` and `checkMixed`.

**Comment by VincentLanglet** [comment]
Hi @ondrejmirtes,

I'll be happy to finish this PR if it does interest you.
What do you think about it ?

**Comment by VincentLanglet** [comment]
Hi @ondrejmirtes,

I'll be happy to fix the conflict and finish this PR if it does interest you.
What do you think about it ?

**Comment by ondrejmirtes** [comment]
Hi, sorry to keep you waiting. I'm currently busy with static reflection and I can't devote time into another project because this one needs finishing first :) I thought about this and there are multiple angles:

1) That mixed is passed only as an argument into another mixed parameter.
2) That nothing is called on mixed, that it's not passed into foreach, that it's not accessed as an array etc.
3) Think about how implicit vs. explicit mixed should be checked.
4) That no expression in code is mixed (aka "totally typed").

It's possible we'd want to check these concerns on different levels as it's possible it would flag too many things at once.

Your PR currently changes too many things at once:

* TypeNodeResolver and TemplateMixedType: changing whether `mixed` is implicit/explicit... I don't want this change, it's been change the other way already once.
* Changes to behaviour in MixedType. I'm also not sure if I want these, I'm not sure about the implications. Too many things in PHPStan rely
* Various reformattings in tests unrelated to the other changes.

I thought that these checks could be implemented only on the rules side. Because `mixed` will never appear in unions with other types, `Type::*` methods don't have to change, it can be checked only in the rules, not in the type system.

**Comment by VincentLanglet** [comment]
> Hi, sorry to keep you waiting. I'm currently busy with static reflection and I can't devote time into another project because this one needs finishing first :) 

No problem. I understand is not an easy project and there could be other priority.
I didn't lose my time and worked on other things.
It was just a friendly reminder in order to see if I should continue this PR :)

> I thought about this and there are multiple angles:
> 
> 1. That mixed is passed only as an argument into another mixed parameter.
> 2. That nothing is called on mixed, that it's not passed into foreach, that it's not accessed as an array etc.

This is mainly these checks that I'm interested in.

My issue is that when I wrote something like
```
class Foo extends Bar
{
    /**
     * @param mixed $param
     */
    public function doThings($param)
    {
         $param->getSomething()
         ...
    }
```
I want phpstan to require a `instanceof` check.

> That no expression in code is mixed (aka "totally typed").

There could be a smaller step: no implicit mixed.
In typescript there is `noImplicitAny` config option.

> Your PR currently changes too many things at once:
> 
> * TypeNodeResolver and TemplateMixedType: changing whether `mixed` is implicit/explicit... I don't want this change, it's been change the other way already once.

What is the reason ?
Currently `array`  is the same than `array<mixed, mixed>`.
I considered that when you write `array` the mixed type is implicit and when you write `array<mixed, mixed>` it's explicit. It doesn't sound bad to me.

I see an advantage. If you introduce a level with `checkExplicitMixed` and another level with `checkMixed`. `array` would only be checked in the second one, when `array<mixed, mixed>` would be checked in the first one. The `checkExplicitMixed` level would be easier to reach.

> * Changes to behaviour in MixedType. I'm also not sure if I want these, I'm not sure about the implications. Too many things in PHPStan rely

I don't know exactly why I did this, I have to check again. But I think I can do without this change.

> * Various reformattings in tests unrelated to the other changes.

I don't think I had done extra-work in the tests...
I added an extra test for every rule I modified. And sometimes I had to add a dependency, so it changed others tests, but that was all the changes I made, IIRC.

> I thought that these checks could be implemented only on the rules side. Because `mixed` will never appear in unions with other types, `Type::*` methods don't have to change, it can be checked only in the rules, not in the type system.

I'll try to revert changes in MixedType, and to change only the rule.

But I recommend to think again about the change in the `TypeNodeResolver` about whether `mixed` is implicit/explicit.

**Comment by ondrejmirtes** [comment]
OK, so this is basically complete level 9 you asked for :) It wasn't that hard after all: https://github.com/phpstan/phpstan-src/commit/da0b2eba99c1721ff409aff6e7de3da4029b7b10

I'd like if more rules were tested like I tested CallMethodsRule. Please test `checkExplicitMixed` setting on a real project and report back. Thank you.

**Comment by ondrejmirtes** [comment]
About the previous discussion - yes, I consider `array` as an alias of `mixed[]` and I don't want to change that.

**Comment by ondrejmirtes** [comment]
Wow, just tried to run it on PHPStan itself and it's super-annoying :) Perfect case for a new level 9 :D

**Comment by VincentLanglet** [comment]
> OK, so this is basically complete level 9 you asked for :) It wasn't that hard after all: [da0b2eb](https://github.com/phpstan/phpstan-src/commit/da0b2eba99c1721ff409aff6e7de3da4029b7b10)
> 
> I'd like if more rules were tested like I tested CallMethodsRule. Please test `checkExplicitMixed` setting on a real project and report back. Thank you.

Whoah ! Nice !

I'll check it for sur. Should I wait 0.12.26 version ?

**Comment by ondrejmirtes** [comment]
You can test the dev-master now, and I’d appreciate similar tests for all the rules that have RuleLevelHelper injected as I did for CallMethodsRule.

**Comment by VincentLanglet** [comment]
> I’d appreciate similar tests for all the rules that have RuleLevelHelper injected as I did for CallMethodsRule.

Sure I will try this week. Any rule you would prioritize for the test ?

**Comment by VincentLanglet** [comment]
@ondrejmirtes The `checkExplicitMixed` seems to work well on my project.

There is just one thing that is debatable.
```
/**
 * @return mixed
 **/
function foo(array $options) {
  //...  
}

/**
 * @return string
 **/
function bar() {
  return $this->foo($params);
}

/**
 * @return string
 **/
function baz() {
  /** @var string $foo */
  $foo = $this->foo($params);

  return $foo;
}
```
Return an error, bar is returning mixed instead of string.
Baz is the solution I found to avoid the error.

Maybe bar shouldn't report an error... I don't know all the implications.

Still, big thanks !

**Comment by ondrejmirtes** [comment]
I'd start with NonexistentOffsetInArrayDimFetchRule because it looks the most tricky - don't forget to test `mixed` as both as the array type and the dimension type.

About your piece of code - `foo()` states that it returns `mixed` but `bar()` must return `string` - looks like the rules do their job correctly to point this out.

Also, please read up on inline `@var`, it really shouldn't be used: https://phpstan.org/writing-php-code/phpdocs-basics#inline-%40var

**Comment by dktapps** [comment]
Is it intentional that universal object crates are not checked? The following code doesn't report any error:
```
<?php

namespace test;

function a(\stdClass $c) : string{
	return $c->iMightNotBeAString;
}
```

**Comment by ondrejmirtes** [comment]
Depends on how the return type of `__get` of such class is defined: https://github.com/phpstan/phpstan-src/blob/f8a6cf15af670871596ff36bbdd14a6826811980/src/Reflection/Php/UniversalObjectCratesClassReflectionExtension.php#L71-L88

And it falls back to implicit mixed, so yeah, this isn't checked.

**Pull request closed without merging**
