### PR TITLE
Fix sapi_windows_set_ctrl_handler signature

### PR DESCRIPTION
**Pull request by Seldaek**
I hope this is the correct way to note that it is optional https://www.php.net/sapi_windows_set_ctrl_handler

### CODE REVIEW

**Comment by adaamz** [comment]
Optional format is when you add `=` as suffix to parameter name - in this case `add=`.

I think there is some info about formats in top of this file.

**Comment by Seldaek** [comment]
I see.. Looks like https://github.com/phan/phan/blob/master/src/Phan/Language/Internal/FunctionSignatureMap_php74_delta.php#L46 is up to date btw. Kind of a shame and a waste of time to duplicate this effort.

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by ondrejmirtes** [comment]
About the duplicate effort - previously it wasn't that easy to reuse this information as the static analysers weren't on-par with each other so the maps in each one used incompatible syntax but now it would be easier. Another source of truth are jetbrains/phpstorm-stubs and PHP 8 itself will also contain more of the similar information. So I'd rather like to depend on phpstorm-stubs and PHP 8 than trying to merge different data from Phan and Psalm that branched off a long time ago :) I guess time will solve this one.

**Pull request merged**
