### PR TITLE
more precise sprintf() return type on constant formats

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/7387

### CODE REVIEW

**Comment by kukulich** [comment]
I think the regex is not complete. The `printf` format is `%[argnum$][flags][width][.precision]`

- Argument number is a little strange for this use case but the support should be there.
- Other use cases: https://3v4l.org/u0vgj

**Comment by kukulich** [comment]
See the regexp here: https://github.com/slevomat/slevomat/blob/524e8b676b66115f6e48cd189007253911209b18/build/PHPStan/Rules/PrintfPlaceholderTypeMatchRule.php#L121

**Comment by staabm** [comment]
> I think the regex is not complete. The `printf` format is `%[argnum$][flags][width][.precision]`

absolutely. I did a first step with this PR which covers the initially reported issues.
I am fine with adding more coverage though, but the PR as is already provides value IMO.

**Comment by rvanvelzen** [comment]
Do you think something like [this](https://github.com/rvanvelzen/phpstan-src/commit/002a12f5e999ba830956995adcd1dfc5989d0723) makes sense as well?

**Comment by staabm** [comment]
> Do you think something like [this](https://github.com/rvanvelzen/phpstan-src/commit/002a12f5e999ba830956995adcd1dfc5989d0723) makes sense as well?

I guess it depends on which use-cases the added complexity will cover. might be easier to think about it, when seeing actual NodeScopeResolverTest-cases

**Comment by staabm** [comment]
@ondrejmirtes just rebased and it should be good to go

I will work on the mentioned features/comments in separate followup PRs regarding

> Do you think something like [this](https://github.com/rvanvelzen/phpstan-src/commit/002a12f5e999ba830956995adcd1dfc5989d0723) makes sense as well?

and

> I think the regex is not complete. The `printf` format is `%[argnum$][flags][width][.precision]`
> 
>     * Argument number is a little strange for this use case but the support should be there.

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
