### PR TITLE
composer: allow Symfony 5

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by hrach** [comment]
Omfg. Please, Ondřej, merge this. This is 4th in a week.

**Comment by ondrejmirtes** [comment]
Wake up. It doesn't make sense and doesn't solve any problem.

**Comment by TomasVotruba** [comment]
It actually blocks the install

image

**Comment by ondrejmirtes** [comment]
Some time ago I split the source code in phpstan/phpstan into phpstan/phpstan-src. phpstan-src isn't a published Packagist package. That's why it doesn't have to support Symfony 5 here. It might make sense to help me upgrade to Symfony 5 to improve the contributor experience of PHPStan itself, but not for its users. That's not a pressing issue and I guess not a goal of this PR.

When PHPStan 0.12 is released in a week, `phpstan/phpstan` won't depend on Symfony at all, there will be no conflict. Until then, if you want to use Symfony 5, you can use `phpstan/phpstan-shim`.

Don't force me to merge something that doesn't make any, even marginal, technical sense. You're just behind the current developer status of the repository.

**Comment by pepakriz** [comment]
Any reason why not to merge it to the 0.11.x branch? Because in our project we currently can't use shim version (a lot of customizations...)

**Comment by ondrejmirtes** [comment]
@pepakriz If you can't use the shim version now, you won't be able to use PHPStan 0.12 at all. Please tell me what's blocking you and I'll try to look into it.

**Comment by pepakriz** [comment]
@ondrejmirtes 0.12 is not released yet and the current master branch is very unstable (tested a week ago). I know we should switch to shim, but it takes some time and Symfony 5 is already released and we'd like to use it.

**Comment by TomasVotruba** [comment]
Shim doesn't help. Same command that worked before now fails:

image

**Comment by ondrejmirtes** [comment]
Yes, if you have custom compiler extensions, you're not compatible with phpstan-shim and you're not going to be compatible with PHPStan 0.12. Since compiler extensions are only for some syntax sugar inside configuration files, you can always live without them.

I need help testing this from you guys, I'm surprised you're finding about this now.

**Comment by TomasVotruba** [comment]
CI report: https://travis-ci.org/TomasVotruba/friendsofphp.org/jobs/616060402#L316

**Comment by ondrejmirtes** [comment]
You need to get rid of the DecoratorExtension here: https://github.com/Symplify/PHPStanExtensions/blob/master/config/config.neon

**Comment by ondrejmirtes** [comment]
If I understand its usage correctly, it's breaking `conditionalTags` section that some PHPStan extensions use. The `phpstan.rules.rule` tag shouldn't always be applied.

**Comment by ondrejmirtes** [comment]
@TomasVotruba Also I realized you're not able to use custom errors formatters with phpstan-shim which is something I'll fix before 0.12.

**Pull request closed without merging**
