### PR TITLE
Fix class name validate method

### PR DESCRIPTION
**Pull request by mvorisek**
improve https://github.com/phpstan/phpstan-src/commit/428baf5f91fa623a51c236a899f308408b3d85fd

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I can't accept this without a test.

**Comment by mvorisek** [comment]
The test is in the previous PR, if you want to test `$cl = '\\\\stdClass'`, please add test, I am not familiar with the testing system.

**Comment by mvorisek** [comment]
Also, class name starting with `\\` should throw an error for strict phpstan configuration.

**Comment by ondrejmirtes** [comment]
Add a line to `tests/PHPStan/Rules/Classes/data/bug-5002.php` that should report an error, add the expected error to `InstantiationRuleTest::testBug5002()`.

**Comment by mvorisek** [comment]
Test was there, but incorrect, as `'\\x'` equals to `\x`. And when corrected, CI shows:
```

1) PHPStan\Rules\Classes\InstantiationRuleTest::testBug5002
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'
+'-1: Internal error: Class \\Test\Foo does not exist
+Run PHPStan with --debug option and post the stack trace to:
+https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
 '

/home/runner/work/phpstan-src/phpstan-src/src/Testing/RuleTestCase.php:173
/home/runner/work/phpstan-src/phpstan-src/tests/PHPStan/Rules/Classes/InstantiationRuleTest.php:347
```

please finish this PR that the regex validation is really used

**Comment by mvorisek** [comment]
@ondrejmirtes please help finish this PR

**Comment by ondrejmirtes** [comment]
If you rebase on master you'll see that the test fails with this exception:

```
1) PHPStan\Rules\Classes\InstantiationRuleTest::testBug5002
ReflectionException: Class "\\Test\Foo" does not exist

/Users/ondrej/Development/phpstan/src/Reflection/Runtime/RuntimeReflectionProvider.php:93
/Users/ondrej/Development/phpstan/src/Reflection/ReflectionProvider/ClassBlacklistReflectionProvider.php:54
/Users/ondrej/Development/phpstan/src/Reflection/ReflectionProvider/ChainReflectionProvider.php:30
/Users/ondrej/Development/phpstan/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php:37
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:2452
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:2434
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:591
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:293
/Users/ondrej/Development/phpstan/src/Analyser/MutatingScope.php:1414
/Users/ondrej/Development/phpstan/src/Analyser/MutatingScope.php:587
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:1680
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:590
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:293
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:611
/Users/ondrej/Development/phpstan/src/Analyser/NodeScopeResolver.php:250
/Users/ondrej/Development/phpstan/src/Analyser/FileAnalyser.php:190
/Users/ondrej/Development/phpstan/src/Analyser/Analyser.php:74
/Users/ondrej/Development/phpstan/src/Testing/RuleTestCase.php:138
/Users/ondrej/Development/phpstan/tests/PHPStan/Rules/Classes/InstantiationRuleTest.php:347
```

The problem is that the code execution shouldn't reach that line. `hasClass` should return false but it doesn't.

**Comment by mvorisek** [comment]
rebased, class name validation does not still apply

**Comment by ondrejmirtes** [comment]
In current code there's no internal error. Which means the fault is in this PR. Unfortunately I can't help you with that, but you're definitely equipped to debug it by yourself :)

**Comment by mvorisek** [comment]
This PR is to fix the regex only. `isValidClassName` method must be however called prior `ReflectionException: Class "\\Test\Foo" does not exist`

https://3v4l.org/2rN2q regex is working

**Comment by ondrejmirtes** [comment]
I figured out the problem: https://github.com/phpstan/phpstan-src/commit/a2c878ab441ec11a4eec62834e96b82bec33009e

So please rebase your branch and make the tests pass.

**Comment by mvorisek** [comment]
`isValidClassName` should be used for assertion if class name is valid or not, here are 3 usecase: https://phpstan.org/r/c8098ca7-3a17-4f07-92ea-87df0d7950d5 , in all of 3, something like "Invalid class name xxx" error must be printed.

**Comment by ondrejmirtes** [comment]
`/** @var` is not validated at all: https://phpstan.org/writing-php-code/phpdocs-basics#inline-%40var

**Comment by mvorisek** [comment]
what is the purpose of closing one PR in favor of a brand new one?

**Comment by ondrejmirtes** [comment]
So that the PR does not clutter the list of open PRs in case the creator doesn't show up again.

**Pull request closed without merging**
