### PR TITLE
Support array shape covariance

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/9905

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Jackpot! Look at issue bot. This also fixes:

* https://github.com/phpstan/phpstan/issues/5655
* https://github.com/phpstan/phpstan/issues/7273

Please add regression tests. Thank you.

**Comment by staabm** [comment]
ha, didn't realize it… 🥳

**Comment by herndlm** [comment]
Amazing. Looks like I also debugged around in those 2 issues and then the fix is a one-liner 🎉

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
