### PR TITLE
change variableTypes to save by exprString

### PR DESCRIPTION
**Pull request by rajyan**
first step of 
https://github.com/phpstan/phpstan/issues/8191

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Awesome, can't wait to merge it 😊

**Comment by ondrejmirtes** [comment]
BTW I appreciate how perfect this first step is, getting those two things closer together 😊

**Comment by rajyan** [comment]
I thought to do "merge variableTypes, moreSpecificTypes and conditionalExpressionTypes" in this PR, but changed my mind. Smaller PR is better!
Each steps can be separated in different PRs. :smile:

**Comment by ondrejmirtes** [comment]
Exactly! This way we get earlier feedback if we broke something 😊 and it's easier to review. Thank you very much.

**Pull request merged**
