### PR TITLE
fix DOMDocument::createTextNode return type

### PR DESCRIPTION
**Pull request by medilies**

### CODE REVIEW

**Comment by medilies** [comment]
I don't understand why this failed

**Comment by ondrejmirtes** [comment]
The failures are unrelated to your PR, but please rebase this on top of 1.10.x as the bot says.

**Comment by medilies** [comment]
please tell me how you rebased it :p

**Comment by ondrejmirtes** [comment]
I didn't, I just changed the base here in the UI.

What you need to do on your side is to rebase your commit on top of 1.10.x. Something like this:

```
git rebase --onto origin/1.10.x HEAD^
```

And then force-push it.

**Comment by medilies** [comment]
bruh

**Pull request closed without merging**
