### PR TITLE
Don't auto-resolve conditional types

### PR DESCRIPTION
**Pull request by rvanvelzen**
Auto-resolving seems very useful, but doesn't allow inspecting the original type

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I'd argue it doesn't make sense for >>conditional return type<< to be supported in `@param`. Or do you want to keep them just to have them reported in a rule?

**Comment by rvanvelzen** [comment]
Indeed, to clarify that they're not supported at all in anything else than return types.

**Comment by ondrejmirtes** [comment]
Awesome. There's quite a lot of places where types can be written in PHPDocs (you can check them in PhpDocNodeResolver), but maybe it's worth it to only report the most common ones like `@var` (above property and in function bodies) and in `@param`.

**Comment by ondrejmirtes** [comment]
Fun fact: Until recently you could have written `@template` above a property, but it didn't do anything useful, it just confused parts of the code and gave confusing error messages.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
