### PR TITLE
Add missing Redis::role() method to functionMap

### PR DESCRIPTION
**Pull request by steffenweber**
https://github.com/phpredis/phpredis/blob/5.3.6/redis.c#L3403

https://redis.io/commands/role

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
This isn't sufficient. First and foremost this method needs to exist in https://github.com/jetbrains/phpstorm-stubs. Post a link to the PR here, thanks.

**Comment by steffenweber** [comment]
https://github.com/JetBrains/phpstorm-stubs/pull/1337

**Comment by steffenweber** [comment]
The phpstorm-stubs pull request has been merged.

**Comment by ondrejmirtes** [comment]
And this PR will get merged once the checks pass :) https://github.com/phpstan/phpstan-src/pull/954

**Pull request closed without merging**
