### PR TITLE
Make result-cache independent from configs include order

### PR DESCRIPTION
**Pull request by staabm**
closes  https://github.com/phpstan/phpstan/issues/8778

tested via https://github.com/phpstan/phpstan/pull/9857

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by staabm** [comment]
@ondrejmirtes any plans for a new release? I think this change will save us minutes on every commit in CI

**Comment by ondrejmirtes** [comment]
You don't have to hypothesize, you can verify it by requiring `1.10.x-dev` 😊 Please report back the numbers.

**Comment by staabm** [comment]
if my testing in CI works as itended I can see PHPStan now using the cache, while it didn't before.
(I guess because of the extension loading order in our complex setup)

this means instead of a full project analysis which takes **~5min**, it now only takes **~30secs** because of cache utilization per commit.
(several phpstan invocations involved, because of a monorepo)

**Comment by ondrejmirtes** [comment]
Rector using result cache doesn't make any sense.

**Comment by staabm** [comment]
I had a typo in my above comment. I updated it to say "PHPStan" not rector" ;)

**Comment by ondrejmirtes** [comment]
Alright, can you please test the dev version anyway?

**Comment by staabm** [comment]
> Alright, can you please test the dev version anyway?

I did. thats the numbers for the dev version

**Comment by ondrejmirtes** [comment]
Alright, thank you 😊

**Comment by staabm** [comment]
for reference - full project analysis on my local machine of the same project

```
$ vendor/bin/phpstan --version
PHPStan - PHP Static Analysis Tool 1.10.x-dev@19801d9

$ time composer phpstan
...
real    2m47.226s
user    0m0.015s
sys     0m0.000s
```

vs.

```
$ vendor/bin/phpstan --version
PHPStan - PHP Static Analysis Tool 1.10.33

$ time composer phpstan
...
real    2m40.789s
user    0m0.000s
sys     0m0.030s
```

**Pull request merged**
