### PR TITLE
Always inspect intersections in TypeUtils

### PR DESCRIPTION
**Pull request by herndlm**
I just want to figure out what the impacts are. Tbh, I don't understand why they are ignored, but it hid a problem in an issue and I started to think why they should be even ignored at all..

### CODE REVIEW

**Comment by staabm** [comment]
I guess you already researched the commit, but in case not: `$inspectIntersections` was added with https://github.com/phpstan/phpstan-src/commit/9f9a57feaa23a27ac0b1b0a71609ccc5a7d7f0b6 and the contained unit test might help you understand whether its still useful

**Comment by ondrejmirtes** [comment]
TypeUtils is just a bunch of hacks that shouldn't exist. Correct solutions is to have all these methods directly on Type so that each Type can truthfully answer them without some weird `if` statements :)

**Comment by ondrejmirtes** [comment]
The end-goal is to completely ban `instanceof *Type` because: https://phpstan.org/developing-extensions/type-system#querying-a-specific-type

**Comment by ondrejmirtes** [comment]
But the Type interface is gonna have dozens, maybe even hundreds of methods for each use-case, how to make that usable is still in question :)

**Comment by ondrejmirtes** [comment]
Each time I remove `instanceof *Type` and introduce a clean method on Type, it fixes a few bugs :) One example is `instanceof ArrayType` -> `Type::isArray()`.

**Comment by herndlm** [comment]
Right, but if nothing breaks here - should we remove it or rather not touch this? So far it looks like it at least improves things.

I'd also rather get rid of many things / usages here though. Maybe I can start with something.

**Comment by herndlm** [comment]
On the other hand this will be unneeded if features are removed. I just have the gut feeling that right now is not the best time to add new type functions. Except I  want to annoy both of you hehe

But indeed it feels like moving some more basic features to the types. Might also help in better handling constant arrays maybe hmm

**Comment by herndlm** [comment]
ok so it looks like this is working just fine without ignoring intersections, but I can't say for sure what it tried to fix. the test is still there and green apparently. I assume it tried to work around some kind of weird type intersection maybe
I'm not sure what's correct here, but I recently had a case where it would not find the array in smth like `array{foo?: bool bar?: bool}&non-empty-array` just because of that non-empty-array and that lead to some invalid offset rule not reporting which was weird. Maybe it makes sense to try to add a test for that..

**Comment by ondrejmirtes** [comment]
Yeah, if we're not sure what the impact is, I'd vote against it. As I said, it's not ideal anyway, I'd rather fix bugs by introducing new methods on Type :)

**Comment by herndlm** [comment]
sure, ok. thx for the input

**Pull request closed without merging**
