### PR TITLE
[WIP] Add DatePeriod::getEndDate dynamic return type

### PR DESCRIPTION
**Pull request by Alban-io**
Resolve https://github.com/phpstan/phpstan/issues/5953

### CODE REVIEW

**Comment by Alban-io** [comment]
Currently my test works only because `MethodCall` is directly the constructor `(new DatePeriod($start, $interval, $recurrences))->getEndDate()`.  

Is there a way to retrieve the constructor arguments from [this method](https://github.com/phpstan/phpstan-src/pull/762/files#diff-6d03c67b8fa9b904420b0d451db91068a9b3d330c95ca5cdaa14dadb53f3a45fR29) ?

**Comment by staabm** [comment]
I think, the object on which the method is called on, is available via https://github.com/nikic/PHP-Parser/blob/99a24b6a556cb2f85c48f62a5311cbc1f8b6eb92/lib/PhpParser/Node/Expr/MethodCall.php#L13

and you might resolve it via the scope to the actual object.

**Comment by Alban-io** [comment]
I've already tried it but I couldn't find the constructor arguments types from `MethodCall->var` only object type :confused:

**Comment by staabm** [comment]
isn't the 3rd arg returned by getRecurrences?

**Comment by Alban-io** [comment]
Not really, `DatePeriod` are 3 constructors :  

```php
public __construct(
    DateTimeInterface $start,
    DateInterval $interval,
    int $recurrences,
    int $options = 0
)

public __construct(
    DateTimeInterface $start,
    DateInterval $interval,
    DateTimeInterface $end,
    int $options = 0
)

public __construct(string $isostr, int $options = 0)
```

The 3rd arg can have three types : `null`, `int`, `DateTimeInterface`.

 `null` or `int` 
```php
public getEndDate(): null
public getRecurrences(): int
```


 `DateTimeInterface`
```php
public getEndDate(): DateTimeInterface
public getRecurrences(): null
```

**Comment by Alban-io** [comment]
I think `DynamicMethodReturnTypeExtension` may not be the right choice.

Another way :  

Create an Type-Specifying Extensions but I feel like they are not available with constructor (`New_`), only available on `Method`, `StaticMethod` and `Function`.

@ondrejmirtes What is your point of view about that ?

**Comment by ondrejmirtes** [comment]
What logic you want to implement in a dynamic return type extension for the constructor?

**Comment by ondrejmirtes** [comment]
Superseded by https://github.com/phpstan/phpstan-src/pull/951 for now. Feel free to open a new PR with improvements.

**Comment by ondrejmirtes** [comment]
This would require making DatePeriod generic with two template types - for endDate and recurrences count.

**Comment by Alban-io** [comment]
Is it possible to make [conditional return type](https://psalm.dev/articles/conditional-love) with PHPStan ?

```php
<?php

/**
 * @template T of int|\DateTimeInterface|null
 */
class TestDatePeriod {

	/** @var T */
	private $value;

	/**
	 * @param T $value
	 */
	public function __construct($value)
	{
		$this->value = $value;
	}

	/**
	 * @psalm-return (T is \DateTimeImmutable ? \DateTimeImmutable : null)
	 * @phpstan-return (T is \DateTimeImmutable ? \DateTimeImmutable : null)
	 */
	public function getEndDate(): ?DateTimeImmutable
	{
		return $this->value instanceof \DateTimeInterface ? new DateTimeImmutable() : null;
	}

	/**
	 * @psalm-return (T is \DateTimeInterface ? null : int)
	 * @phpstan-return (T is \DateTimeInterface ? null : int)
	 */
	public function getRecurrences(): ?int
	{
		return is_int($this->value) ? 0 : null;
	}
}

$intExpected = fn(int $value): int => $value + 1;
$dateExpected = fn(\DateTimeInterface $dateTime): \DateTimeInterface => $dateTime;

$datePeriod = new TestDatePeriod(new DateTimeImmutable());
$dateExpected($datePeriod->getEndDate());
$intExpected($datePeriod->getRecurrences());

$datePeriod = new TestDatePeriod(55);
$dateExpected($datePeriod->getEndDate());
$intExpected($datePeriod->getRecurrences());

$datePeriod = new TestDatePeriod(null);
$dateExpected($datePeriod->getEndDate());
$intExpected($datePeriod->getRecurrences());
```

**Comment by canvural** [comment]
@Alban-io [Not yet.](https://github.com/phpstan/phpstan/issues/3853)

**Comment by ondrejmirtes** [comment]
But you can write a dynamic return type extension for the same purpose.

**Comment by ondrejmirtes** [comment]
You need to write a DatePeriod generic stub that describes return types of thos two metods, and write a `DynamicStaticMethodReturnTypeExtension` for the constructor that returns different GenericObjectType based on the arguments.

The stub can look like this:

```php
/**
 * @template TEnd of ?DateTimeInterface
 * @template TRecurrences of ?int
 */
class DatePeriod
{

	/**
	 * @return TEnd
	 */
	public function getEndDate()
	{
		
	}

	/**
	 * @return TRecurrences
	 */
	public function getRecurrences()
	{
		
	}
}
```

**Comment by Alban-io** [comment]
It seems to work, great 😃  https://github.com/Alban-io/phpstan-src/commit/ad22b8b9d2e4b70a827ab3b89749e1ff8b208853

Do you want a new PR or reopen this one ?

**Comment by ondrejmirtes** [comment]
Please open a new PR.

**Pull request closed without merging**
