### PR TITLE
Fix unreferenced data providers

### PR DESCRIPTION
**Pull request by jlherren**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Wow, this is bad :) Thank you very much.

**Comment by jlherren** [comment]
Er... I'm confused, did you mean to not merge it?

**Comment by ondrejmirtes** [comment]
I’m sorry, I meant to merge it, don’t know what happened 🙁 Can you please rebase because of the conflict? Thank you very much!

**Comment by ondrejmirtes** [comment]
Thank you, test failures are unrelated :)

**Pull request merged**
