### PR TITLE
tests: remove duplicated file with wrong name casing

### PR DESCRIPTION
**Pull request by hrach**
There is also (duplicated) `bug2574.php`

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, we can't remove it like this, the build will star failing on case-insensitive filesystems: https://travis-ci.org/phpstan/phpstan-src/jobs/632627352#L271-L275

Do you have any suggestions how to do it right?

**Comment by hrach** [comment]
Sorry, I don't understand, how `GenericsIntegrationTest::testLevels` works with `Bug2574.php`? The `bug2574.php` should be still in repo. (https://github.com/phpstan/phpstan-src/blob/76e8283e4bce9299abc7e4d8ab738b5850721043/tests/PHPStan/Generics/data/bug2574.php vs https://github.com/phpstan/phpstan-src/blob/76e8283e4bce9299abc7e4d8ab738b5850721043/tests/PHPStan/Generics/data/Bug2574.php)

**Comment by ondrejmirtes** [comment]
It looks like Git removes both files when this branch is checked out on macOS or Windows.

**Comment by ondrejmirtes** [comment]
Please open the PR again if you figure this out. Thank you.

**Pull request closed without merging**
