### PR TITLE
fixed non-falsy-string inference with '0'

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/7877
closes https://github.com/phpstan/phpstan/issues/7881

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Please add a test for https://github.com/phpstan/phpstan/issues/7881 😊

**Comment by staabm** [comment]
done. added another fix & test caused by the initial patch

**Comment by staabm** [comment]
built error seems unrelated

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
