### PR TITLE
Add ThrowableReturnTypeExtension

### PR DESCRIPTION
**Pull request by herndlm**
Closes https://github.com/phpstan/phpstan/issues/6001

Based on feedback of the first approach in https://github.com/phpstan/phpstan-src/pull/767#issuecomment-970242253

### CODE REVIEW

**Comment by herndlm** [comment]
I'm still unsure when it comes to tests in phpstan - is this assert test enough?

**Comment by ondrejmirtes** [comment]
Yes, thank you!

**Comment by Seldaek** [comment]
Are you sure this is the best way to handle this? And if it is only PDOException could we not return string only for that class, and leave getCode as an int for other classes?

I am asking because as per https://phpstan.org/r/610c7193-7cba-46eb-be15-b9f09c91728f it is a bit weird IMO that a clear int case is seen as string|int, which forced me to do https://github.com/composer/composer/commit/84f8fda0c6e75dbaa19b4333e1956ff8c2c09b8f to fix these errors https://github.com/composer/composer/actions/runs/1638602292

**Comment by ondrejmirtes** [comment]
@Seldaek We've had `Exception::getCode()` and `Throwable::getCode()` as only `int` in the past but it was wrong in many cases.

We haven't tried `Exception::getCode()`and `Throwable::getCode()` to be `int|string`, `PDOException::getCode()` as `string` and any other subclass to be `int` but I think it's certain there's going to be userland exceptions that use `string` as well...

**Comment by Seldaek** [comment]
I tried redefining getCode to add an int return type but it's final so I couldn't, so I'm not sure what those userland exceptions would be? Exceptions in extensions perhaps..

**Comment by ondrejmirtes** [comment]
@Seldaek You can do this crazy thing: https://3v4l.org/vcWJg

**Comment by Seldaek** [comment]
OK, although I would argue that is totally voiding the warranty and shouldn't mean PHPStan covers your ass with a mixed return type. I suspect many things can be broken in similar ways or with reflection or who knows what..

**Comment by Seldaek** [comment]
https://www.php.net/manual/en/exception.getcode.php clearly documents it as returning an int, so IMO an exception for PDO as it's insane but part of core makes sense, but everything else should be int, and those people doing insane shit can ignore their errors instead of forcing everyone else to do so.

**Comment by ondrejmirtes** [comment]
Alright, I'm eager to try my suggestion from https://github.com/phpstan/phpstan-src/pull/795#issuecomment-1003700362 too: https://github.com/phpstan/phpstan-src/commit/11817175c9977a835d8a0dcc6f8edf2d87744b47

Let's see what the integration tests and the feedback will say :)

**Comment by ondrejmirtes** [comment]
Try out 1.3.2 :) https://github.com/phpstan/phpstan/releases/tag/1.3.2

**Comment by Seldaek** [comment]
Thanks, looks good to me now, and sorry for the rant :D

**Comment by Seldaek** [comment]
https://github.com/composer/composer/commit/508ac051eced468dc3a37a9da5e54351bcb1d8f4 🎉

**Comment by Seldaek** [comment]
Ahh well now I'm left with https://github.com/composer/composer/runs/4736711738?check_suite_focus=true which makes sense of course.. There's no way to tell PHPStan to narrow down the return type for getCode is there? Redefining with `@method` did not seem to help.

**Comment by ondrejmirtes** [comment]
Yeah, this might be actually solved for good, until someone notices that some exception from a popular framework like Symfony or Doctrine also misuses this :D

The fact that @method doesn't work here surprised me, I'm gonna look into it.

**Comment by Seldaek** [comment]
At least adding this to SolverProblemsException's class docblock did not help, maybe I did it wrong tho:

```
 * @method self::ERROR_DEPENDENCY_RESOLUTION_FAILED getCode()
```

**Comment by Seldaek** [comment]
Maybe it's effects is negated by the ThrowableReturnTypeExtension?

**Comment by ondrejmirtes** [comment]
Good guess, that was it: https://github.com/phpstan/phpstan-src/commit/e04cc8dfb8f6b3a2c4ac399232a6691baed1d162

**Comment by Seldaek** [comment]
Nice :) Thanks a bunch

**Comment by ondrejmirtes** [comment]
Enjoy 1.3.3 :) https://github.com/phpstan/phpstan/releases/tag/1.3.3

**Comment by Seldaek** [comment]
It builds 👍🏻 https://github.com/composer/composer/commit/64d39a9655462a8fcabaa15a431674b41100e127

**Pull request merged**
