### PR TITLE
Some mysqli functions always return true

### PR DESCRIPTION
**Pull request by kamil-tekiela**
https://github.com/php/doc-en/commit/18d96d58e38ff747678163d6a01dcb946e6810a7

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
PHPStan already knows this: https://phpstan.org/r/992b11b1-4192-459c-bb23-362f6a4e086e

**Comment by kamil-tekiela** [comment]
It doesn't seem it knows: https://phpstan.org/r/205aa72d-5f1f-476f-b6f0-6f748280140e
Maybe I made some mistake in my PR, but the demo here shows that it thinks the type is bool.

**Comment by ondrejmirtes** [comment]
That should be fixed in official stubs in php-src. PHPStan uses automatically extracted signatures and there it's still `bool`: https://github.com/phpstan/php-8-stubs/blob/main/stubs/ext/mysqli/mysqli_field_seek.php

In php-src: https://github.com/php/php-src/blob/17b3af29589ef5667c44dae7aaa11f1018e6949b/ext/mysqli/mysqli.stub.php#L1460

Compare that with mysqli_close: https://github.com/phpstan/php-8-stubs/blob/main/stubs/ext/mysqli/mysqli_close.php + https://github.com/php/php-src/blob/17b3af29589ef5667c44dae7aaa11f1018e6949b/ext/mysqli/mysqli.stub.php#L1592

**Comment by kamil-tekiela** [comment]
PR is waiting to be merged https://github.com/php/php-src/pull/11948

**Pull request closed without merging**
