### PR TITLE
Add CommandLine ExcludeAnalyse parameter

### PR DESCRIPTION
**Pull request by patrizia-wacht**
Add new paramater for commandline to exclude paths on analyse-command, implementation using the existing config parameter exclude_anaylse functionality.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, I appreciate your contribution but I don't think it's useful to have multiple ways of doing the same thing, especially when people appreciate more stuff being in the config and not having to type it out every time you run PHPStan...

**Comment by patrizia-wacht** [comment]
Hallo Ondrej,

generally that is right, but then why there level, error-format and other paramters in both possible? 

I <3 phpstan for better code-quality. It is really very helpful. We want add this package to our coding-standard package, this includes also other static analyse tools, all have a exculde-paramter in commandcli. We use all with checking blacklist and whitelist paths. To solve this with configfile I am forced to generate a configfile on the flye before start phpstan-command. Or have you maybe another suggestion? I very thankful for help,

Regrads
Patrizia

**Comment by ondrejmirtes** [comment]
Thank you for your kind words! Yes, if there’s already a way to do something by the user, I prefer the core not to be modified because of that reason. I like the open-closed principle a lot 😊

So generating the config file is the way to go! 😊 There’s nette/neon package for that.

**Comment by patrizia-wacht** [comment]
Thank you. 

I think you mean with the NeonAdapter:dump() ?

**Comment by ondrejmirtes** [comment]
Neon::encode()

**Pull request closed without merging**
