### PR TITLE
Add PossiblyDivisionByZero rule

### PR DESCRIPTION
**Pull request by VincentLanglet**
First try of the implementation of PossiblyDivisionByZero

The config declaration is missing. At which level should I add this @ondrejmirtes ? (with a conditional tag ?)

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Any recommendation about the level I should add this rule @ondrejmirtes ?

**Comment by VincentLanglet** [comment]
Friendly ping @ondrejmirtes.

To finish this PR I just need to know to which level I should add this rule ? Should it be under bleeding edge ?

**Comment by ondrejmirtes** [comment]
Hi, let's try it on level 7 to see how annoying it'd be. It's correct but I worry too annoying in practice.

I want to see it without bleedingEdge first, to test it on real projects in CI.

**Comment by ondrejmirtes** [comment]
Also - base it on 1.9.x.

**Comment by staabm** [comment]
As a followup it might be usefull to cover modulo division by zero?

**Comment by VincentLanglet** [comment]
> As a followup it might be usefull to cover modulo division by zero?

Nice idea. I've added the support. I just need now to understand what is wrong with my config.

**Comment by VincentLanglet** [comment]
The PR is now ready :)

**Comment by VincentLanglet** [comment]
Friendly reminder @ondrejmirtes, just in case ^^

**Comment by ondrejmirtes** [comment]
The pipeline results show that although correct, this would really be annoying in practice...

**Comment by VincentLanglet** [comment]
> The pipeline results show that although correct, this would really be annoying in practice...

For every projects tested where there is failure about possibly division by zero there is not a lot and adding a check wouldn't hurt. But I understand the "annoying" thing.

Should it be an option then ?

**Comment by ondrejmirtes** [comment]
I feel like PHPStan doesn't have to contain every custom rule idea under an option. I encourage you to publish and market your own package for this problem. Similar to how https://github.com/Roave/no-floaters is done.

**Comment by VincentLanglet** [comment]
> I feel like PHPStan doesn't have to contain every custom rule idea under an option. I encourage you to publish and market your own package for this problem. Similar to how https://github.com/Roave/no-floaters is done.

I just had a new thought about this rule and start to think this is not needed, and maybe should not exists.

The following code could be considered as correct
```
/**
 * @throws DivisionByZeroError
 */
public function compute(int $int): float {
     return 42 / $int;
}
```
And PHPStan is already correctly reporting the DivisionByZeroError when using the exception features.

I totally forgot about this because I had
```
exceptions:
        uncheckedExceptionClasses:
                - Error
```

I guess I cannot modify the config to say "I'd like to ignore all the Error, except DivisionByZeroError". ^^'

**Pull request closed without merging**
