### PR TITLE
feat: disable tips via config

### PR DESCRIPTION
**Pull request by DrWursterich**
Hi, I'd like to be able to configure wether tips are displayed or not, which is what this pr adds.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
What's your use-case for disabling tips? I worry that someone could turn this off but then they're gonna post a support question that would already be answered by the tip, so this would be a net-negative for both parties.

**Comment by DrWursterich** [comment]
That is a fair point.

Mainly it's the unicode symbol `💡` I would like to prevent beeing output. `--ansi` does not hide them.

**Comment by ondrejmirtes** [comment]
Yeah, I'd accept a change that's more smart about this.

**Comment by DrWursterich** [comment]
Okay, I understand. I will probably not have the time to implement this.

Thanks for the quick answers and have a nice day!

**Pull request closed without merging**
