### PR TITLE
Use current PHP version in CallToFunctionParametersRuleTest

### PR DESCRIPTION
**Pull request by herndlm**
Working on something in `FunctionCallParametersCheck` which is tested via `CallToFunctionParametersRuleTest` but realised that the PHP version was hard-coded to 8.0 which is blocking me there. Also: bigger range of tests over multiple PHP versions, yay :) in general there seem to be many rules where similar things could be done.

Unfortunately this causes a small conflict in 2.0.x apparently.

UPDATE: Markus made me aware of https://github.com/phpstan/phpstan-src/pull/3662 and I adapted the named arguments test to be skipped exactly the same way to avoid troubles there.

### CODE REVIEW

**Comment by herndlm** [comment]
ah, I just saw that `CallMethodsRuleTest` uses the current PHP version dynamically, **but** for the named arguments test it forces it to 8.0. Which method are we preferring? I see it has a `disallow-named-arguments.php` test, maybe that's the way to go then. Or something like marking the test skipped if the PHP version is too low? 🤔 😅

for the bug fix / feature PR I'm preparing it doesn't matter. I just need to be able to have a dynamic PHP version in this test file.

**Comment by staabm** [comment]
Please note: we are working on the same files

https://github.com/phpstan/phpstan-src/pull/3662

**Comment by herndlm** [comment]
> Please note: we are working on the same files
> 
> #3662

Oh, not good.. The scope dependent php version functionality is 2.x only, right? I'm also OK with the skipping approach of course, the constructor is conflicting any way..

**Comment by staabm** [comment]
> The scope dependent php version functionality is 2.x only, right? 

yes

> I'm also OK with the skipping approach of course, the constructor is conflicting any way..

no its fine. lets see which one is merged earlier :)

**Comment by staabm** [comment]
ahh this looks great now, thanks

**Comment by herndlm** [comment]
> ahh this looks great now, thanks

for a moment I thought I broke gitlab though with all my back and forth .. xD  apparently it wasn't happy with me force-pushing back to an old state hmm. anyway, closer to yours now, yeah

Screenshot From 2024-12-02 20-53-31

**Comment by herndlm** [comment]
btw I have a PR prepared which adapts a rule dealing with an high-upvoted bug. but it would need this small test change first. would be great if this can be merged :)

**Comment by herndlm** [comment]
@ondrejmirtes after this I was planning to fix https://github.com/phpstan/phpstan/issues/11418, or do you consider that to be a new feature, then I can just skip this and work on 2.x after https://github.com/phpstan/phpstan-src/pull/3662 was merged.

I don't want to pressure you, just trying to figure out what the best approach is to avoid conflicts/issues.

**Comment by ondrejmirtes** [comment]
This https://github.com/phpstan/phpstan-src/pull/3662 basically fixes the same problem, so in order to avoid conflicts, I'm closing this. Thanks.

**Pull request closed without merging**
