### PR TITLE
MethodReturnStatementsNode: add getClassMethod

### PR DESCRIPTION
**Pull request by janedbal**
This method would be very handy in my case, do you think we can expose it?

I'm trying to analyse all methods with extra analysis on their returns, but I also need to check the class and method even when void is returned.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
`$scope->getFunction()` doesn't give you the right method?

**Comment by janedbal** [comment]
It does, but I still didn't find the way to retrieve `PhpParser\Node\Stmt\ClassMethod` easily from public api from the `PhpMethodFromParserNodeReflection`. It is always in private/protected method/field only.

**Comment by janedbal** [comment]
But I think I can work with reflection only in my case... feel free to close this If you find it useless.

**Comment by ondrejmirtes** [comment]
The question is whether you need the AST or whether `MethodReflection` is sufficient - it should be.

**Comment by janedbal** [comment]
In my case, reflection was sufficient. Closing, thx

**Pull request closed without merging**
