### PR TITLE
checkImplicitMixed

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Draft of checkImplicitMixed option as discussed in https://github.com/phpstan/phpstan/discussions/7835

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Would be nice to actually test this somewhere :) Pick a rule when there's already `checkExplicitMixed` tested, and add a case for the implicit mixed.

Both changes in RuleLevelHelper should actually have a test. Thanks!

**Comment by ondrejmirtes** [comment]
Also, the test should show that `false` doesn't report an error, and `true` does. `@dataProvider` is ideal for that.

**Comment by MartinMystikJonas** [comment]
I tried to find some test where checkExplicitMixed is tested but all I found is just tests for specific bugs so I was not sure how this test should look like. Should I add new testCheckImplicitMixed() with some minimal input? Or copy some basic method like https://github.com/phpstan/phpstan-src/blob/401ae3e82f165b716263dac8d8f0cff63a1c8958/tests/PHPStan/Rules/Methods/CallMethodsRuleTest.php#L41 with same input and just modify expected errors?

**Comment by ondrejmirtes** [comment]
Don't copy this huge test, that's a maintenance nightmare :) Just add a small one, to show the differences.

**Comment by MartinMystikJonas** [comment]
OK I will do it tomorrow ;-)

**Comment by MartinMystikJonas** [comment]
Test added. Based on explicit mixed test I found in CallMethodsRuleTest.

**Comment by MartinMystikJonas** [comment]
I have another suggestion. I would welcome option that would allow casting implicit/explicit mixed. It is currently not allowed when checkXMixed is used.  Maybe add new option allowCastMixed or two options allowCastXMixed? I think it would be enough to check it in findTypeToCheck of RuleLevelHelper right?

**Comment by ondrejmirtes** [comment]
I really like how you made these two options independent :) Thank you very much!

**Comment by ondrejmirtes** [comment]
About your suggestion - I don't get it, can you give me a code sample?

**Comment by MartinMystikJonas** [comment]
At level 9 casting explicit mixed to string is not allowed. With implicit mixed option it would not be allowed for implicit mixed too.

https://phpstan.org/r/33a99c16-a95b-41c9-94bf-30e8404dd8cf

**Comment by ondrejmirtes** [comment]
If you want you can just ignore this with a regex. But IMHO it's a valid error.

**Comment by MartinMystikJonas** [comment]
That is what we do now. I just think it would be nice to have built-in support for ignoring such errors because it is often used. BUt I can live with just ignoring it.

**Comment by MartinMystikJonas** [comment]
I just found out problems with checkImplicitMixed option. See https://phpstan.org/r/fbdaf0db-cf77-4cce-827f-63ca9facfaee

It seems that access lelel-2 key access to array with undefined structure always raises error even ehoen used in context where it is valid like in isset or setting array value.

But I do not know how to fix that.

**Comment by MartinMystikJonas** [comment]
@ondrejmirtes I am not sure what to do now. I can prepare failing test but I do not know where to even start with fixing it.

**Comment by ondrejmirtes** [comment]
It's expected, and I think it's not specific to implicit mixed. You can see the same thing with explicit mixed: https://phpstan.org/r/50a04edc-93f4-4871-981a-8d1147500d02

I think this error is desirable. You can fatal-crash PHP with some types and this construct: https://3v4l.org/oPMeC

**Comment by MartinMystikJonas** [comment]
But here it is known it is an array and it works without errors on level 9.

**Comment by ondrejmirtes** [comment]
Because `static $cache` is implicit mixed on purpose. We'd have to have some analysis of the whole function body to figure out what types it can be. There's an open issue for it.

**Comment by MartinMystikJonas** [comment]
Oh I see. Problem is that you do not know if value of static is not set to someting completely different later and picked up in next call.

**Comment by ondrejmirtes** [comment]
Please send a documentation update here: https://phpstan.org/config-reference#stricter-analysis

Editing the page: https://github.com/phpstan/phpstan/edit/1.8.x/website/src/config-reference.md

**Comment by MartinMystikJonas** [comment]
Ok I will write it

**Comment by MartinMystikJonas** [comment]
See https://github.com/phpstan/phpstan/compare/1.8.x...MartinMystikJonas:phpstan:patch-1

**Comment by ondrejmirtes** [comment]
Please open a PR :)

**Pull request merged**
