### PR TITLE
Add rule that disallows final private methods

### PR DESCRIPTION
**Pull request by herndlm**
Closes https://github.com/phpstan/phpstan/issues/7507

Refs: https://wiki.php.net/rfc/inheritance_private_methods

Is this going in the right direction? I'm unsure about a few details, e.g.
- is bleeding edge needed?
- is the php version check needed?
- is it ok to be ignorable? (it's "only" a warning after all)

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you! I took the liberty to mark it as ready and merge it :)

About your questions - you made everything correct in your PR :) The ignorability is questionable, I'm 50-50 in this case.

**Comment by herndlm** [comment]
Oh, he's back :)
OK perfect, thx!

**Comment by ondrejmirtes** [comment]
Oh yes, I was on vacation and I have some more vacations planned this summer, so there are gonna be a few more breaks from processing the inbox :) The work breaks are nice but I'm gonna start missing the work eventually I think :)

**Comment by ondrejmirtes** [comment]
I also wanted to tag PHPStan 1.8.1 on July 1st before leaving, but I couldn't crack a bug I introduced so I hope I'll be able to solve it now that I'm recharged :)

**Comment by ondrejmirtes** [comment]
Oh, I have an immediate bug report for you :) This doesn't apply to constructors so it shouldn't be reported for them: https://3v4l.org/qZkFv

**Pull request merged**
