### PR TITLE
Report always false usages of is_a

### PR DESCRIPTION
**Pull request by b1rdex**
Fixes https://github.com/phpstan/phpstan/issues/4371

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, could you achieve the same behaviour by modifying IsAFunctionTypeSpecifyingExtension instead? The `ImpossibleCheckTypeHelper` is there to course-correct mainly "weird" information from extensions, so making the fix in `IsAFunctionTypeSpecifyingExtension` might be a little harder, but much more correct. Thanks.

**Comment by b1rdex** [comment]
If I understand `IsAFunctionTypeSpecifyingExtension` correctly, it's used to set the type of $object var. Should I implement `DynamicFunctionReturnTypeExtension` also or what?

**Comment by ondrejmirtes** [comment]
@b1rdex Nope, just the logic of `IsAFunctionTypeSpecifyingExtension` needs to be modified, there's a general dynamic return type extension for type-specifying functions.

**Comment by b1rdex** [comment]
So I finally learned the thing:
```php
return $this->typeSpecifier->create(
	$node,
	new ConstantBooleanType(false),
	$context
);
```

sets the function return type to `false`. That's what we need... But it won't generate any error message. How do I test it? I tried
```
if (is_a(Bar::class, Foo::class)) {
	dumpType(is_a(Bar::class, Foo::class));
}
```
and it dumps `false` w/o any errors reported on `max` level. Also, looks like the type specifying works only in conditional context – I tried
```
if ($a = is_a(Bar::class, Foo::class)) {
	dumpType($a);
}
```
and it dumps `true` which is impossible.

**Comment by staabm** [comment]
@ondrejmirtes I think we can close this one as well then

**Comment by staabm** [comment]
> If I understand IsAFunctionTypeSpecifyingExtension correctly, it's used to set a type of $object var. Should I implement DynamicFunctionReturnTypeExtension also or what?
>
> So I finally learned the thing:
> 
> ```
> return $this->typeSpecifier->create(
> 	$node,
> 	new ConstantBooleanType(false),
> 	$context
> );
> ```

just posting the anwser here, since I also worked thru this recently:

the cited code is not correct. instead it works like this:
- the actual type needs to be set like in https://github.com/phpstan/phpstan-src/blob/9d9dcd84343bbb8d5f386de1fba44530a2e63110/src/Type/Php/IsAFunctionTypeSpecifyingExtension.php#L49-L55
- the returned type is then combined with the previous type in https://github.com/phpstan/phpstan-src/blob/9d9dcd84343bbb8d5f386de1fba44530a2e63110/src/Analyser/TypeSpecifier.php#L1019-L1025
- and the combination of the scope-type with the type-specified type is taken into account in https://github.com/phpstan/phpstan-src/blob/9d9dcd84343bbb8d5f386de1fba44530a2e63110/src/Type/Php/TypeSpecifyingFunctionsDynamicReturnTypeExtension.php#L72-L80

**Comment by ondrejmirtes** [comment]
Implemented a different way here: https://github.com/phpstan/phpstan-src/pull/1311

**Pull request closed without merging**
