### PR TITLE
setlocale() can take as argument 0 and NULL

### PR DESCRIPTION
**Pull request by peter-gribanov**
https://www.php.net/manual/en/function.setlocale.php

> If `locale` is **NULL** or the empty string "", the locale names will be set from the values of environment variables with the same names as the above categories, or from "LANG".
> If `locale` is "0", the locale setting is not affected, only the current setting is returned.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Is it supposed to be integer 0 or string "0"?

**Comment by peter-gribanov** [comment]
Is a integer, not a string.

**Comment by peter-gribanov** [comment]
No, though. Wait. It seems I'm wrong.

**Comment by peter-gribanov** [comment]
It is not obvious to me from the documentation which data type should be used. Integer is most commonly used. It's not obvious to me in the [source](https://github.com/php/php-src/blob/master/ext/standard/string.c#L4570) either. Both options [work the same way](https://3v4l.org/CeXk7).

**Comment by ondrejmirtes** [comment]
Yeah, these functions are weird, the documentation talks about `string` only though. I'd accept a PR that changes the type to `string|null`.

**Comment by peter-gribanov** [comment]
@ondrejmirtes please review

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
