### PR TITLE
Improve the return type of functions that return an indexed array of strings

### PR DESCRIPTION
**Pull request by johnbillion**
Just some low hanging fruit. These all return an indexed array of strings.

None of them have dynamic return type extensions.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Can it be changed to `list<string>` or those aren't lists?

Please note that lists aren't fully supported by PHPStan yet and they're currently aliased to `array<int, ...>` but it would be a better typehint for the future.

**Comment by johnbillion** [comment]
They're consecutively indexed lists, yes. I see there's only three existing uses of list in functionMap.php. I can switch these to `list<string>` if you prefer.

**Comment by ondrejmirtes** [comment]
Yes, thank you.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
