### PR TITLE
Fix `ReflectionClass::newInstanceArgs()` - error on argument type

### PR DESCRIPTION
**Pull request by s3b4stian**
Update ReflectionClass stub to solve phpstan/phpstan#8679.

Tests needed!

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Please test it in CallMethodsRuleTest.

**Comment by ondrejmirtes** [comment]
FYI you based the PR on 1.10.x. This means it's going to be released somewhat later than if you based it on 1.9.x. Feel free to rebase it on top of 1.9.x, thanks.

**Comment by s3b4stian** [comment]
If you wish, merge this PR on `1.10.x`, I will do a new PR, based on branch `1.9.x`.

**Comment by ondrejmirtes** [comment]
You don't need to do a new PR, you can just change the base on 1.9.x and rebase on top of 1.9.x. Everything in 1.9.x gets merged automatically into 1.10.x.

**Comment by s3b4stian** [comment]
Now should be ok, next time I will start checking out a new dev branch and not working directly on official one. Less problem to do a rebase. Thaks for the support!

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
