### PR TITLE
Smarter extract() with constant arrays

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
As discussed in https://github.com/phpstan/phpstan/issues/9331

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
```php
if (!$keyType instanceof ConstantStringType) {
  // integers as variable names not allowed
  continue;
}
```
This code raises `Doing instanceof PHPStan\Type\Constant\ConstantStringType is error-prone and deprecated. Use Type::getConstantStrings() instead.  `

But it is used this way in other places. Should I rewrite it somehow or ignore it using baseline?

**Comment by ondrejmirtes** [comment]
> But it is used this way in other places.

I don't see a single `instanceof ConstantStringType` in NodeScopeResolver. Please use what the tip tells you - either `Type::isString()` or `count($type->getConstantStrings()) === 0`. I'd prefer the first one.

**Comment by ondrejmirtes** [comment]
please rebase your pull request and change its target to 1.10.x.

**Comment by ondrejmirtes** [comment]
`git rebase --onto` is your friend ;) So `git rebase --onto origin/1.10.x HEAD^` is going to fix this for you. Alternatively, you can `git reset --hard origin/1.10.x` and then `git cherry-pick` that one commit of yours. The result is gonna be the same.

**Comment by ondrejmirtes** [comment]
Really nice, thank you!

**Comment by herndlm** [comment]
Thx, this most likely gets rid of a couple of baseline entries in one of our legacy apps 😊

**Pull request merged**
