### PR TITLE
declare more precise getClass* return types

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
I'd agree with extensions but not with ObjectType/TypeWithClassName. That's used to represent invalid class names too.

**Comment by ondrejmirtes** [comment]
Yeah, still a BC break, we have to wait for 2.0 if we find it valuable.

**Comment by staabm** [comment]
agree. thx for the review.

**Comment by staabm** [comment]
what do you think about adding these PRs to a separate milestone, so they won't be forgotten when we do the next major version?

**Comment by ondrejmirtes** [comment]
That's not necessary, I've got a private todolist with 50 items already, it's not gonna get lost.

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
