### PR TITLE
#6840 Report useless array filter

### PR DESCRIPTION
**Pull request by leongersen**
New branch based on [1.5.x](https://github.com/phpstan/phpstan-src/tree/1.5.x), I could not reopen #1076.

Implements phpstan/phpstan#6840.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I'm looking at this - it's really nice, Some observations that would make this even better:

1) Calling array_filter without callback on always-truthy values is similarly useless as on always-falsy values. Please detect that too.
2) We should also detect situations with `array_filter($array, null, ARRAY_FILTER_USE_KEY)` and `array_filter($array, null, ARRAY_FILTER_USE_BOTH)` - not sure how the latter one behaves, needs to be tested.

**Comment by leongersen** [comment]
> 1. Calling array_filter without callback on always-truthy values

That's what this PR checks for. Do you mean the opposite? Calling `array_filter` on _only_ falsy values will always result in `[]` and is likely an error, but not without effect.

2. Sounds good, I'll add support for that.

**Comment by ondrejmirtes** [comment]
Yes, that's what I meant, the rule should report both always-truthy and always-falsy arrays :)

**Comment by herndlm** [comment]
USE_BOTH without a callback only uses the first arg (= value) AFAIK, see also https://github.com/phpstan/phpstan-src/blob/1.4.10/tests/PHPStan/Analyser/data/array-filter.php#L36

But better double-check :) if the referenced test is wrong, I need to fix smth in the ArrayFilter extension

**Comment by leongersen** [comment]
I checked, passing `null` explicitly as the `callback` (with or without the `mode` parameter) results in the following warning:

```Warning: array_filter() expects parameter 2 to be a valid callback, no array or string given```

**Comment by herndlm** [comment]
Ah maybe that explains why the key mode test above my rererence also looks weird 😅 would be interesting if and how it filters

**Comment by leongersen** [comment]
It doesn't filter at all:
```
var_dump(@array_filter([0,1], null)); => NULL
```

I've added support for reporting arrays with _only_ falsey values.

**Comment by leongersen** [comment]
~~The failing test is unrelated.~~

**Comment by ondrejmirtes** [comment]
The failure is definitely related as the file contains this: `array_filter([]);`

Feel free to modify the file to contains something that's valid, like `[0, 1, 2]` :)

**Comment by leongersen** [comment]
Turns out `file-without-errors` is not without errors 🙈

**Comment by ondrejmirtes** [comment]
I pushed some extra commits to adjust this to my taste.

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by ondrejmirtes** [comment]
Also to keep the BC promise (https://phpstan.org/user-guide/backward-compatibility-promise) I had to do this: https://github.com/phpstan/phpstan-src/pull/1077/commits/7627b52b977480e71254a84f08b01e6251076619

> The library of performed rules on analysed code, and the meaning of [rule levels](https://phpstan.org/user-guide/rule-levels) does not change in minor/patch versions. This means that PHPStan will not look for new categories of errors in a minor/patch version. New rules are added only in major versions, and also as part of [bleeding edge](https://phpstan.org/blog/what-is-bleeding-edge) which is an opt-in preview of the next major version.

**Comment by herndlm** [comment]
@leongersen fyi I think null callables would work fine, they only work since PHP 8 and weirdly only ever filter by value (= ignore any given mode)

See https://3v4l.org/Cj17A

**Pull request merged**
