### PR TITLE
Fix is_subclass_of with same class

### PR DESCRIPTION
**Pull request by herndlm**
Closes https://github.com/phpstan/phpstan/issues/6305

### CODE REVIEW

**Comment by herndlm** [comment]
weird, `make` is working fine on my local env. need to check later

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by mvorisek** [comment]
Thank you!

**Comment by mvorisek** [comment]
@staabm please see https://github.com/phpstan/phpstan/issues/6305#issuecomment-1057164556

**Pull request merged**
