### PR TITLE
Fix duplicate paths in composerAutoloaderProjectPaths

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/11706

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I'd rather not call realpath, too much logic, can fail. You can normalize the paths with DIRECTORY_SEPARATOR.

**Comment by ondrejmirtes** [comment]
Thank you. This should lead to performance improvements as well.

**Comment by staabm** [comment]
I measured the before/after stats of this patch. 

I can see a ~5-7% faster end-to-end analysis time after the patch with a primed cache.
with a empty cache I can see a 3-4% improvement.

**Comment by staabm** [comment]
@ondrejmirtes looking at the result cache, I can see `\PHPStan\Analyser\Error` beeing serialized with a few duplicated properties:

```
    \PHPStan\Analyser\Error::__set_state(array(
       'message' => 'Call to method isValidPost() of deprecated class CsrfToken:
use DI injected CsrfTokenAbstract instead',
       'file' => 'C:\\dvl\\Workspace\\kunzmann\\app\\portal\\controllers\\ServiceController.php',
       'line' => 145,
       'canBeIgnored' => true,
       'filePath' => 'C:\\dvl\\Workspace\\kunzmann\\app\\portal\\controllers\\ServiceController.php',
       'traitFilePath' => NULL,
       'tip' => NULL,
       'nodeLine' => 145,
       'nodeType' => 'PhpParser\\Node\\Expr\\StaticCall',
       'identifier' => 'staticMethod.deprecatedClass',
       'metadata' => 
      array (
      ),
```

would you accept a patch, which e.g. would prevent serializing `'file'` and `'filePath` in case they contain 1:1 the identical string?
(to reduce the amount of data in the result cache file)

**Comment by staabm** [comment]
Found out that in our projects one big "offender" of result-cache bloat was `rectory/type-perfect` which gets fixed with https://github.com/rectorphp/type-perfect/pull/44

**Comment by ondrejmirtes** [comment]
> would you accept a patch

No, not worth it.

**Pull request merged**
