### PR TITLE
Fix null coalesce assignment type

### PR DESCRIPTION
**Pull request by hirokinoue**
Fix: https://github.com/phpstan/phpstan/issues/9995

### CODE REVIEW

**Comment by hirokinoue** [comment]
Hi, I'm new to phptan-src. I created a pull request referred to several merged pull requests. Any advice is welcome. Thank you in advance.

**Comment by ondrejmirtes** [comment]
Perfect, thank you very much!

**Comment by ondrejmirtes** [comment]
I encourage you to look into more "easy fixes" issues (https://github.com/phpstan/phpstan/milestone/8) :) They might not be exactly "easy" to figure out, I mark issues as "easy fixes" where I'm sure it's actually fixable in the current feature set of PHPStan and doesn't require any fundamental changes or refactorings :)

The rule of thumb is - if the fix takes less than 50 lines of code, you're good to go, if it takes more and is tricker than that, I probably misqualified the issue and shouldn't be marked as easy to fix :)

**Comment by hirokinoue** [comment]
Thank you so much for your review and advice :)

**Pull request merged**
