### PR TITLE
Disable ini files when restarted by XdebugHandler

### PR DESCRIPTION
**Pull request by fsmoak**
Disable use of (additional) ini files for workers when restarted by XdebugHandler

This relates to: https://github.com/phpstan/phpstan/issues/5809

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
@johnstevenson So instead of this PR, the only thing we need to add is `$xdebug->setPersistent();`? Thank you.

**Comment by johnstevenson** [comment]
@ondrejmirtes Yes, correct

**Comment by ondrejmirtes** [comment]
Alright, just did that: https://github.com/phpstan/phpstan-src/commit/222e1c3e22a6bd034c7542f44b2f7a870ccbe8e0

Can you please verify it works as expected? Thanks.

**Comment by johnstevenson** [comment]
Okay, you can probably get rid of the extra code that was added in ProcessHelper.php. I'll reproduce the various scenarios and check them just to confirm.

**Comment by ondrejmirtes** [comment]
What extra code?

**Comment by ondrejmirtes** [comment]
Also please wait a bit; the new commit hasn't yet built to phpstan/phpstan. The CI pipeline is full today.

**Comment by johnstevenson** [comment]
The extra code introduced in https://github.com/phpstan/phpstan-src/pull/559

>Also please wait a bit; the new commit hasn't yet built to phpstan/phpstan. 

I tend to specifically replicate these scenarious in my own testcase classes first. One day I'll put them on Github, when I've worked out a simple way to automate them!

**Comment by ondrejmirtes** [comment]
It's now in phpstan/phpstan dev-master, so you can test it :)

**Comment by johnstevenson** [comment]
@ondrejmirtes Great, this works nicely and keeps Xdebug out of all subprocesses.

>you can probably get rid of the extra code that was added in ProcessHelper.php

I was wrong about this. Explicitly setting the loaded ini on the comand-line has no downsides when XdebugHandler has restarted the process, because everything is in a single ini file (which is made available to PHP through through `PHPRC` environment variable). However for the sake of clarity it should probably be amended to something like:

```php

    $phpCmd = escapeshellarg(PHP_BINARY);

    if (XdebugHandler::getRestartSettings() === null && php_ini_loaded_file() !== false) {
        // Explicitly set ini file in case it was passed in on the command line
        $phpCmd .= ' -c ' .escapeshellarg(php_ini_loaded_file());             
    }
    
    $processCommandArray = [
      $phpCmd,
    ];
```

**Pull request closed without merging**
