### PR TITLE
Support List<Foo> rebased

### PR DESCRIPTION
**Pull request by orklah**
This is a new edition of #79 because the first one was messy.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Merged as https://github.com/phpstan/phpstan-src/commit/a2c04036578f9a7d03c28a7e0414749c96724ec2, thank you!

**Comment by szepeviktor** [comment]
@orklah What is the list type? is it `array<int, mixed>`?

**Comment by szepeviktor** [comment]
I see :) https://github.com/phpstan/phpstan-src/pull/79#issue-358983293

**Comment by orklah** [comment]
> @orklah What is the list type? is it `array<int, mixed>`?

Yes, for now, it is just aliases. However, there is a much bigger meaning behind it that wasn't implemented for now. It is best described in Psalm documentation:
https://psalm.dev/docs/annotating_code/type_syntax/array_types/#lists

> Psalm supports a list type that represents continuous, integer-indexed arrays like ["red", "yellow", "blue"] .
> These arrays have the property $arr === array_values($arr), and represent a large percentage of all array usage in PHP applications.

It is a subset of array<int, mixed> where the indexes have no gap and start at 0.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
