### PR TITLE
Add the possible `false` return value to DateTime(Immutable) modifiers

### PR DESCRIPTION
**Pull request by themasch**
According to the docs all these methods may return `false` in case of failure (e.g. invalid input).

This hopefully fixes https://github.com/phpstan/phpstan/issues/3347

I can see how this creates a lot "false positives" with known-good constant values, but the current situation creates false negatives when actually checking for false.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
This change was rejected before: https://github.com/phpstan/phpstan/pull/2329

> I can see how this creates a lot "false positives" with known-good constant values,

This is exactly why I can't accept this. This needs a dynamic return type extension so that known values do not cause `false` to be returned.

**Comment by themasch** [comment]
Oh, I did not see that, should have checked more thoroughly. Sorry for that!

**Comment by ondrejmirtes** [comment]
Feel free to use inline `@var` in places where it bothers you 😊

**Comment by themasch** [comment]
Yeah, thats the fix I'm currently using 👍

**Pull request closed without merging**
