### PR TITLE
Fix RecursiveIteratorIterator template type

### PR DESCRIPTION
**Pull request by simPod**
image

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Unions aren’t supported yet. What real issues does the current stub cause?

**Comment by simPod** [comment]
Ah. It did not catch passing Traversable into RecursiveIteratorIterator.

https://phpstan.org/r/5e98305e-2a97-45bc-8447-3142a2e801fd

**Comment by ondrejmirtes** [comment]
Can you open an issue (feature request) and show on 3v4l.org that it fails in PHP? Thanks.

**Comment by simPod** [comment]
Not sure what FR should I want 🤔 

PHP failing example https://3v4l.org/evDe2

**Comment by ondrejmirtes** [comment]
Just a normal "expected/actual output" kind of feature request.

**Pull request closed without merging**
