### PR TITLE
TypeSpecifier: Narrow `(string) $expr` like `$expr != ''`

### PR DESCRIPTION
**Pull request by staabm**
refs https://github.com/phpstan/phpstan-src/pull/3380#discussion_r1740085169

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I think you can narrow all of them as `!= false`.

Because here you missed `'0'` which is falsy.

**Comment by staabm** [comment]
> I think you can narrow all of them as `!= false`.

great suggestion. since we have already a better loose comparison of constant bools, this also leads to more precise results already :)

**Comment by staabm** [comment]
(I will de-duplicate the existing logic on the next PR, when currently open ones are merged)

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
