### PR TITLE
Enforce optional parameters in callable types

### PR DESCRIPTION
**Pull request by rvanvelzen**
Fixes phpstan/phpstan#7320

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
The test assertions from the failures probably need updating, otherwise 👍 :)

**Comment by ondrejmirtes** [comment]
The test assertions from the failures probably need updating, otherwise 👍 :)

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by ondrejmirtes** [comment]
It's so annoying but I have to revert this. In a test project I'm running each new PHPStan commit on, this change caused 81 new errors. And it's because of these annotations in doctrine/collections (the same mistake is repeated above multiple methods):

```
    /**
     * Tests for the existence of an element that satisfies the given predicate.
     *
     * @param Closure $p The predicate.
     * @psalm-param Closure(TKey=, T=):bool $p
     *
     * @return bool TRUE if the predicate is TRUE for at least one element, FALSE otherwise.
     */
    public function exists(Closure $p);
```

This means that passing `Closure(int|string, TValue): bool` into this method is not valid. Although in reality the code always calls the closure with two arguments...

**Comment by ondrejmirtes** [comment]
So some research needs to be done:

1) Does `Closure(TKey=, T=):bool` mean the same thing in Psalm and PHPStan?
2) Should the Doctrine Collections annotations be fixed?

**Comment by ondrejmirtes** [comment]
Also there's number of issues phpstan-bot commented on because playground samples changed. All of this tells me impact on the ecosystem would be too huge even if we're right. Might be better to save a fix like this for a major version.

**Comment by rvanvelzen** [comment]
I think most of the issues the bot found were due to the `describe()` change.

I'll research this for a bit soon.

**Comment by rvanvelzen** [comment]
Psalm [does not](https://psalm.dev/r/771de51ba9) consider this to be an issue, but I think it's pretty clear that it is. I believe the annotations in Doctrine Collections are wrong.

Specifically: `callable(T=)` can be called with either 0 or 1 parameter, but passing in `callable(T)` will require 1 parameter. This is what this PR would fix.

However, I agree that this change could be overly disruptive. An option might be to put it in `bleedingEdge`?

**Comment by ondrejmirtes** [comment]
Can you please open a Psalm issue to see what the maintainers think about this? Thanks :)

Bleeding edge - I considered it, but this is deep in the typesystem so there would have to be some kind of global static singleton toggle to query... (There was once in the past for similar purpose).

**Comment by greg0ire** [comment]
FYI `doctrine/collections` 1.7.2 no longer has this issue.

**Comment by stof** [comment]
FYI, I opened the psalm issue at https://github.com/vimeo/psalm/issues/8438

**Comment by ondrejmirtes** [comment]
Readded this again: https://github.com/phpstan/phpstan-src/commit/45404d9d4e6c631418959d20a11df463b0e20ad7

**Pull request merged**
