### PR TITLE
fix: mark `Ds\Queue::pop()` as impure

### PR DESCRIPTION
**Pull request by simPod**
Resolves [#9682](https://github.com/phpstan/phpstan/issues/9682)

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Can you please check other similar methods that might have the same problem? The key is that the method returns a value AND changes the underlying collection.

Such an example: `Stack::pop()`

If it does not return a value (it's `void`) then such a method is already understood as impure by PHPStan.

**Comment by simPod** [comment]
I tried to mark all eligible I know of.

**Comment by ondrejmirtes** [comment]
I don't think that first/last and peek are impure.

**Comment by simPod** [comment]
ok i missed "changes" in `The key is that the method returns a value AND changes the underlying collection.`

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
