### PR TITLE
fix `sscanf()` inference with regex format patterns

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/7563
closes https://github.com/phpstan/phpstan/issues/7764

### CODE REVIEW

**Comment by rvanvelzen** [comment]
This fails for `'%[%[]'` which should have size 1.

**Comment by staabm** [comment]
> This fails for `'%[%[]'` which should have size 1.

good catch, fixed

**Comment by staabm** [comment]
rebased

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
