### PR TITLE
Added regression test

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/6776
closes https://github.com/phpstan/phpstan/issues/7075

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
There's also 7075 please.

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Please make sure you're seeing these tests fail first. My guess is that the second one is missing `$this->treatPhpDocTypesAsCertain = false;`.

**Comment by staabm** [comment]
I tested it on 1.9.x and it failed there. wasn't the best idea for this particular test though it seems ;)

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
