### PR TITLE
Implement locateIdentifiersByType for OptimizedSingleFileSourceLocator

### PR DESCRIPTION
**Pull request by tomasfejfar**
Followup to #1080

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Why not constants too? 😊

**Comment by tomasfejfar** [comment]
@ondrejmirtes I kind of extrapolated from https://github.com/phpstan/phpstan-src/pull/1080#issuecomment-1072411687. It felt weird that if I'm looking in directory constants are not located, but when I look at single file, they are.

**Comment by ondrejmirtes** [comment]
I just want `locateIdentifier()` and `locateIdentifiersByType()` to be consistent in each locator.

**Review by ondrejmirtes — APPROVED** [review]

**Comment by ondrejmirtes** [comment]
I took it over the finish line, thanks.

**Pull request merged**
