### PR TITLE
Add non regression test for issue 7607

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/phpstan/phpstan/issues/7607

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by VincentLanglet** [comment]
You're welcome.

It didn't closed the issue https://github.com/phpstan/phpstan/issues/7607, so you'll have to do it manually @ondrejmirtes.

**Comment by herndlm** [comment]
He might be able to close it next time he's in the ski lift again 😅

**Comment by ondrejmirtes** [comment]
They're not closed unless the PR is on the default branch...

**Pull request merged**
