### PR TITLE
Support for phpstan and psaml prefixes on @method

### PR DESCRIPTION
**Pull request by yosatak**
About one month after #279, there was a conflict, so I repaired it.
@bastien-phi and @ondrejmirtes. I will take over the correspondence of this PR.

### CODE REVIEW

**Comment by bastien-phi** [comment]
@yosatak Sorry about that... I just completely forgot that PR. My bad !

I fixed the conflict in #279

**Comment by yosatak** [comment]
Thanks for the fix!

Let's continue the discussion with #279

**Comment by ondrejmirtes** [comment]
There was still conflict in #279 so I'd much prefer this one. I'll do the review.

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Hi, the `@phpstan-method` tag also needs to be added to InvalidPHPStanDocTagRule. Otherwise I like it 👍

**Comment by ondrejmirtes** [comment]
Please solve the conflict by rebasing, I don't want "Merge branch 'master' into..." commit.

**Comment by yosatak** [comment]
Thank you for the review!
Fixed InvalidPHPStanDocTagRule and rebase on master.

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by bastien-phi** [comment]
@ondrejmirtes You are completely right, this one is much better than #279 !

@yosatak You did a great job !

Thank you both for that !

**Pull request merged**
