### PR TITLE
Update string compare return values

### PR DESCRIPTION
**Pull request by bytestream**
See https://github.com/phpstan/phpstan-src/pull/1407#issuecomment-1151976963

### CODE REVIEW

**Comment by staabm** [comment]
same for 

https://github.com/phpstan/phpstan-src/blob/d1e0b1bf15516a020c1aff77f9778a1ddf32ac79/resources/functionMap.php#L11780-L11783 

?

maybe also `substr_compare`


additionally a test-case regarding your reported error would be great.

**Comment by bytestream** [comment]
@ondrejmirtes is something else necessary here? The test fails despite the function map being updated?

**Comment by bytestream** [comment]
@ondrejmirtes this is :green_circle: now :tada:

**Comment by ondrejmirtes** [comment]
No merge commits please, but clean linear history on top of 1.7.x.

**Comment by bytestream** [comment]
I've rebased and squashed :+1:

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
