### PR TITLE
Add non regression tests for phpstan/phpstan#6576 + phpstan/phpstan#6842

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/phpstan/phpstan/issues/6576
Closes https://github.com/phpstan/phpstan/issues/6842

### CODE REVIEW

**Comment by staabm** [comment]
Please reference the relevant issues in the PR description like 
"closes $link-to-issue" (each on a separate line)

**Comment by VincentLanglet** [comment]
Closes https://github.com/phpstan/phpstan/issues/6576
Closes https://github.com/phpstan/phpstan/issues/6842

But they are already closed

**Comment by staabm** [comment]
Even if they are already closed - adding the link - will show up a reference at the issue.

So it eases getting things together later on.

**Comment by ondrejmirtes** [comment]
Awesome, thank you.

**Comment by VincentLanglet** [comment]
> Awesome, thank you.

I can do more if you need to :)

**Comment by ondrejmirtes** [comment]
I'll keep that in mind when it happens next time - when some bugs are fixed as a side effect of another fix and @phpstan-bot discovers that 😊

**Pull request merged**
