### PR TITLE
Option usePathConstantsAsConstantString

### PR DESCRIPTION
**Pull request by MartinMystikJonas**

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
The `new ConstantStringType($file)` part is repeated here. I'd like the code to change so that the last line call looks like this:

```php
return $this->usePathConstantsAsConstantString ? $stringType : $stringType->generalize(GeneralizePrecision::moreSpecific());
```

**Review by ondrejmirtes — APPROVED** [review]

**Comment by ondrejmirtes** [comment]
Please remind me - why would need this again? It's causing problems with https://github.com/phpstan/phpstan/issues/12203.

**Comment by thg2k** [comment]
@ondrejmirtes I think there is something explained here: https://github.com/phpstan/phpstan/discussions/8454#discussioncomment-4297664

**Comment by MartinMystikJonas** [comment]
It was needed when we evaluated paths to latte tempaltes with expressions containing __DIR__. Type was resolved as generic string not COnstantString with evaluated value. So I implemented this to be able to turn on treating results of expressions with __DIR__ as constantString so it can be evaluated later. It seems like problem described in https://github.com/phpstan/phpstan/issues/12203 is basically same thing we encountered. So this is not causing that problem but is solution to similar problem.

**Comment by ondrejmirtes** [comment]
I'd say this option shouldn't be needed. We should always strive for the type to be as precise as possible, and only degrade it (generalize it) in contexts where the precise type is counter-productive.

**Comment by MartinMystikJonas** [comment]
Agreed.

**Pull request merged**
