### PR TITLE
is_a(): support class-string in parameter $class

### PR DESCRIPTION
**Pull request by jiripudil**
Follow-up to #392, should fix phpstan/phpstan#2799

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Would be cool to also have this tested in `testFileAsserts` as #392 was :)

**Comment by jiripudil** [comment]
@ondrejmirtes like this? :)

**Comment by ondrejmirtes** [comment]
Yes :) Thank you!

**Comment by jiripudil** [comment]
Glad to help :)

**Pull request merged**
