### PR TITLE
RuleLevelHelper: Don't wipe out TemplateMixedType

### PR DESCRIPTION
**Pull request by dktapps**
this caused a variety of interesting bugs with generics in explicit-mixed mode.

This fixes phpstan/phpstan#3566.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
1) The build needs to pass.
2) There needs to be a test accompanying this change.

**Comment by dktapps** [comment]
Where should the tests go?

**Comment by ondrejmirtes** [comment]
In the rule where you're experiencing false negative or false positive.

**Comment by dktapps** [comment]
That would be many of them. This bug occurs in lots of places.

**Comment by ondrejmirtes** [comment]
Single example is sufficient.

**Comment by dktapps** [comment]
This change breaks some cases of generic mixed being passed to non-mixed in explicitMixed mode. I'm not sure how to address these other than adding a StrictTemplateMixedType. Any suggestions?

**Comment by ondrejmirtes** [comment]
I still don't know what scenario are you trying to fix, so I can't decide what's actually desired here.

If you can't provide a test, then please open an issue with a reproducing example, thanks.

**Comment by dktapps** [comment]
I've added a test sample. On the master branch it fails with this error:
`94: Parameter #1 $t of method CheckExplicitMixedMethodCall\Baz<T>::acceptsT() expects T, T given.`

**Comment by dktapps** [comment]
I've opened another PR with failing tests so you can see firsthand on the CI.

**Comment by dktapps** [comment]
I think the real solution to this problem is likely to be to make TemplateMixedType not extend MixedType. In the tests that failed here, it's being treated as a non-strict mixed type, with all of the weird behaviour that entails.

**Comment by dktapps** [comment]
Hello, any feedback on this? I'm hesitant to make changes on the type system because I don't understand how half of it fits together. But it seems like something has to be done to differentiate TemplateMixedType from a regular implicit `mixed` type.

**Comment by ondrejmirtes** [comment]
I'm gonna fix this myself.

**Pull request closed without merging**
