### PR TITLE
phpstan-assert with count results in type loss

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/10264

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by ondrejmirtes** [comment]
This PR introduces a bug :( https://phpstan.org/r/cb084a8a-ee9d-435f-bc22-5987d9e46093

1) In else it should be `array{}`
2) Below if-else it should be `list<stdClass>`.

**Comment by staabm** [comment]
I will have a look

**Comment by staabm** [comment]
> This PR introduces a bug :( [phpstan.org/r/cb084a8a-ee9d-435f-bc22-5987d9e46093](https://phpstan.org/r/cb084a8a-ee9d-435f-bc22-5987d9e46093)

how did you find this regresssion so fast?

**Comment by ondrejmirtes** [comment]
@staabm I have a few proprietary projects that are tested continously after each commit with https://github.com/phpstan/phpstan/blob/1.11.x/.github/workflows/test-projects.yml so I inspect the failures afterwards.

**Pull request merged**
