### PR TITLE
Introduce memoizing reflectors

### PR DESCRIPTION
**Pull request by lookyman**
In my testing this improves time spent analysing PHPStan's own source code by about 45%.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by matks** [comment]
Hi, I'm looking at this code. When I read this I think it should be typed `Memorizing` instead of `Memoizing` . Am I right (then I can submit a PR) or did I miss something?

**Comment by ondrejmirtes** [comment]
@matks Nope: https://en.wikipedia.org/wiki/Memoization

**Comment by matks** [comment]
Aaaah 😄  I knew it was not that simple. Thanks !

**Pull request merged**
