### PR TITLE
DynamicFunctionReturnTypeExtension for the get_debug_type function.

### PR DESCRIPTION
**Pull request by patrickkusebauch**
Closes: https://github.com/phpstan/phpstan/issues/10558
Closes: https://github.com/phpstan/phpstan/issues/10585

### CODE REVIEW

**Comment by patrickkusebauch** [comment]
Looking at the failing checks, none of them seem to be genuinely caused by this change.

**Comment by staabm** [comment]
Please add a pattern-matching example-test and use it in rule-tests which emit errors before this PR and are expected to be fixed now

**Comment by patrickkusebauch** [comment]
> Please add a pattern-matching example-test and use it in rule-tests which emit errors before this PR and are expected to be fixed now

Updated the PR.

Error emitted before this PR: `'20: Match expression does not handle remaining value: string'`.

**Comment by patrickkusebauch** [comment]
Updated to also specify the type in condition branches. This closes https://github.com/phpstan/phpstan/issues/10585 for me.

I have a question about `TypeTraverser::map` and `TypeCombinator::union`. I tried to replicate the code in `GettypeFunctionReturnTypeExtension` as it is a similar feature. However, when trying to combine:
 - `'bool'|string` (constant string `bool` or any string) it gets normalized to `string`
 -  `'Namespace\ClassA'|'Namespace\ClassB'` (constant strings with FQCN) it gets normalized to `Namespace\ClassA|Namespace\ClassB`
 
 Is this expected? Can this be turned off? Are those considered equivalent?

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
