### PR TITLE
Remove clashing duplicated file

### PR DESCRIPTION
**Pull request by iluuu1994**
The file already exists here: https://github.com/phpstan/phpstan-src/blob/master/tests/PHPStan/Generics/data/bug2574.php

This will clash and emit a warning on case insensitive file systems.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
This was already tried before: https://github.com/phpstan/phpstan-src/pull/84/files

But it breaks the Windows build: https://travis-ci.org/phpstan/phpstan-src/jobs/641054293#L233

I think we have to remove the file including the test, and then add it again in another PR.

**Comment by iluuu1994** [comment]
You mean both files?

**Comment by ondrejmirtes** [comment]
Yeah, probably :)

**Comment by cs278** [comment]
Easiest fix is probably just to rename the remaining file to `bug-2574.php` which will then resolve the conflict.

**Comment by adaamz** [comment]
Or maybe do it in two commits?

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
