### PR TITLE
Fix return type of mysqli_result::fetch_array + fetch_assoc

### PR DESCRIPTION
**Pull request by paranoiq**
https://www.php.net/manual/en/mysqli-result.fetch-array.php 
https://www.php.net/manual/en/mysqli-result.fetch-assoc.php

### CODE REVIEW

**Comment by janedbal** [comment]
Just met this, should be easy to merge imo :)

**Comment by ondrejmirtes** [comment]
There's a conflict, can you please fix it?

Also: note that the type on PHP 8+ is already correct :) https://phpstan.org/r/7868d592-23fb-4a4b-8145-ebc89ca74bb4

**Comment by janedbal** [comment]
Looks like this was fixed in https://github.com/phpstan/phpstan-src/pull/3279

**Comment by ondrejmirtes** [comment]
Yeah :)

**Pull request closed without merging**
