### PR TITLE
Simulate issset for null coalesce operator

### PR DESCRIPTION
**Pull request by rajyan**
fixes https://github.com/phpstan/phpstan/issues/4885
fixes https://github.com/phpstan/phpstan/issues/5304
fixes https://github.com/phpstan/phpstan/issues/5337

### CODE REVIEW

**Comment by rajyan** [comment]
Several thing to consider and fix.
The test fails because the behaviour for coalesce and isset ternary is slightly different with undefined variables.
Although
```php
isset($a) ? $a : null;
isset($a->b) ? $a->b : null;

$a ?? null;
$a->b ?? null;
```
are all [valid](https://3v4l.org/IKJO6#v8.1.4) (no errors, but kind of buggy), currently PHPStan throws an error `Undefined variable: $a` for isset ternary while coalesce dosen't.

Also, it may be misleading, if `IssetRule` errors occur by coalesce.

**Comment by rajyan** [comment]
I should separate the PR for 6870

**Comment by rajyan** [comment]
memo https://github.com/phpstan/phpstan/issues/3283
https://github.com/phpstan/phpstan/issues/6026

**Comment by rajyan** [comment]
5 errors in tests
1. From https://github.com/phpstan/phpstan-src/commit/71c51e40e71985b152456b3b56d4c6593f0fe279
  * The logic of `lookForEnterVariableAssign` should be moved to `Isset_` (and also `Empty_`)
  * Maybe related? 
    * https://github.com/phpstan/phpstan/issues/6107
    * https://github.com/phpstan/phpstan/issues/3659
    * https://github.com/phpstan/phpstan/issues/6026 
    * https://github.com/phpstan/phpstan/issues/5971

2, 3, 5. Fixes https://github.com/phpstan/phpstan/issues/6809 and some others but conflicting with the current test case
4. Should be fixed in `Isset` 
  * created an issue https://github.com/phpstan/phpstan/issues/6899

**Comment by rajyan** [comment]
The failures in the tests looks good to me, but it's definitely a breaking change.
Two differences of `Coalesce` and `Isset_` now (before this PR)

1. PropertyFetch in isset is not considered as read
https://github.com/phpstan/phpstan-src/blob/f6c6c5e184615d2591a9321fe121005e055d57a1/tests/PHPStan/Rules/DeadCode/data/bug-5337.php#L17-L27
This reports `Property Bug5337\Foo::$field is unused` for isset, but something like `$this->field ?? false` would say `only read`.

By the way, there is a bug in coalesce too, reported in https://github.com/phpstan/phpstan/issues/5971#issuecomment-1024303463
which
```php
$this->field->prop ?? false
```
would not be recognized as read for property `$field`.

2. Dynamic property in isset is not reporting undefined property

As explained in https://github.com/phpstan/phpstan/issues/6809#issuecomment-1073711227 

This commit https://github.com/phpstan/phpstan-src/pull/1104/commits/cf0059e3b069e640d393ae9ac4da16e834e57ba4
would solve the first problem (leaving the bug https://github.com/phpstan/phpstan/issues/5971#issuecomment-1024303463), and report undefined property for dynamic property for the second one (which makes it more strict, but maybe too strict for some usecases?).

**Comment by rajyan** [comment]
I think first one should be fixed, but not sure about the second one.
As shown in
https://phpstan.org/r/56de90d5-b01b-42fd-ab31-912e2a3f6d79
dynamic property errors in level 0 anyway, so maybe in reporting in isset too is applicable.

**Comment by ondrejmirtes** [comment]
Please see my thinking about this: https://github.com/phpstan/phpstan/issues/6809#issuecomment-1073711227

I don't want BC breaks around this for analysis on PHP <= 8.1. We can do something more ambitious and strict for PHP 8.2 and objects that do not allow dynamic properties, but right now, there are too many test failures :)

**Comment by rajyan** [comment]
@ondrejmirtes 
Thank you for your comment. I'm working on now to solve the first problem (which is a bug I think), while leaving the dynamic property behavior as is. I'll mark this PR ready after the tests are passed!

**Comment by ondrejmirtes** [comment]
Superseded by https://github.com/phpstan/phpstan-src/pull/1192

**Pull request closed without merging**
