### PR TITLE
Fixing OPcache issues with autoloading with FileReadTrapStreamWrapper

### PR DESCRIPTION
**Pull request by dktapps**
These issues were caused by #491, because it made stream_read() return an empty string.
OPcache then cached this empty string, leading to failures to load files from phars or file:// locations.

This PR changes FileReadTrapStreamWrapper to allow autoloading to proceed as normal, and only intervenes to grab the first loaded filename. For everything else, it passes back to the regular functions.

### CODE REVIEW

**Comment by dktapps** [comment]
This one fails because it used the cache from the previous broken build https://github.com/phpstan/phpstan-src/runs/4317359673?check_suite_focus=true

seems like an issue with the CI ...

Will fix the other issues shortly.

**Comment by dktapps** [comment]
I see this causes a bunch of issues with static reflection. Not sure what the best way to solve those is, short of creating two implementations (obviously not ideal).

**Comment by dktapps** [comment]
I attempted to use opcache_reset() and opcache_invalidate() to get this issue to gtfo, but opcache just won't cooperate. reset has no effect, and invalidate() returns false because it doesn't understand realpath() on phar://. This is a really infuriating issue.

**Comment by dktapps** [comment]
I think the only bulletproof solution to this problem is to do `ini_set("opcache.enable", "off")` somewhere. Since static reflection may anyway be used when dynamic reflection is enabled, there's no reliable way to know whether the actual code should be loaded or not, and if it's not loaded, this problem will occur because OPcache will grab the fake data.

Sadly, even just turning off OPcache temporarily can't be done, as `opcache.enable` can only be disabled at runtime. Once it's disabled, it can't be reenabled.

**Comment by mvorisek** [comment]
disabling opcache causes increased memory usage and lower performance

**Comment by dktapps** [comment]
Yeah, I'm aware. It also means PHPStan can't benefit from JIT. But until this bug is resolved, it's the only option I have available.

Trouble is, I don't see any way to fix this problem. If `opcache_invalidate()` worked, we might be OK, but [even Nikita was nervous to fix it due to unknowns](https://github.com/php/php-src/pull/4432). Until static reflection is forced for everyone, this will continue to be a problem.

**Comment by mvorisek** [comment]
The php-src issue seems fixable, let's try to fix it there first, wait for bugfix releases and disable opcache for the older/unmaitaned php versions.

**Comment by dktapps** [comment]
I doubt it will get fixed upstream. This issue has been known since >2y and no activity on it due to low demand. I've made some suggestions and hopefully it gets fixed, but I'm not hopeful.

**Comment by dktapps** [comment]
It looks like `opcache_invalidate()` does not do anything in the current request context (the script will not be recompiled, even when opcache_invalidate() succeeds). It only forces a recompile in _subsequent_ requests.

It looks like the only ways to fix this problem are:

1) Patch php-src to make opcache not cache scripts which are empty (weird special case, doubtful it would be accepted upstream).
2) Disable opcache during PHPStan execution.

**Comment by dktapps** [comment]
I should also point out that this can happen _without_ OPcache when `require_once` is used. @ondrejmirtes this is a really broken hack :/

**Comment by staabm** [comment]
Not sure its related: there is another open PR to this file in https://github.com/phpstan/phpstan-src/pull/722

maybe thats something which works on the same problem your are trying to fix.
I didn‘t know, just remembered the other PR and figured maybe its helpful for you

**Comment by dktapps** [comment]
No, that PR isn't related to this bug.

**Comment by ondrejmirtes** [comment]
Thank you for this effort. Would you be able to report a bug to php-src? Or it isn't PHP's fault at all? Looks to me like `opcache_invalidate` ought to always work.

**Comment by ondrejmirtes** [comment]
Just dealt with this in the obvious way - let it actually autoload the file! https://github.com/phpstan/phpstan-src/commit/e30f4467ab8fa2421f7da6c3909061ab4d5ba743

PHPStan should now work even with OPCache enabled, please test dev-master.

**Comment by dktapps** [comment]
Great, thanks.

I suppose that fix should be fine in most cases since autoloaded classes usually won't directly execute code anyway.

**Comment by ondrejmirtes** [comment]
One catch though - I had to revert to the old way of doing things when `disableRuntimeReflectionProvider=true`: https://github.com/phpstan/phpstan-src/commit/c2d2c2f638689b370752f9f197d1fdfeeef5926d

**Comment by dktapps** [comment]
In that case it should be fine anyway, since all classes are reflected statically. The issue only occurred when mixing static and dynamic reflection.

**Comment by ondrejmirtes** [comment]
Maybe it's this obvious: https://github.com/phpstan/phpstan-src/commit/ae53760a875a118131df949a7547fb9f1a55e904

**Comment by dktapps** [comment]
I tried that already, it doesn't work for this case.

**Comment by ondrejmirtes** [comment]
It helped to solve my issues. If you comment it out in this PR, some tests fail (with OPCache enabled): https://github.com/phpstan/phpstan-src/pull/1265

**Comment by dktapps** [comment]
The problems I had arose when using phars, since opcache_invalidate() doesn't like phar:// paths.

**Pull request closed without merging**
