### PR TITLE
Remove 3 leading spaces in PHAR

### PR DESCRIPTION
**Pull request by ruudk**
Fixes https://github.com/phpstan/phpstan/issues/8952

I think the problem comes from the nowdoc related to Box/Rector.

### CODE REVIEW

**Comment by ruudk** [comment]
> As a CI artifact in a PR here you get the compiled PHAR so you could easily debug the end result this way.

@ondrejmirtes I must be blind but I don't see the artifact.

**Comment by staabm** [comment]
in the "compile phar" action

grafik

 at the bottom

https://github.com/phpstan/phpstan-src/actions/runs/4260429654

grafik

sorry for the huge screenshots 😅

**Comment by ruudk** [comment]
@staabm Thanks!

**Comment by ruudk** [comment]
Oke, the generated PHAR now looks like this:
```php
            ksort($fileErrorsCounts, SORT_STRING);
            foreach ($fileErrorsCounts as $message => $count) {
                $php .= '$ignoreErrors[] = [';
                $php .= "\n";
                $php .= "\t'message' => " . var_export(Helpers::escape('#^' . preg_quote($message, '#') . '$#'), \true) . ',';
                $php .= "\n";
                $php .= "\t'count' => " . $count . ',';
                $php .= "\n";
                $php .= "\t'path' => __DIR__ . " . var_export(Helpers::escape($file), \true) . ',';
                $php .= "\n";
                $php .= '];';
                $php .= "\n";
            }
```

I think this looks good.

I also noticed that the generated baseline did not have a line ending, so I added that.
Screenshot 2023-02-24 at 09 40 40@2x

This is ready.

**Comment by ondrejmirtes** [comment]
CS failed: https://github.com/phpstan/phpstan-src/actions/runs/4260736633/jobs/7414242127

**Comment by mvorisek** [comment]
When PHP-CS-Fixer is present in the project, what about invoking it and keeping the phpstan PHP file CS always fixed?

**Comment by ruudk** [comment]
Feels like a waste of resources especially on large baselines with 15k lines. PHP CS Fixer is not the fastest.... 

I will fix the CS in this PR so that we can merge the actual fix.

**Comment by ruudk** [comment]
@ondrejmirtes CS is fixed. And I verified that the new PHAR generates the baseline correctly.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
