### PR TITLE
Add `class_implements` return type extension

### PR DESCRIPTION
**Pull request by herndlm**
Refs: https://github.com/phpstan/phpstan/discussions/8059
Closes https://github.com/phpstan/phpstan/issues/4335

See also https://3v4l.org/IufYX

If this is OK, I can do the same for the other related functions either here or in dedicated PRs.

### CODE REVIEW

**Comment by herndlm** [comment]
The one nextras failure should be fine. They do a `class_exists` before which makes the string a `class-string` and therefore `false` will never be returned: https://github.com/nextras/orm/blob/v4.0.6/src/Entity/Reflection/MetadataParser.php#L421

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
I don't think this is worth it. You can say these things for sure only for final classes, otherwise the array isn't really complete - a subclass can implement more interfaces.

**Comment by herndlm** [comment]
> I don't think this is worth it. You can say these things for sure only for final classes, otherwise the array isn't really complete - a subclass can implement more interfaces.

It should work fine with subclasses as well, why wouldn't it? Or do you mean something different?

**Comment by herndlm** [comment]
aaah I think I got you now, makes sense

I'll have to find another fix for the webmozart assert problem then :)

**Comment by VincentLanglet** [comment]
A return type extension is still useful for https://github.com/phpstan/phpstan/issues/4335 @herndlm 
Instead of looking for the exact values returned by `class_implements` just knowing if the return value is `class-string[]` or `class-string[]|false` would be great.

Do you want to reopen the PR or should I work on it ? :)

**Comment by herndlm** [comment]
You can go ahead, I fixed my problem that I was having in a different way :)

**Comment by VincentLanglet** [comment]
> You can go ahead, I fixed my problem that I was having in a different way :)

I started https://github.com/phpstan/phpstan-src/pull/2023 then if you have time to take a look.
You recently introduce a lot of new method in the Type interface, and I may miss something but didn't find the one I needed and had to use `instanceof`.

**Pull request closed without merging**
