### PR TITLE
proc_get_status can also return false

### PR DESCRIPTION
**Pull request by Slamdunk**
References:

1. https://www.php.net/manual/en/function.proc-get-status.php#refsect1-function.proc-get-status-returnvalues
1. https://github.com/php/php-src/blob/php-7.4.8/ext/standard/proc_open.c#L311

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Could we improve the return type with array shapes based on the "return values" in the docs?

* https://www.php.net/manual/en/function.proc-get-status.php
* https://phpstan.org/writing-php-code/phpdoc-types#array-shapes

**Comment by Slamdunk** [comment]
Oh, didn't know `functionMap.php` supported them, sure! Just need some time though

**Comment by Slamdunk** [comment]
Done

**Comment by ondrejmirtes** [comment]
Awesome!

**Pull request merged**
