### PR TITLE
Fix YieldTypeRuleTest docblock

### PR DESCRIPTION
**Pull request by rvanvelzen**
BC break from phpstan/phpdoc-parser#146

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
This potential for parser-related BC breaks is gonna break me one day...

**Comment by rvanvelzen** [comment]
At some point _any_ fix could technically be a BC break…

Relevant XKCD

**Comment by ondrejmirtes** [comment]
Yeah, in case of PHPStan, I really feel that - what's one person's bugfix is another person's failed build...

**Comment by ondrejmirtes** [comment]
Thank you :)

**Pull request merged**
