### PR TITLE
Display parent class name for anonymous classes like native php does

### PR DESCRIPTION
**Pull request by mvorisek**
closes https://github.com/phpstan/phpstan/issues/8740

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
This logic is likely insufficient. See https://github.com/phpstan/phpstan-src/pull/3374/files

**Comment by mvorisek** [comment]
PR adjusted.

**Comment by mvorisek** [comment]
@ondrejmirtes rebased into 2.0.x

**Comment by ondrejmirtes** [comment]
Merging into 2.0.x because of impact on error messages. Thank you!

**Comment by mvorisek** [comment]
Sure and thank you!

**Pull request merged**
