### PR TITLE
Added failling test for bug 9391

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/9391

### CODE REVIEW

**Comment by staabm** [comment]
let me have a look whether we have the same problem for `__serialize` and `__sleep`

**Comment by ondrejmirtes** [comment]
I don't think so, union isn't possible in the first place.

**Comment by staabm** [comment]
> I don't think so, union isn't possible in the first place.

you are right. I added a test which shows that we don't need a fix

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
