### PR TITLE
more precise `preg_match_all` return type on php8

### PR DESCRIPTION
**Pull request by staabm**
fixes issue reported in https://github.com/phpstan/phpstan-src/pull/918#issuecomment-1042983239

### CODE REVIEW

**Comment by Seldaek** [comment]
👍Thanks

**Comment by ondrejmirtes** [comment]
Coding standard failing here. Run `make cs` locally to check it.

**Comment by staabm** [comment]
args, the error slipped in while rebasing.. sorry for that.. fixed

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
