### PR TITLE
fix: mb_str_split

### PR DESCRIPTION
**Pull request by voku**
https://github.com/php/php-src/blob/2e97ae91c8ac404be00050eef414b555aba45a1c/ext/mbstring/mbstring.c#L1882

---
This change is [Reviewable](https://reviewable.io/reviews/phpstan/phpstan-src/123)

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Optional doesn't mean nullable: https://3v4l.org/I4OlG

**Comment by ondrejmirtes** [comment]
Even the second argument cannot be null: https://3v4l.org/3NfeC

**Comment by ondrejmirtes** [comment]
I don't understand what it's supposed to fix now?

**Comment by voku** [comment]
Good question :D I thought we must define the optional parameters. :-/

**Pull request closed without merging**
