### PR TITLE
Use positive integers for various time functions

### PR DESCRIPTION
**Pull request by staabm**
inspired by https://github.com/vimeo/psalm/pull/6861

the psalm PR also changes some singatures in a CallMap_historical.php file.. do we have an equivalent in phpstan?

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, I'm not a big fan of changing parameter types like this right now in a minor version, it's bound to break someone's build and in fact it's not going to find any real bugs.

> the psalm PR also changes some singatures in a CallMap_historical.php file

I don't know what's the purpose of CallMap_historical.php.

**Comment by ondrejmirtes** [comment]
So to be more specific - I'd like to change return types only, that's useful.

**Comment by staabm** [comment]
> So to be more specific - I'd like to change return types only, that's useful.

I see. thanks for the insights. fixed per feedback

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
