### PR TITLE
Make SimpleXMLElement stub more specific

### PR DESCRIPTION
**Pull request by devbanana**
Makes the types returned by SimpleXMLElement more specific. See the discussion here: https://github.com/phpstan/phpstan/discussions/5586

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Alright, let's try this :) I'll revert it if some complications come up.

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by VincentLanglet** [comment]
This code is working fine on my project 
https://phpstan.org/r/21751445-6289-4c07-8418-64ca4e71067e

But phpstan is now complaining since the last release.

**Comment by ondrejmirtes** [comment]
@VincentLanglet Please open an issue, discussion below a merged PR isn't the right place.

**Pull request merged**
