### PR TITLE
small signature updates

### PR DESCRIPTION
**Pull request by staabm**
see 
- https://3v4l.org/DA9eM
- https://www.php.net/round
- https://github.com/vimeo/psalm/commit/309d1a4634b6cdfec226bbd49fdd942c5522789f

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by dktapps** [comment]
It would be nice if PHPStan had some enum types for these parameters; for example [here](https://github.com/pmmp/Math/blob/1c8de44cc46fa300227a35a928c5f14794bc962b/src/Vector3.php#L108) I'm forced to copy `1|2|3|4` instead of being able to write something like `PHP_ROUND_HALF_*`, which is a pain if extra parameter values are ever added.

**Comment by staabm** [comment]
I guess https://github.com/phpstan/phpstan/issues/6160 is what you are suggesting?

**Comment by dktapps** [comment]
That would make it easier for sure. I previously requested something similar myself but was denied.

However, what I would rather have is some kind of pseudo-enum `RoundMode` or something of that nature, rather than being forced to write out all these options myself everywhere I pass through such a parameter.

**Pull request merged**
