### PR TITLE
Implement InvalidDivisionOperationRule

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/11090

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
There is already InvalidBinaryOperationRule so we don't need a new rule: https://phpstan.org/r/42eed56b-0bb3-42b9-8f97-8c53752c4d35

**Comment by VincentLanglet** [comment]
Also, exception checks about `DivisionByZeroError` already covering this case.
It require
- Either to catch the DivisionByZeroError
- Either to add it to the phpdoc

https://phpstan.org/r/06bc1121-7847-4c30-9d19-59c34c9369a0

Adding a new rule will create a duplicate and false positive since
```
	/**
	 * @throws DivisionByZeroError
	 */
	public function sayHello2(int $i, int $j): void
	{
		echo $i / $j; // Not error it's documented
	}
```
is fully valid code.

**Comment by staabm** [comment]
thanks for pointing this out.

> You have to enable "missingCheckedExceptionInThrows", "DivisionByZeroError"

I don't think coverage for a division-by-zero error should be a opt-in thing and "hidden" in the config file.

> There is already InvalidBinaryOperationRule

@ondrejmirtes wdyt about adding the logic of this PR into InvalidBinaryOperationRule (or the type system) while checking the config whether DivisionByZeroError was configured as missingCheckedExceptionInThrows to prevent duplicate errors?

**Comment by staabm** [comment]
submitted a alternative impl as a base for discussion: https://github.com/phpstan/phpstan-src/pull/3419

**Pull request closed without merging**
