### PR TITLE
Fix false positive of access to private property of parent class

### PR DESCRIPTION
**Pull request by tyabu12**
fix https://github.com/phpstan/phpstan/issues/2435

### CODE REVIEW

**Comment by herndlm** [comment]
according to the new bot, your PR would be closing 3 issues 🎉 https://github.com/phpstan/phpstan-src/actions/runs/3428507295

**Comment by ondrejmirtes** [comment]
Please add regression tests for them too :) Thank you.

**Comment by ondrejmirtes** [comment]
When I get around to it, I'll add some smart commenting feature on PRs too. My idea is that when the bot finds changes, it adds a comment with them, but with further force-pushes, it doesn't add new comments, it just edits the first one.

**Comment by ondrejmirtes** [comment]
Perfect, thank you!

**Comment by tyabu12** [comment]
@ondrejmirtes 
Thank you for merging!
Could you also close the following issue that herndlm mentions?

- https://github.com/phpstan/phpstan/issues/7640
- https://github.com/phpstan/phpstan/issues/3572

**Comment by ondrejmirtes** [comment]
Don't worry, I always do that, that's what the bot is for 😊

**Comment by staabm** [comment]
@tyabu12 I am wondering whether we have the same problem in static context in `AccessPrivatePropertyThroughStaticRule`

https://phpstan.org/r/a757dd9c-01fa-450a-96f6-52a10feab73f
https://3v4l.org/YmKc6

**Comment by tyabu12** [comment]
@staabm 
It seems that we still have the same problem in the rule.
Could you open new issue for it?

**Comment by staabm** [comment]
here we go: https://github.com/phpstan/phpstan/issues/8333

**Comment by tyabu12** [comment]
Thank you!

**Pull request merged**
