### PR TITLE
fix SimpleRelativePathHelper when working directory is a deeper path then filename

### PR DESCRIPTION
**Pull request by clxmstaab**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
In this case we just want to reuse the absolute path.

**Comment by clxmstaab** [comment]
> In this case we just want to reuse the absolute path.

the absolute path make our baselines useless, because we get absolute path which only work on the developer workstations and cannot be compared with those generated at "runtime" in CI

**Comment by ondrejmirtes** [comment]
You will not fix the baseline with this. Baseline generation does not know about the file path you’re saving the baseline to.

**Comment by clxmstaab** [comment]
I already confirmed that this fixes my issues

**Comment by ondrejmirtes** [comment]
Baseline generation can only be fixed with these suggestions: https://github.com/phpstan/phpstan/issues/2534#issuecomment-545397707

Why I don't want to pursue your approach:

1) I don't want people to encourage running PHPStan from a project subdirectory, just because of baseline generation. This creates an awkward command in the form of `../../vendor/bin/phpstan analyse ../../src ../../tests -c ../../phpstan.neon`. Running PHPStan as usual and telling it explicitly where it should store the baseline file would solve this better.
2) SimpleRelativePathHelper should stay simple. I don't want it to generate paths that go up a directory with `../../`...

Thank you.

**Comment by staabm** [comment]
Because of the multi app setup we have (see https://github.com/phpstan/phpstan-src/pull/66#issuecomment-568497285) its not possible to not call phpstan from a subdirectory

**Comment by ondrejmirtes** [comment]
I don't get why you have reported errors from `lib/` when analysing `app/app1`. `lib/` should have its own CI build.

**Comment by staabm** [comment]
lib/ contains common logic of app1/2 and the sources within app1/2 does not work without classes from within lib/

**Comment by staabm** [comment]
app1/ phpstan.neon.dist looks like
```
parameters:
    level: 0
    paths:
        - src/
        - ../../lib
```

**Comment by ondrejmirtes** [comment]
The sources from `lib` just have to be available through an autoloader, you don't have to analyse them.

**Comment by staabm** [comment]
Need to play with this idea. Thx for your input. 

Have a happy christmas 🎄 🤟

**Pull request closed without merging**
