### PR TITLE
Upgrade vaimo/composer-patches

### PR DESCRIPTION
**Pull request by herndlm**
was tried already in https://github.com/phpstan/phpstan-src/pull/1647 and https://github.com/phpstan/phpstan-src/pull/2129 but I forgot what the problem was..
I hope CI tells me and this time I'll properly note it down

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
There's also a different library (check what Rector is using), maybe we could switch.

**Comment by herndlm** [comment]
ah ok, I guess the problem is that ` vaimo/composer-patches` dropped the dependency of `drupol/phposinfo` which was replaced with `loophp/phposinfo` and the latest version there is not compatible with PHP 7.2.
using an older version of `loophp/phposinfo` that is (e.g. 1.6.5) still uses the drupol namespace which breaks ` vaimo/composer-patches`.

so effectively ` vaimo/composer-patches` needs `loophp/phposinfo` in `^1.7` which is not compatible with PHP 7.2.

**Comment by herndlm** [comment]
hmm close, it would be possible to make this work I guess, but it looks like it involves more github actions / composer install adaptions / hacks. I'll check out the other lib too.

**Comment by ondrejmirtes** [comment]
`cweagans/composer-patches` was merged

**Pull request closed without merging**
