### PR TITLE
Fix `count($x) > $n === true` negation

### PR DESCRIPTION
**Pull request by rvanvelzen**
Fix phpstan/phpstan#10952

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Awesome, thank you!

**Comment by rvanvelzen** [comment]
The same problem actually applies to `strlen()`, maybe one day I'll submit a PR for that too :)

**Comment by staabm** [comment]
> The same problem actually applies to `strlen()`, maybe one day I'll submit a PR for that too :)

@rvanvelzen  I tried replicating this problem for `strlen()` but did not succeed:
https://phpstan.org/r/fa21633d-7311-406a-8959-cbb4a488a61d

**Comment by rvanvelzen** [comment]
@staabm the problem occurs when wrapping the condition with `(...) === true`: https://phpstan.org/r/8adcd9e6-501f-4e37-a175-001c753a4153

**Pull request merged**
