### PR TITLE
Fix using value-of/key-of with template types

### PR DESCRIPTION
**Pull request by rvanvelzen**
Leverage the power of late-resolved types when necessary.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Yes, makes a ton of sense, thank you :)

**Comment by ondrejmirtes** [comment]
BTW Doesn't `ParametersAcceptorSelector::hasAcceptorTemplateOrConditionalType()` need updating for all late-resolvable types? I'm not sure... (It's an optimization so that this block of code isn't called and some time is saved by not getting the arg types):

```php
		foreach ($args as $i => $arg) {
			$type = $scope->getType($arg->value);
			$index = $arg->name !== null ? $arg->name->toString() : $i;
			if ($arg->unpack) {
				$unpack = true;
				$types[$index] = $type->getIterableValueType();
			} else {
				$types[$index] = $type;
			}
```

**Comment by rvanvelzen** [comment]
It should be fine right now because `value-of` and `key-of` are not resolvable if they contain a template type which is already checked. For simplicity and future-proofing it could be changed to just look for `LateResolvableType` instead.

**Comment by ondrejmirtes** [comment]
Alright, done: https://github.com/phpstan/phpstan-src/commit/38198f166ae90289c3ac595095d01b154b396101

**Pull request merged**
