### PR TITLE
preg_split sometimes returns array of arrays

### PR DESCRIPTION
**Pull request by spaze**
When `PREG_SPLIT_OFFSET_CAPTURE` flag is given

```php
preg_split('/-/', 'a-b-c', -1, PREG_SPLIT_OFFSET_CAPTURE);
```
See https://3v4l.org/B4Qf5

Then "this changes the return value in an array where every element is an array consisting of the matched string at offset 0 and its string offset into subject at offset 1."

### CODE REVIEW

**Comment by dktapps** [comment]
Wouldn't a dynamic return type extension be better for this?

**Comment by ondrejmirtes** [comment]
Thank you, but yes, dynamic return type extension would be better so that the user doesn't have to check against values that cannot occur in their situation :)

@spaze I'm sure you won't have any problems writing one as you've already written some custom PHPStan rules :) Here are some pointers:

* Basic info: https://phpstan.org/developing-extensions/dynamic-return-type-extensions
* This is a similar extension that also reads various constants (although it's probably much more complicated than one needed for `preg_split`: https://github.com/phpstan/phpstan-src/blob/master/src/Type/Php/FilterVarDynamicReturnTypeExtension.php
* This is a useful method: https://github.com/phpstan/phpstan-src/blob/4f152b291da55d19e9b28a8d1bd5bc435b4ccd2c/src/Type/Php/FilterVarDynamicReturnTypeExtension.php#L75-L84 (feel free to copy it to your extension as well)
* I'm not sure if preg_split flags can be combined using bitwise operators, if yes then the extension has to account for it.
* Test the implementation by adding a new data provider to NodeScopeResolverTest::testFileAsserts, call `assertType` in the test file and test various inputs :)

**Comment by spaze** [comment]
Thanks, I've vaguely remembered there was a better way of doing things like this but...

I've now changed this PR to use a dynamic type extension for that.

And thanks @ondrejmirtes for those hints, helped a lot!

**Comment by ondrejmirtes** [comment]
Perfect, thank you :)

**Comment by spaze** [comment]
Thanks for the release @ondrejmirtes! :-)

**Pull request merged**
