### PR TITLE
Add missing iterator stubs

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- Relates to https://github.com/phpstan/phpstan/issues/6555
- Add more iterator stubs

### CODE REVIEW

**Comment by staabm** [comment]
This PR is getting pretty big (and hard to review).

it might be usefull to separate low hanging fruits/easy picks into a separate PR.

the changes itself seem to be mostly independet from each other, so this should be easily doable, right?

**Comment by drupol** [comment]
Indeed, I had that in my mind, this is also why I split every commit. I just need a bit of time to do the PRs.

**Comment by staabm** [comment]
Just realized we dont know types of RecursiveFilterIterator in phpstan.

maybe you want to add them with this PR

**Comment by ondrejmirtes** [comment]
Please send one PR at a time for each stub (have a single PR open at a time, after it's merged please open another one). Thanks.

**Pull request closed without merging**
