### PR TITLE
Update return types for hash functions

### PR DESCRIPTION
**Pull request by jlherren**
This consolidates `HashHmacFunctionsReturnTypeExtension` into `HashFunctionsReturnTypeExtension` (the two classes were very similar) and adds support for `hash_file()`, `hash_hkdf()` and `hash_pbkdf2()`.

It now also deduces the return type correctly when writing `hash($cond ? 'md5' : 'sha256', ...)`.

I also added `non-empty-string` for return types and parameters. Return types should be fine, but I'm not sure whether it's too dangerous to narrow function parameters from `string` to `non-empty-string`, since that's likely to cause new errors. If that's not desired, I can remove them again.

Finally, I'm not sure about why there was logic to treat a `mixed` argument for the `$algo` parameter in such a way, that these functions would return `(string|false)`, but I left it like that. Perhaps this can be changed to `string|false`?

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, the build failed, also please fix the conflict :) Thank you.

**Comment by ondrejmirtes** [comment]
BTW there are some build failures on current master (in testing 3rd party projects coming from phpstan/phpstan) so beware, I hope to fix them soon.

**Comment by jlherren** [comment]
Thank you! Yes, I currently struggle in writing test that are expected to behave differently between PHP 7.4 and PHP 8.0+. Specifically, some of those functions no longer return `false` in PHP 8.  But I'm not yet sure how to test that with `NodeScopeResolverTest`. I'll continue trying when I get time again.

**Comment by ondrejmirtes** [comment]
You can yield different files based on PHP_VERSION_ID :) It's already happening in that test a few times :)

**Comment by jlherren** [comment]
I think I got it sorted out now (not yet pushed). However, I came across [this bug](https://github.com/php/php-src/issues/7759) that affects the PHP 8 stubs. I'll wait to see what happens over there and update the stubs once that is fixed.

**Comment by jlherren** [comment]
Okay, the stubs are fixed, let's try again :) This time I also removed `non-empty-string` from parameters, it seems it causes too much troubles.

**Comment by ondrejmirtes** [comment]
This might be fine, the failures are unrelated, I'm gonna review it soon :) Thank you!

**Comment by ondrejmirtes** [comment]
Thank you! Merged: https://github.com/phpstan/phpstan-src/commit/1ec1c919f20e962b563949d5ac9fcaf0db90dc34

**Pull request closed without merging**
