### PR TITLE
Fix unassigning the last offset in a ConstantArray that is a list

### PR DESCRIPTION
**Pull request by herndlm**
Those keep being lists.

Fixes https://github.com/phpstan/phpstan/issues/11718

### CODE REVIEW

**Comment by herndlm** [comment]
nope, I was overlooking https://3v4l.org/n5E7F

so the array is a list until another element is added again. ouch. might need changes to `setOffsetValueType()` too..

UPDATE: adapted

**Comment by ondrejmirtes** [comment]
Closing because of: https://github.com/phpstan/phpstan/issues/11718#issuecomment-2363791774

**Comment by herndlm** [comment]
ok. the changes here made the "array with last item unset"-is-still-a-list part work while also removing the list when more is assigned. it indeed feels slightly weird and a non-well-defined state though

**Comment by ondrejmirtes** [comment]
We can't do that because if you passed it somewhere else as a list, and the other place appended an element, the assumption would be broken, and PHPStan would think it has a list but in reality it wouldn't be a list.

**Pull request closed without merging**
