### PR TITLE
WIP ArrayIntersection

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, I don't know if something like this would work. Either I'll look into it when I consider it a priority, or you need to submit a PR that works, including tests.

**Comment by VincentLanglet** [comment]
> Hi, I don't know if something like this would work. Either I'll look into it when I consider it a priority, or you need to submit a PR that works, including tests.

Sure, I was curious to get some feedback. I'll see if I can improve this.

In order to add e2e tests, I'll need to correctly parse `array{foo: bar}&array<string, string>` isn't it ?
I'll be happy to try to add e2e tests on the different rules, but I don't understand the code enough to modify the `intersect` method in order to generate the ArrayIntersection type.

**Comment by VincentLanglet** [comment]
How can I add test to this since the parser is not understanding `array{foo: bar}&array<string, string>` atm @ondrejmirtes ?

**Comment by ondrejmirtes** [comment]
Hi, I'm not convinced I want this syntax anyway, as discussed here: https://github.com/vimeo/psalm/issues/4700#issuecomment-870369305

**Pull request closed without merging**
