### PR TITLE
Fix Imagick::scaleImage parameter name

### PR DESCRIPTION
**Pull request by davidkmenta**
According to https://github.com/php/doc-en/pull/2444

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
What kind of bug are you experiencing that is fixed with this change?

**Comment by davidkmenta** [comment]
When using named attributes, the phpstan reports errors according to the badly documented method signature. This code:

```php
$image = new \Imagick();
$image->readImageFile($fileStream);
$image->scaleImage(columns: 1500, rows: 1500, bestfit: true);
```

produces these errors:

>Missing parameter $cols (int) in call to method Imagick::scaleImage().    
>Unknown parameter $columns in call to method Imagick::scaleImage().

but it should not as the named attributes are correct and the code works.

**Comment by ondrejmirtes** [comment]
Please verify that your change actually helps by writing a new test in CallMethodsRuleTest.

Your change might help, but it might also need a different fix in https://github.com/JetBrains/phpstorm-stubs/blob/077d371b23d38d7f6f039994bfb03732d7965fbc/imagick/imagick.php#L1962.

**Comment by davidkmenta** [comment]
Fixed by #2580.

**Pull request closed without merging**
