### PR TITLE
create recursive directory structures

### PR DESCRIPTION
**Pull request by swiffer**

### CODE REVIEW

**Comment by swiffer** [comment]
Does it fix https://github.com/phpstan/phpstan/issues/3918

**Comment by ondrejmirtes** [comment]
Recursive mkdir isn't thread-safe so this solution cannot be used.

**Comment by ondrejmirtes** [comment]
And it misses what's actually going on, which I described in this comment: https://github.com/phpstan/phpstan/issues/3918#issuecomment-703891293

**Comment by swiffer** [comment]
yeah, seems to miss what's going on according to your comment - but

when i'm using any version newer than 0.12.42 for me running phpstan in ci fails because of:

`Cannot create a temp directory /builds/my_project/.cache/phpstan`

(where .cache and .cache/phpstan where not existing)

with
```neon
includes:
	- vendor/phpstan/phpstan/conf/bleedingEdge.neon
parameters:
    level: 7
    phpVersion: 70400
    checkMissingIterableValueType: false
    bootstrapFiles:
        - config/bootstrap.php
    tmpDir: .cache/phpstan
    paths:
        - src
    excludes_analyse:
        - src/Console/Installer.php
```

i've now added `mkdir -p .cache` to ensure the .cache dir exist prior to running phpstan and this indeed fixes the problem for me.

maybe it's a different one...

**Comment by ondrejmirtes** [comment]
This changes things as they were pre-0.12.42: https://github.com/phpstan/phpstan-src/commit/5be8b8081bb01cc8c2ea0c91554288777b2a4f90

**Pull request closed without merging**
