### PR TITLE
added more integer range vs. int constants tests

### PR DESCRIPTION
**Pull request by staabm**
refs https://github.com/phpstan/phpstan-src/pull/1742#issuecomment-1256099860

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you! BTW Why do you have two GitHub accounts used seemingly randomly? 🤔

**Comment by staabm** [comment]
I have one account for private stuff (configured on my personal computer) and another account for company stuff (which is configured on a different computer).

Depending on where I currently work, I can commit stuff into each others PR 

:-)

**Comment by ondrejmirtes** [comment]
A tip: Use .git/config in your local clone of phpstan-src to unify this for PHPStan :)

**Comment by herndlm** [comment]
Yeah I was wondering the same thing already :) btw I also use two computers where I git config my private email into one for phpstan because the global one is my work email

**Comment by mad-briller** [comment]
i think my first commit to phpstan was with my work email not my github one, but it was already merged before i realized :sweat_smile: 

you can set it with `git config user.name <name>` and `git config user.email <email>`

**Pull request merged**
