### PR TITLE
functionMap.php fixes for YAF 3.3.5

### PR DESCRIPTION
**Pull request by mbakirov**
This branch contains fixes for Yaf classes corresponding official stubs:
- Yaf_Config_* https://github.com/laruence/yaf/blob/9cde8111c1dd679d3d8185123cbd73658cc6e64c/yaf_config.stub.php
- Yaf_Controller_* https://github.com/laruence/yaf/blob/9cde8111c1dd679d3d8185123cbd73658cc6e64c/yaf_controller.stub.php
- Yaf_Dispatcher_* https://github.com/laruence/yaf/blob/9cde8111c1dd679d3d8185123cbd73658cc6e64c/yaf_dispatcher.stub.php
- Yaf_Request_* https://github.com/laruence/yaf/blob/9cde8111c1dd679d3d8185123cbd73658cc6e64c/yaf_request.stub.php
- Yaf_Response_* https://github.com/laruence/yaf/blob/9cde8111c1dd679d3d8185123cbd73658cc6e64c/yaf_response.stub.php
- Yaf_View_* https://github.com/laruence/yaf/blob/9cde8111c1dd679d3d8185123cbd73658cc6e64c/yaf_view.stub.php

### CODE REVIEW

**Comment by mbakirov** [comment]
As @ondrejmirtes said, someone still uses Yaf =)

**Comment by ondrejmirtes** [comment]
Yeah I know (/cc @staabm), developing open-source gives you a hunch for these things :) I'm gonna look at this asap, but I'm travelling at the moment. Thanks!

**Comment by staabm** [comment]
LoL. A few days after I tried deleting it :-)

**Comment by ondrejmirtes** [comment]
Thank you very much!

**Pull request merged**
