### PR TITLE
Enforce magic signatures

### PR DESCRIPTION
**Pull request by staabm**
make sure all magic signatures defined in https://www.php.net/manual/en/migration80.incompatible.php are covered

followup to https://github.com/phpstan/phpstan-src/pull/2372/

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Levels tests need updating.

**Comment by staabm** [comment]
fixed

**Comment by ondrejmirtes** [comment]
Needs a rebase, sorry.

**Comment by staabm** [comment]
no worries. here you are.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
