### PR TITLE
Add SensitiveParameter stub

### PR DESCRIPTION
**Pull request by staabm**
see https://stitcher.io/blog/new-in-php-82#redact-parameters-in-back-traces-rfc

refs https://wiki.php.net/rfc/redact_parameters_in_back_traces

the RFC mentions another class involved, which is `SensitiveParameterValue`.
it will only be needed at runtime - as a place-holder for the sensitive value beeing masked, and therefore no additional stubs are required regarding that one.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
That test could never fail, it's in a wrong class. It's parameter attribute, not class attribute.

**Comment by staabm** [comment]
🤦 - good catch. moved the test.

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by staabm** [comment]
for posterity: this needed an additional fix in https://github.com/ondrejmirtes/BetterReflection/commit/7f99a91d1a271de20d00eb5ac81f0342c6238b92

**Pull request merged**
