### PR TITLE
array_filter w/ arrow functions return type extension

### PR DESCRIPTION
**Pull request by b1rdex**
Fixes https://github.com/phpstan/phpstan/issues/4188

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
1) Please fix the build.
2) Please add an actual test for the rule that flags the code as errorneous in https://github.com/phpstan/phpstan/issues/4188, thanks.

**Comment by ondrejmirtes** [comment]
FYI you can also run tests locally, simply run `vendor/bin/phing tests-fast` :) And I still need the regression test for the actual error message from https://github.com/phpstan/phpstan/issues/4188. Probably in CallMethodsRuleTest.

**Comment by b1rdex** [comment]
@ondrejmirtes I added another test. I don't know why, but it fails with `Call to method onlyB() on an unknown class Bug4188\Test`. I can't find any way to solve it.

**Comment by ondrejmirtes** [comment]
You need to run composer dump-autoload, then run the test.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
