### PR TITLE
Nuke `OriginalPropertyTypeExpr`

### PR DESCRIPTION
**Pull request by herndlm**
just want to know what this affects outside of PHPStan's test suite..

I assume it will lead to some improvements in edge cases while causing some other edge case issues, especially with invalid offset setting on array props.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
There aren't many integration tests running right now :)

**Comment by herndlm** [comment]
ok, still interesting. looks like this would fix

- https://github.com/phpstan/phpstan/issues/7880
- https://github.com/phpstan/phpstan/issues/6571
- https://github.com/phpstan/phpstan/issues/6398

downside could be some weird types in errors in some cases, especially phpstan's test suite that tries to assign incorrect types in a row. more integration tests would be interesting I guess :)

**Comment by herndlm** [comment]
enough for today. it would be interesting to see if the type from the scope can be used for that `TypesAssignedToPropertiesRule` rule only, while not modifying the property type itself. that would be the best of both worlds I suppose..

**Comment by herndlm** [comment]
Ok, I think I know what I have to do :)

**Comment by ondrejmirtes** [comment]
Finally figured it out https://github.com/phpstan/phpstan-src/commit/a8cae55bcbab4ddb1529abaa83947cd6f0968ecf

**Comment by herndlm** [comment]
> Finally figured it out [a8cae55](https://github.com/phpstan/phpstan-src/commit/a8cae55bcbab4ddb1529abaa83947cd6f0968ecf)

amazing that you still remembered this PR :D

**Comment by ondrejmirtes** [comment]
There are things that haunt me for years until they're solved 😀

**Pull request closed without merging**
