### PR TITLE
Fix: Set COMPOSER_ROOT_VERSION environment variable

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] trades in a hard-coded `COMPOSER_ROOT_VERSION` environment variable for setting it from `composer.json` using `jq`

### CODE REVIEW

**Comment by localheinz** [comment]
Also see https://github.com/sebastianbergmann/type/pull/12.

**Comment by ondrejmirtes** [comment]
Thank you! This would definitely be a nice action by itself, with configurable (using `with` section) branch alias to use, e.g. `dev-master` :)

**Comment by localheinz** [comment]
@ondrejmirtes 

I agree!

**Comment by localheinz** [comment]
Thank you, @ondrejmirtes!

**Pull request merged**
