### PR TITLE
Allow lowercase variant of constant

### PR DESCRIPTION
**Pull request by VincentLanglet**
Close https://github.com/phpstan/phpstan/issues/4431

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Don't forget about setrawcookie

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
And I guess the non-array setcookie variant could also use those constants.

**Comment by VincentLanglet** [comment]
It should be better now @ondrejmirtes :)

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
