### PR TITLE
RegularExpressionPatternRule: fix false positive in preg_quote() handling

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/11432

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by ondrejmirtes** [comment]
Some new error appeared based on this, can you look if it's valid or not? https://github.com/phpstan/phpstan/actions/runs/10226167599/job/28296101528

**Comment by staabm** [comment]
> Some new error appeared based on this, can you look if it's valid or not? [phpstan/phpstan/actions/runs/10226167599/job/28296101528](https://github.com/phpstan/phpstan/actions/runs/10226167599/job/28296101528)

thats a interessting case: https://github.com/PrestaShop/PrestaShop/blob/ca9d81aae0bb17f3e767bb5d835348ed144a3ab5/src/Adapter/Assets/AssetUrlGeneratorTrait.php#L57

@Seldaek do you agree that for proper escaping the PrestaShop code would need a tripe backslash like in https://3v4l.org/8fsWi ?

another example - which IMO also proves the regex in PrestShop is missing a 3rd backslash - is https://3v4l.org/Td9vj

**Comment by Seldaek** [comment]
Yeah that's a case of needing 4 backslashes imo.. You really want one in the pattern so you have to escape it as 2 and then each of those again escaped for the php string. Technically 3 works the same i suppose as long as it's not double quoted strings and depending what follows the 3rd.

**Comment by ondrejmirtes** [comment]
FYI this is currently blocking me from release, this bug is still present and generating errors in Prestashop.

**Comment by staabm** [comment]
As I understood it, its a bug in prestashop because they wrongly escape.

**Comment by ondrejmirtes** [comment]
OK, thanks!

**Pull request merged**
