### PR TITLE
Fix/issue 7109

### PR DESCRIPTION
**Pull request by rajyan**
fixes https://github.com/phpstan/phpstan/issues/7109

See https://github.com/phpstan/phpstan/issues/7109#issuecomment-1109876639 for the discussion and implementation

### CODE REVIEW

**Comment by rajyan** [comment]
@ondrejmirtes 
I'm almost done except the error message. Do we need a node connecting visitor to change messages by coalesce/isset/empty?

**Review by ondrejmirtes — APPROVED** [review]
Thank you, this is really nice! I'll look into improving the error message myself 😊

**Comment by ondrejmirtes** [comment]
Thank you. I'll try to improve the message directly on the branch.

**Comment by ondrejmirtes** [comment]
Alright, done: https://github.com/phpstan/phpstan-src/commit/54f15441eba3907c4ff056f6dafb1c2801a6b766

I took advantage of IssetCheck already knowing the right context, I also tried to preserve the original behaviour as much as possible.

**Comment by rajyan** [comment]
@ondrejmirtes 
Thank you. Your changes looks better!
Didn't need to check https://github.com/phpstan/phpstan-src/pull/1253/files#diff-5cc10d718dd4dbca2d13640be20698dff3831518d541839da32e32ac86ab4c50L26-L34
because null safe property fetch is always unnecessary.

**Comment by rajyan** [comment]
@ondrejmirtes 
> always unnecessary.

Oh, it was not.
https://github.com/phpstan/phpstan/issues/7109#issuecomment-1110545290
```
null->test->call() ?? "test";
```
this might be an edge case of this fix.

When there is a method call, all expression before it is evalauted (and property fetch on null cause a warning)

**Comment by ondrejmirtes** [comment]
@rajyan Can you please show that on phpstan.org/try and post the expected output? Thanks :)

**Comment by rajyan** [comment]
@ondrejmirtes 
Sorry, on second thought, your fix looks perfect!

**Comment by ondrejmirtes** [comment]
Alright, feel free to submit a regression test for the `null->` scenario :)

**Pull request merged**
