### PR TITLE
Do not assume that arrays are always instanceof ArrayType

### PR DESCRIPTION
**Pull request by dktapps**
they might be intersection type, union type, or something else.
I don't think there's a way to test this without #315.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
There's no actual difference because you can't write any union or intersection type of arrays as native closure return type...

But otherwise yeah, I changed most instances of `instanceof ArrayType` to `->isArray()`.

**Comment by dktapps** [comment]
@ondrejmirtes I noticed it in a CI failure on #315 so I thought it made sense to change it. For future proofing.

**Comment by ondrejmirtes** [comment]
Which CI failure do you think is related to that?

**Comment by dktapps** [comment]
This one: https://github.com/phpstan/phpstan-src/pull/315/checks?check_run_id=1065415207#step:7:212

**Comment by dktapps** [comment]
Image for posterity since the link seems to be flaky: 
image

**Pull request closed without merging**
