### PR TITLE
Consider last `else if` of an `if` / `else if` combination to be the last condition

### PR DESCRIPTION
**Pull request by herndlm**
Closes https://github.com/phpstan/phpstan/issues/10113

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Would this error go away too? https://phpstan.org/r/6e31b9d4-2f6b-4c02-9c8c-72f62dc720f8

**Comment by herndlm** [comment]
> Would this error go away too? https://phpstan.org/r/6e31b9d4-2f6b-4c02-9c8c-72f62dc720f8

no, but looks like the related rule (`UnreachableIfBranchesRule`) is not using the `isLastCondition` attribute yet.

**Comment by herndlm** [comment]
> > Would this error go away too? https://phpstan.org/r/6e31b9d4-2f6b-4c02-9c8c-72f62dc720f8
> 
> no, but looks like the related rule (`UnreachableIfBranchesRule`) is not using the `isLastCondition` attribute yet.

did a deeper check, the visitor is not handling `else` at all, so it will never be set. if this should go away that specific rule needs an adaption I'd say, this PR is basically unrelated IMO.

**Comment by ondrejmirtes** [comment]
I'd accept a PR that runs a special visitor in RichParser before all the visitors that would transform AST with many `else if`s into a flat `elseif` structure :)

**Comment by herndlm** [comment]
superseded by https://github.com/phpstan/phpstan-src/pull/2799

**Comment by herndlm** [comment]
@ondrejmirtes since https://github.com/phpstan/phpstan-src/pull/2799 didn't work out, would you consider this solution after all?

**Comment by ondrejmirtes** [comment]
This probably needs a different solution than transforming the AST for everyone.

**Comment by herndlm** [comment]
> This probably needs a different solution than transforming the AST for everyone.

yeah. so, https://github.com/phpstan/phpstan-src/pull/2799 was the AST transformation which didn't work. this here was the less invasive `LastConditionVisitor` which worked fine :)

**Pull request closed without merging**
