### PR TITLE
Report precise offsets in errors

### PR DESCRIPTION
**Pull request by ruudk**
Fixes phpstan/phpstan#11760

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
Some CS violations here https://github.com/phpstan/phpstan-src/actions/runs/11069234135/job/30756357522

**Comment by ruudk** [comment]
Fixed! 

💡 TIL: `make cs + make cs-fix`

**Comment by ruudk** [comment]
I believe the 71 failing tests are unrelated to my change. Is that correct?

**Comment by ruudk** [comment]
I'm wondering. Shouldn't we also port this to 1.12 under bleeding edge? You say that 1.12 + bleeding edge == 2.0, right?

**Comment by ondrejmirtes** [comment]
2.0 is close enough :)

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
