### PR TITLE
Allow null as a return value when resolving return types

### PR DESCRIPTION
**Pull request by matthiasnoback**
This fixes an issue reported earlier: https://github.com/phpstan/phpstan/issues/5855

Please let me know if you want me to provide anything else at this point.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
It's technically a BC break but I doubt that anyone calls these directly:

```

[BC] CHANGED: The return type of PHPStan\Type\DynamicFunctionReturnTypeExtension#getTypeFromFunctionCall() changed from PHPStan\Type\Type to the non-covariant ?PHPStan\Type\Type
[BC] CHANGED: The return type of PHPStan\Type\DynamicFunctionReturnTypeExtension#getTypeFromFunctionCall() changed from PHPStan\Type\Type to ?PHPStan\Type\Type
[BC] CHANGED: The return type of PHPStan\Type\DynamicMethodReturnTypeExtension#getTypeFromMethodCall() changed from PHPStan\Type\Type to the non-covariant ?PHPStan\Type\Type
[BC] CHANGED: The return type of PHPStan\Type\DynamicMethodReturnTypeExtension#getTypeFromMethodCall() changed from PHPStan\Type\Type to ?PHPStan\Type\Type
[BC] CHANGED: The return type of PHPStan\Type\DynamicStaticMethodReturnTypeExtension#getTypeFromStaticMethodCall() changed from PHPStan\Type\Type to the non-covariant ?PHPStan\Type\Type
[BC] CHANGED: The return type of PHPStan\Type\DynamicStaticMethodReturnTypeExtension#getTypeFromStaticMethodCall() changed from PHPStan\Type\Type to ?PHPStan\Type\Type
```

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by matthiasnoback** [comment]
> It's technically a BC break

Never saw that tool being used, seems very useful!
Right, as you mentioned earlier, for implementers it's no issue, but for clients it could be.

Thanks for the quick merge!

I think it would be nice to update the documentation about type extensions as well: instead of always returning a type using the default `selectFromArgs()` call you can now return `null` if you don't have a specific type. Can I do that? Should this happen on the phpstan/phpstan repository?

**Comment by ondrejmirtes** [comment]
Yes, documentation pages have "Edit this page" link at the bottom 😊 Please don't forget to mention that "null" can be used since PHPStan 1.5.0. (I'll merge it after the release which is gonna be in a few weeks).

**Pull request merged**
