### PR TITLE
ParaTest: leverage WrapperRunner for quicker tests

### PR DESCRIPTION
**Pull request by Slamdunk**
Hi, opened this PR as *draft* to see if the Windows builds get a significant improvement.

### CODE REVIEW

**Comment by staabm** [comment]
I see fatal erros in tests I recently added. It looks like these should use separate php namespaces (they overlap across files atm)

**Comment by Slamdunk** [comment]
Yup, working on it. In the meantime, results are encouraging:

| Before | After |
|---|---|
|image|image|

**Comment by staabm** [comment]
Yep, I also saw these numbers. Looks really nice

**Comment by Slamdunk** [comment]
@staabm I'm having trouble fixing the class name collision introduced in https://github.com/phpstan/phpstan-src/pull/1082

Could you have a look at it please while I'm figuring out the paratest error on Win+PHP7.2?

The short command to raise the error is:

```console
vendor/bin/phpunit --filter '/(value-of-enum|testValueOfEnum)/' --debug
```

**Comment by staabm** [comment]
I think the fix should look like https://github.com/phpstan/phpstan-src/commit/2e2c62cba316355bc2eac865d1fb2a342124adc3

**Comment by Slamdunk** [comment]
I've tried many iterations like that, but still it seems a `require` is being done twice :\

**Comment by staabm** [comment]
oh,.. then we should drop this line I guess

https://github.com/phpstan/phpstan-src/pull/1082/files#diff-f2a343029c039bbc2575f7cfd07e807dbaf777db062319d7b7456e669a7bab7cR213

**Comment by Slamdunk** [comment]
Already tried that too, unsuccessfully :\

**Comment by staabm** [comment]
hmmm all green on my end? - see only a different problem in "old PHPUnit" jobs

https://github.com/phpstan/phpstan-src/pull/1117

**Comment by Slamdunk** [comment]
Not reliable: `WrapperRunner` is not deterministic, the two colliding tests can randomly get executed in the same proc or in different procs.

Try that PR locally with the aforementioned command, you'll see it failing:

```
$ vendor/bin/phpunit --filter '/(value-of-enum|testValueOfEnum)/' --debug
PHP Fatal error:  Cannot declare class ValueOfEnumPhpdoc\Country, because the name is already in use in ./phpstan-src/tests/PHPStan/Rules/PhpDoc/data/value-of-enum.php on line 7
```

**Comment by staabm** [comment]
> Try that PR locally with the aforementioned command, you'll see it failing:

I can reproduce the error locally. with the changes of #1119 the test-suite runs cleanly on my machine.

unrelated question: I am wondering why paratest uses just 6 workers on my laptop, even though it can run 12 threads (6 cores, 12 SMT threads)

**Comment by ondrejmirtes** [comment]
I'm blown away by this! On my local machine running the tests just went down from 18s to 11s!

**Comment by ondrejmirtes** [comment]
I'm gonna go ahead and merge it, thank you :)

**Comment by ondrejmirtes** [comment]
Hi, could you please work out why it doesn't finish on PHP 7.2 on Windows? I reworked how the patch is applied (https://github.com/phpstan/phpstan-src/pull/1115/commits/d99708f1971402b100ad3556a8b61a0eef326491) but that shouldn't cause an issue. Thank you.

**Comment by ondrejmirtes** [comment]
It always times out after 60 minutes: https://github.com/phpstan/phpstan-src/actions/runs/2048944923

**Comment by ondrejmirtes** [comment]
I'm trying if the original works or not: https://github.com/phpstan/phpstan-src/pull/1130

**Comment by ondrejmirtes** [comment]
Didn't help, decided to do this for now: https://github.com/phpstan/phpstan-src/commit/a95ce30d8d036fe5232815ff12d229cea4b1f46a

**Comment by Slamdunk** [comment]
> It always times out after 60 minutes

Yup, I saw that, I was planning to tackle it this week :+1:

**Comment by ondrejmirtes** [comment]
Alright, you can start by reverting the commit that removes testing on Windows 😊 Thanks.

**Comment by ondrejmirtes** [comment]
But don't sink too much time into it, it's not worth it 😊 Thanks.

**Comment by Slamdunk** [comment]
Ok then.

Worth mentioning that I'm the ParaTest maintainer: ping me if you need further help on this topic.

**Comment by Slamdunk** [comment]
Before:
image
After:
image

:rocket:

**Comment by ondrejmirtes** [comment]
An idea - we could bump PHPUnit to 8.5 if there was a compatible ParaTest version that would work on PHP 7.2. Don't know if it's solve anything though.

**Comment by staabm** [comment]
maybe we could just invoked paratest without `--runner WrapperRunner` on php72 ?

**Comment by ondrejmirtes** [comment]
I've got the same idea but since I've already got an appetite for a faster pipeline like this, I rather removed testing on Windows on 7.2.

**Comment by Slamdunk** [comment]
> An idea - we could bump PHPUnit to 8.5 if there was a compatible ParaTest version that would work on PHP 7.2. Don't know if it's solve anything though.

When I became the main maintainer, ParaTest already had all the good ideas and stuff wrote, but with very poor CC, bad overall design and zero static analysis. I had to make sharp turns to unburden maintenance costs, so backporting would be very costly.
7.2 seems to go pretty well on Ubuntu: if you are ok to not test against Windows on PHP 7.2, you would ease my life a lot.

Starting from ParaTest 6, I can guarantee pretty decent support even in the future though, for every platform PHPUnit supports too.

**Comment by ondrejmirtes** [comment]
Yes, the current status is fine, thank you :) It's my choice to support older PHP versions, I don't want to forward that burden to anyone.

**Pull request merged**
