### PR TITLE
Add non regression test for bug 5232

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/phpstan/phpstan/issues/5232

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
I haven't written this one yet, so you can do that :)

This should be a test for ReturnTypeRuleTest. I reserve AnalyserIntegrationTest.php for things that crash PHPStan or for bad performance problems.

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
This test would never fail, you should check that by cherrypicking it on top of 1.8.x before the yesterday's fixes 😊

A hint: there are two ReturnTypeRuleTest classes.

**Comment by VincentLanglet** [comment]
> This test would never fail, you should check that by cherrypicking it on top of 1.8.x before the yesterday's fixes 😊

Indeed, I always confuse method and functions...

Should be better now

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
