### PR TITLE
Fix Union with float should accept integer range

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/phpstan/phpstan/issues/10248

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
This fixes https://github.com/phpstan/phpstan/issues/9659 too, please add a regression test.

**Comment by VincentLanglet** [comment]
> This fixes [phpstan/phpstan#9659](https://github.com/phpstan/phpstan/issues/9659) too, please add a regression test.

Done.

BTW, I do you know which issue it will solve. I assume you had a CI for this ?

**Comment by staabm** [comment]
You can see it in the issue-bot job summary

https://github.com/phpstan/phpstan-src/actions/runs/10338705040

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
