### PR TITLE
Fix specifying types for left side of null coalesce

### PR DESCRIPTION
**Pull request by rvanvelzen**
Fix phpstan/phpstan#5304
Fix phpstan/phpstan#7244
Fix phpstan/phpstan#7501
Fix phpstan/phpstan#7639
Fix phpstan/phpstan#7949

### CODE REVIEW

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
1) Would you try deleting the `if` about Coalesce in TypeSpecifier on line 971 to see if it's still needed?
2) Shouldn't this somehow work recursively even for `$foo ?? $bar ?? $baz`?

**Comment by rvanvelzen** [comment]
> 1. Would you try deleting the if about Coalesce in TypeSpecifier on line 971 to see if it's still needed?

The `bug-560` test fails without it

> 2. Shouldn't this somehow work recursively even for $foo ?? $bar ?? $baz?

Without thinking too much about it it might, but I'd rather approach that separately - I haven't seen that kind of type narrowing in actual code before.

**Comment by rvanvelzen** [comment]
The test failure is unrelated as far as I can tell - broken by https://github.com/laravel/framework/commit/d44c34505296f968c4233f0ddcf66f7d45834e5a

**Comment by ondrejmirtes** [comment]
I agree, thank you very much 😊

**Pull request merged**
