### PR TITLE
Improve performance by change count(array) to empty array [] comparison

### PR DESCRIPTION
**Pull request by samsonasik**
@ondrejmirtes @TomasVotruba this is for increase PHPStan performance improvement by replace count($array) === 0 or count($array) > 0  to empty array comparison $array === [] or $array !== [], it utilize rector's `Rector\CodingStyle\Rector\FuncCall\CountArrayToEmptyArrayComparisonRector::class`.

Rector probably needed to be part of CI workflow to verify it if it is approved, @ondrejmirtes what do you think?

### CODE REVIEW

**Comment by samsonasik** [comment]
compiler tests notice seems unrelated

**Comment by ondrejmirtes** [comment]
Hi, thank you, but I doubt this has real world performance implications. Did you measure it?

**Comment by samsonasik** [comment]
You can check this benchmark https://phpsandbox.io/n/polished-violet-mwjd-llhvj

```
Count took: 0.316ms
Compare to empty array took: 0.018ms
```

**Comment by TomasVotruba** [comment]
@samsonasik Cool tool, thanks for sharing the link :+1: 

I tried to re-run it couple of times and got wide range of numbers:

* count: 160-250 ms
* compare empty array: 15-30 ms

Factor 10x for the empty array.

**Comment by ondrejmirtes** [comment]
Yeah, but it's not obvious what it means for PHPStan from these benchmarks. I'll have to compare it with Blackfire.

**Comment by orklah** [comment]
Weird, I don't reproduce the same time with 3v4l at all:
https://3v4l.org/uc9iY

Maybe a difference in opcache setup?

I had to reduce the content of the array by a factor of ten, but I doubt this would have this kind of dramatic effect. I also have a different benchmark script that show similar results: https://3v4l.org/TNFbu (ie, no dramatic effect in one way or another)

But I still prefer !== [] / === [] notation !

**Comment by ondrejmirtes** [comment]
I prefer the `count` version so I need some hard evidence this improves PHPStan performance by at least a few percents :)

**Comment by staabm** [comment]
AFAIR will php-src optimizes code when you write \count() at compile time.

using `count` without a prior `use function` or without a fully-qualified notation will not benefit from php-src compilation passes.

**Comment by Dgame** [comment]
> I prefer the `count` version so I need some hard evidence this improves PHPStan performance by at least a few percents :)

I doubt that there is one. In contrast to earlier PHP versions (I think from >=PHP 7.0) `count` only reads the `length` property of the internal buckets, so it's not as costly. I also like the `== []` comparison much better, but if you compare both versions, you see almost no difference: https://3v4l.org/tF1WE

**Comment by staabm** [comment]
> using count without a prior use function or without a fully-qualified notation will not benefit from php-src compilation passes.
i.e. this PR as is improves performance when the native count function is not imported via use function.
(this only works for namespace'd code and depends on opcache beeing used) 

my assumption was wrong

https://twitter.com/nikita_ppv/status/1482096003721355266?s=20

**Comment by staabm** [comment]
in https://github.com/phpstan/phpstan-src/pull/747#discussion_r738037863 we concluded that this change is not worth it

**Pull request closed without merging**
