### PR TITLE
Add AllowDynamicProperties stub

### PR DESCRIPTION
**Pull request by andypost**
refs https://wiki.php.net/rfc/deprecate_dynamic_properties

Resolve https://phpstan.org/r/021bc1c5-d27b-4bc8-8974-1a5116b49d9f

https://github.com/phpstan/phpstan/issues/7345#issuecomment-1166632576

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Needs a regression test in ClassAttributesRuleTest.

**Comment by andypost** [comment]
Thank you, will do today

**Comment by andypost** [comment]
Added test but can't make it work on PHP 8.2 but on earlier PHP versions it throws `05: Attribute class AllowDynamicProperties does not exist.` when I comment out attribute definition. That's exactly what the bug is

**Comment by ondrejmirtes** [comment]
Merged as: https://github.com/phpstan/phpstan-src/commit/d122cf43e99b1c6b3b7f85ef5966096b93a0d83b

It works fine in my opinion.

**Comment by andypost** [comment]
Thank you!

**Comment by mglaman** [comment]
Thanks, as always, @ondrejmirtes !

**Comment by andypost** [comment]
@ondrejmirtes somehow now it fails on PHP 8.2 alpha3 but https://3v4l.org/hIKTZ/rfc#vgit.master reports that class exists

`Class AllowDynamicProperties is not an Attribute class. ` maybe it needs some definition somewhere?

**Comment by andypost** [comment]
It needs to update phpstorm-stubs after PR  https://github.com/JetBrains/phpstorm-stubs/pull/1404

**Comment by ondrejmirtes** [comment]
@andypost Please test 1.8.x-dev with `composer require --dev phpstan/phpstan:1.8.x-dev` to see if it fixes your problem.

**Comment by andypost** [comment]
@ondrejmirtes thank you! it works! waiting for new release (and this week 8.2 beta1 coming)

```
/var/www/html/web $ vendor/bin/phpstan analyze -l 2 --debug core/modules/views/src/ResultRow.php
/var/www/html/web/core/modules/views/src/ResultRow.php

                                                                                                                        
 [OK] No errors                                                                                                         
                                                                                                                        

/var/www/html/web $ php -v
PHP 8.2.0alpha3 (cli) (built: Jul  9 2022 13:42:07) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.0alpha3, Copyright (c), by Zend Technologies

/var/www/html/web $ vendor/bin/phpstan -V
PHPStan - PHP Static Analysis Tool 1.8.x-dev@d866a66

```

**Pull request closed without merging**
