### PR TITLE
sscanf: allow nulls in returned array

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/7735

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by ondrejmirtes** [comment]
@staabm Please fix tests on 1.8.x, I didn't check before rebasing and there were some conflicting asserts.

**Comment by herndlm** [comment]
> @staabm Please fix tests on 1.8.x, I didn't check before rebasing and there were some conflicting asserts.

noticed them as well when I rebased my PR :) https://github.com/phpstan/phpstan-src/pull/1652

**Comment by staabm** [comment]
Thank you guys

**Pull request merged**
