### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, I don't want to say PHP 8 is supported unless it really is, so at the minimum these things need to happen:

1) PHP 8 feature freeze
2) nikic/php-parser updated with PHP 8 support and all the new syntax

If you want to run PHPStan on PHP 8 for testing purposes, you can download the PHAR and run that.

**Comment by carusogabriel** [comment]
Hi @ondrejmirtes 👋 

My idea of allowing PHP 8 on `composer.json` is so that projects that want to add support to PHP 8 and have PHPStan as a dependency are allowed to do that. 

Would you accept these changes if we add `continue-on-error` for this builds?

https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error

**Comment by ondrejmirtes** [comment]
Do you have any specific projects like that? If there's demand for that, and they're aware that PHPStan won't actually check (or work) on PHP 8-specific features, then it's probably fine.

**Comment by carusogabriel** [comment]
> Do you have any specific projects like that?

Our current internal projects at @usabilla :)

> PHPStan won't actually check (or work) on PHP 8-specific features, then it's probably fine.

That's true, as we have `static analysis` as one of our steps, wouldn't make much sense to have PHPStan failing there if we want to ensure forward compatibility.

Thanks for the review!

**Comment by ondrejmirtes** [comment]
Why are you closing this? I'd accept this so that you can run *your* application on PHP 8 and don't have to uninstall phpstan/phpstan before `composer install`.

**Comment by carusogabriel** [comment]
@ondrejmirtes Wouldn't make much sense IMHO, as you said, to just have PHPStan running on PHP 8 but not covering the features and new code added.

Plus, I took a look into the GitHub Actions builds failures, there's something odd going on there that's needs further investigation :(

**Comment by ondrejmirtes** [comment]
Alright :)

**Pull request closed without merging**
