### PR TITLE
Fix/issue 6870 expr early termination for `BinaryOp`

### PR DESCRIPTION
**Pull request by rajyan**
fixes https://github.com/phpstan/phpstan/issues/6870
fixes https://github.com/phpstan/phpstan/issues/6890

### CODE REVIEW

**Comment by rajyan** [comment]
Didin't touch `Coalesce` in this PR, because going to fix in separate PR https://github.com/phpstan/phpstan-src/pull/1104

**Comment by rajyan** [comment]
~~Tests are not skipped in old PHP versions 🤔~~

solved

**Comment by ondrejmirtes** [comment]
Sorry, I can't wrap my head around the fact there are two PRs for the same issue: https://github.com/phpstan/phpstan-src/pull/1104 + https://github.com/phpstan/phpstan-src/pull/1105 Can you please explain what's your intention here before I review?

**Comment by rajyan** [comment]
@ondrejmirtes 

https://github.com/phpstan/phpstan-src/pull/1104 is only for `Coalesce` now, and for solving other issues. I cherry picked the first two commits to this PR (which fixes https://github.com/phpstan/phpstan/issues/6870, the scope for `BinaryOp` except `Coalesce`).

As https://phpstan.org/r/9ad910e5-7783-4441-9cb6-98548cce54eb shows, `Coalesce` is already working with this case because of https://github.com/phpstan/phpstan-src/pull/1063, but the scope is not precise enough like https://github.com/phpstan/phpstan/issues/4885 is not solved.

I thought that `Coalesce` expr 
```php
$leftExpr ?? $rightExpr
```
process can be replaced by simulating isset `Ternary`
```php
isset($leftExpr) ? $leftExpr : $rightExpr
```
which handles the scope problem perfectly (fixes https://github.com/phpstan/phpstan/issues/4885), and also fixes a lot of issues like https://github.com/phpstan/phpstan/issues/6026, issues caused from difference between the implementation of `Coalesce` and `Isset_`. 
There are still several problems to fix with https://github.com/phpstan/phpstan-src/pull/1104, but the fact that https://github.com/phpstan/phpstan/issues/6870 can be solved without fixing `Coalesce`, I separated into two PRs.

**Comment by ondrejmirtes** [comment]
Alright, thank you!

**Pull request merged**
