### PR TITLE
Add "base64" as key for stream_get_meta_data

### PR DESCRIPTION
**Pull request by SvenRtbg**
Given the right "data" url, PHP will add a boolean "base64" key to `stream_get_meta_data`.

See some example code in action: https://3v4l.org/G65j4

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, the key should be marked as optional.

**Comment by SvenRtbg** [comment]
I'd like to if I knew how to. I am using the same format as "mediatype", which has been added years ago when this file was at a different location, and it also isn't marked as optional.

I found that arguments can be marked as optional using `=` as a suffix, but we are talking about the return value here.

**Comment by ondrejmirtes** [comment]
https://phpstan.org/writing-php-code/phpdoc-types#array-shapes

See for example `unserialize`.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
