### PR TITLE
Support getting reflection of an anonymous function

### PR DESCRIPTION
**Pull request by Lctrs**
From https://www.php.net/manual/en/class.closure.php :
> Besides the methods listed here, this class also has an __invoke method.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, I don't understand what you're trying to achieve. Can you first post something on phpstan.org that fails?

**Comment by Lctrs** [comment]
Hi @ondrejmirtes,

Well, nothing fails.

In https://github.com/rectorphp/rector/pull/2658, I worked on a class that could resolve any calls (`FuncCall|MethodCall|StaticCall`) to the called function or method reflection (`FunctionReflection|MethodReflection`).

I had one problem when `FuncCall::$name` is an `Expr` (can be obtained with eg `$f = function() {}; $f();`). I could not get the real signature of the function (the one without the `$newthis` param). So I implemented this to resolve my case. I thought maybe you would consider this a valid case and accept a PR for this.

I don't know if I did the right thing though. [Here is where I implemented it](https://github.com/Lctrs/rector/blob/call-reflection-resolver/src/PHPStan/Reflection/CallReflectionResolver.php#L85), maybe you can understand me better with this.

**Comment by ondrejmirtes** [comment]
For `$expr()`, `Type::getCallableParametersAcceptors()` should be used. Maybe this will simplify the logic you implemented in Rector too?

**Comment by ondrejmirtes** [comment]
It works with this too for example:

```php
$func = 'date';
$func();
```

So `ConstantStringType::getCallableParametersAcceptors()` also answers this correctly.

**Comment by ondrejmirtes** [comment]
Not sure what you need FunctionReflection, but yeah, something like that.

**Pull request closed without merging**
