### PR TITLE
Enhance FILTER_VALIDATE_INT option in filter_var

### PR DESCRIPTION
**Pull request by takeokunn**
fixed https://github.com/phpstan/phpstan/issues/7608

### CODE REVIEW

**Comment by takeokunn** [comment]
@ondrejmirtes I don't know how to fix failure github actions job. 
Could you mind help me?

**Comment by herndlm** [comment]
@takeokunn it looks like the problem is that e.g. octdec returns only int before PHP 8. At least that's the type phpstan currently resolves. Such cases might be impossible to fix and have to go to a PHP version specific baseline most likely. There should be some existing already. Sorry, I'm typing from my half-broken phone :)

**Comment by zonuexe** [comment]
@herndlm 
Thanks for your help! (I was working on pair programming with @takeokunn today)
Maybe the problem will be resolved after cherry-pick or rebase https://github.com/phpstan/phpstan-src/pull/1500.

**Comment by herndlm** [comment]
@zonuexe most likely it will, maybe double-check hexdec too. Sorry, still on my phone, otherwise I could have checked already

**Comment by zonuexe** [comment]
@herndlm 
Of course, `hexdec()` is typed correctly
https://github.com/phpstan/phpstan-src/blob/07e341daedc018cf60bd7e8827bb59ae24566bee/resources/functionMap.php#L3933

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
