### PR TITLE
Fix more filter var use cases

### PR DESCRIPTION
**Pull request by BackEndTea**
First commit is to add support for `FILTER_SANITIZE_ADD_SLASHES`, which was added in php 7.3.
It also makes the support for `FILTER_SANITIZE_MAGIC_QUOTES` conditional, as that will be removed in PHP 8.0.

The second commit adds support for the `default` flag. The third commits improves the tests for `filter_var`. And finally the fourth commit improves types for things that can not be false

Also fixes https://github.com/phpstan/phpstan/issues/2802

### CODE REVIEW

**Comment by BackEndTea** [comment]
Because of the amount of filters and the number of possible combinations, this does mean that note very single edge cases has its own test.

I could create those, but i'd prefer to generate them and yield all cases form inside a few nested foreach loops, instead of manually writing them all and returning the array as it is done right now.

What is your opinion on this @ondrejmirtes ?

**Comment by ondrejmirtes** [comment]
If you trust yourself to generate the right expected values, I'm fine with this approach :)

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by BackEndTea** [comment]
Thanks @ondrejmirtes

**Pull request merged**
