### PR TITLE
Recurse into generic objects parameters

### PR DESCRIPTION
**Pull request by dktapps**
This fixes phpstan/phpstan#3767: types like `GenericType<OtherGenericType>` with invalid nested generic parameters not being analysed and reported.

I'm aware that this breaks some iterable special-cases such as intersection of iterable<int>&Traversable. I'm not entirely sure how to address this, so I could use some advice.

I also don't know if I missed any cases, although I don't think I did.

I'm also not sure how this should be tested. There doesn't seem to be any test unit dedicated to `MissingTypehintCheck`.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Look at from which places are the Check classes called - these rules have unit tests.

And I guess the `$traverse($type);` inside `$type->isIterable()->yes()` shouldn't be added.

**Comment by dktapps** [comment]
> Look at from which places are the Check classes called - these rules have unit tests.

Do you want me to repeat the test cases 5 times (one for each of the places MissingTypehintCheck is used)? I hoped there was a better way :<

**Comment by ondrejmirtes** [comment]
@dktapps It's fine to test it in a single rule.

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by dktapps** [comment]
Thanks. Also, the original post referenced the wrong issue, I meant to link this one: phpstan/phpstan#3764

**Pull request merged**
