### PR TITLE
Save native expression types by ExpressionHolder

### PR DESCRIPTION
**Pull request by rajyan**
Another step forward for https://github.com/phpstan/phpstan/issues/8191 suggested in https://github.com/phpstan/phpstan-src/pull/1919#issuecomment-1292596647

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Sorry, I'm just on my phone. I'd expect this to be reverted here or handled better, is it? https://github.com/phpstan/phpstan-src/commit/728336c7d9102edcf3aa3a21f0ed422d1f3b6d32

**Comment by rajyan** [comment]
@ondrejmirtes 
Yes, in different commits to make it clear :)
https://github.com/phpstan/phpstan-src/pull/1936/commits/b674b3eb29f023dd166aaa09947bcafde8e4a562

**Comment by ondrejmirtes** [comment]
Thank you very much! 😊

**Comment by ondrejmirtes** [comment]
FYI There's some bad performance regression in this PR, it makes analysis in two real world projects run indefinitely. I'll try to figure out what's the cause.

**Comment by ondrejmirtes** [comment]
This commit seems so innocent https://github.com/phpstan/phpstan-src/pull/1936/commits/a0980655e510a6a936b9849577b678fb2fb280ea but it makes this file being analysed for 27 seconds instead of 2 seconds: https://gist.github.com/ondrejmirtes/693136deb16f88a98c1973ecaad23079

It probably uncovers some underlying problem with enums and the fix is going to lie somewhere else instead of changing the lines that changed here...

Currently investigating with Blackfire.

**Comment by ondrejmirtes** [comment]
Alright, the performance problem was fixed with this: https://github.com/phpstan/phpstan-src/commit/1ec058d5518a86d88e8877425588bcdcc175f374

**Comment by ondrejmirtes** [comment]
I figured it out because I added some debug statements here:

```diff
--- a/src/Analyser/NodeScopeResolver.php
+++ b/src/Analyser/NodeScopeResolver.php
@@ -2697,7 +2697,16 @@ class NodeScopeResolver
 					ExpressionContext::createTopLevel(),
 				);
 				$armScope = $armResult->getScope();
+				var_dump('scope first:');
+				var_dump($scope->debug());
+
+				var_dump('armScope first:');
+				var_dump($armScope->debug());
 				$scope = $scope->mergeWith($armScope);
+
+				var_dump('scope second:');
+				var_dump($scope->debug());
+				var_dump('------');
 				$hasYield = $hasYield || $armResult->hasYield();
 				$throwPoints = array_merge($throwPoints, $armResult->getThrowPoints());
 				$matchScope = $matchScope->filterByFalseyValue($filteringExpr);
```

And the log made it obvious:

```
/Users/ondrej/Development/slevomat/app/services/PointOfInterest/PointOfInterestType.php
string(12) "scope first:"
array(1) {
  ["$this (Yes)"]=>
  string(51) "$this(Slevomat\PointOfInterest\PointOfInterestType)"
}
string(15) "armScope first:"
array(2) {
  ["$this (Yes)"]=>
  string(111) "$this(Slevomat\PointOfInterest\PointOfInterestType)&Slevomat\PointOfInterest\PointOfInterestType::LOOKOUT_TOWER"
  ["native $this"]=>
  string(111) "$this(Slevomat\PointOfInterest\PointOfInterestType)&Slevomat\PointOfInterest\PointOfInterestType::LOOKOUT_TOWER"
}
string(13) "scope second:"
array(2) {
  ["$this (Yes)"]=>
  string(51) "$this(Slevomat\PointOfInterest\PointOfInterestType)"
  ["native $this"]=>
  string(111) "$this(Slevomat\PointOfInterest\PointOfInterestType)&Slevomat\PointOfInterest\PointOfInterestType::LOOKOUT_TOWER"
}
string(6) "------"
string(12) "scope first:"
array(2) {
  ["$this (Yes)"]=>
  string(51) "$this(Slevomat\PointOfInterest\PointOfInterestType)"
  ["native $this"]=>
  string(111) "$this(Slevomat\PointOfInterest\PointOfInterestType)&Slevomat\PointOfInterest\PointOfInterestType::LOOKOUT_TOWER"
}
string(15) "armScope first:"
array(2) {
  ["$this (Yes)"]=>
  string(164) "$this(Slevomat\PointOfInterest\PointOfInterestType~Slevomat\PointOfInterest\PointOfInterestType::LOOKOUT_TOWER)&Slevomat\PointOfInterest\PointOfInterestType::MUSEUM"
  ["native $this"]=>
  string(164) "$this(Slevomat\PointOfInterest\PointOfInterestType~Slevomat\PointOfInterest\PointOfInterestType::LOOKOUT_TOWER)&Slevomat\PointOfInterest\PointOfInterestType::MUSEUM"
}
string(4) "here"
string(13) "scope second:"
array(2) {
  ["$this (Yes)"]=>
  string(51) "$this(Slevomat\PointOfInterest\PointOfInterestType)"
  ["native $this"]=>
  string(280) "($this(Slevomat\PointOfInterest\PointOfInterestType)&Slevomat\PointOfInterest\PointOfInterestType::LOOKOUT_TOWER)|($this(Slevomat\PointOfInterest\PointOfInterestType~Slevomat\PointOfInterest\PointOfInterestType::LOOKOUT_TOWER)&Slevomat\PointOfInterest\PointOfInterestType::MUSEUM)"
}
string(6) "------"
```

The `native $this` got longer and longer because the starting point wasn't the same.

**Comment by rajyan** [comment]
Thank you for the fix!
https://github.com/phpstan/phpstan-src/commit/1ec058d5518a86d88e8877425588bcdcc175f374
I had these fixes in a different PR branch, couldn't notice that this breaks the performance that much.

and thank you for
https://github.com/phpstan/phpstan-src/commit/69d7e8185af250ce7315a2000b88a3d31f84cf3a
too. I was a little worried about the performance when using exprStringToExpr.

**Pull request merged**
