### PR TITLE
Add `parse_str` and `mb_parse_str` by-ref result type specifier

### PR DESCRIPTION
**Pull request by fluffycondor**
Fixes one case from phpstan/phpstan#7231

### CODE REVIEW

**Comment by fluffycondor** [comment]
Whoops, looks like it still fails. Will fix it tomorrow

**Comment by ondrejmirtes** [comment]
Thanks, but this should be done via stub after https://github.com/phpstan/phpstan-src/pull/1804.

**Comment by fluffycondor** [comment]
> Thanks, but this should be done via stub after #1804.

But there's no way getting constant arrays from constant strings with `@param-out`.
It's one of the key features of this PR.
https://phpstan.org/r/ce7618fa-543a-4e35-ac99-99c2b8f0a7b0

**Comment by staabm** [comment]
I think we would need a new extension-type, which allows to programatically define paramOut types

**Pull request closed without merging**
