### PR TITLE
Add-fpow

### PR DESCRIPTION
**Pull request by jack-worman**
Docs: https://www.php.net/manual/en/function.fpow.php

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
This doesn't solve the problem. PHPStan already knows about the function. See https://github.com/phpstan/phpstan/issues/12226#issuecomment-2530719733

**Comment by jack-worman** [comment]
> This doesn't solve the problem. PHPStan already knows about the function. See [phpstan/phpstan#12226 (comment)](https://github.com/phpstan/phpstan/issues/12226#issuecomment-2530719733)

Although it may not solve the problem, shouldn't `fpow()` still be added? Why is `mb_ucfirst()` added to the new list?

**Comment by ondrejmirtes** [comment]
Not sure, we don't need it there.

**Comment by jack-worman** [comment]
> Not sure, we don't need it there.

To help my understanding, could you give me an example of a reason to ever add a function to this file?

**Comment by ondrejmirtes** [comment]
1) If it exists on PHP 7 (php-8-stubs are used for PHP 8+)
2) Or if we want to type more specific parameter or return types

**Pull request closed without merging**
