### PR TITLE
ignoreErrors: multiple messages in and explixit reportUnmatched

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
See https://github.com/phpstan/phpstan/issues/7876

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
Oh it looks like I have to figure out how to make parameters schema keys optional.

**Comment by MartinMystikJonas** [comment]
I solved it by extending ParametersSchemaExtension. Keys prepended with ? are created as optional.

**Comment by ondrejmirtes** [comment]
This is really nice, thank you!

Please send an update to https://phpstan.org/user-guide/ignoring-errors#ignoring-in-configuration-file and also https://phpstan.org/user-guide/ignoring-errors#reporting-unused-ignores.

**Comment by MartinMystikJonas** [comment]
Docs update here: https://github.com/phpstan/phpstan/pull/8039

**Pull request merged**
