### PR TITLE
Fix false positives for array accesses on `iterable`

### PR DESCRIPTION
**Pull request by julienfalque**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Nope, sorry, the original behaviour is intended. `Bar[]` + `iterable` is still `iterable`, not `array`.

`iterable` means `Traversable|array`, the array access is not guaranteed.

**Comment by julienfalque** [comment]
I don't understand. In the following example:
```php
/** @var array|(ArrayAccess&iterable) $foo
private iterable $foo;
```
isn't the PHPDoc type supposed to "extend" the native type? Both `array` and `ArrayAccess&iterable` are subtypes of `iterable`, why not use the PHPDoc type as-is in this case?

**Comment by ondrejmirtes** [comment]
Please open an issue, right now I don't know what problem you're trying to fix :)

**Comment by julienfalque** [comment]
See https://github.com/phpstan/phpstan/issues/6243.

**Comment by herndlm** [comment]
`ArrayAccess` might need some special care here and there. Especially in a Union type. Your https://github.com/phpstan/phpstan/issues/6184 is another example, which I tried to work on, but failed :)

**Pull request closed without merging**
