### PR TITLE
Fix order of functions in functionmap

### PR DESCRIPTION
**Pull request by muglug**
This makes it a little easier to keep them in sync.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you! If you tell me what sorting function is used here, I'm gonna keep it sorted with a unit test.

**Comment by muglug** [comment]
I just sorted them in my text editor, but it should be a straight-forward alphabetic sort...

**Comment by localheinz** [comment]
@muglug @ondrejmirtes 

I can recommend the [Lines Sorter Plugin](https://plugins.jetbrains.com/plugin/5919-lines-sorter/) for PhpStorm.

**Comment by muglug** [comment]
I can recommend SublimeText 😉

**Pull request merged**
