### PR TITLE
Change curl_setopt function signature based on 2nd arg

### PR DESCRIPTION
**Pull request by staabm**
validates all available curl constants when passed to `curl_setopt`.

implemeted everything listed on https://www.php.net/manual/en/function.curl-setopt.php - except a few callable-expecting types at the very end. these are a bit more complicated, therefore I left them out for now.

doing similar stuff for `curl_setopt_array` will be implemented in a followup PR.

closes https://github.com/phpstan/phpstan/issues/7951

### CODE REVIEW

**Comment by staabm** [comment]
(lets finish all my other open non-draft PRs before finalizing/discussing this one here. I had a hour of free time.. ;))

**Comment by ondrejmirtes** [comment]
Thank you for mapping out the types! However this doesn't need a new rule, just modifications to the function signature on the fly. This is already done for array_map and similar in https://github.com/phpstan/phpstan-src/blob/1.8.x/src/Reflection/ParametersAcceptorSelector.php.

When that's done, the existing rule (call to function parameters) will pick it up and report.

**Comment by ondrejmirtes** [comment]
So nice, right? :) Please rebase and solve the conflict, thanks.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
