### PR TITLE
Fix resolving class const fetch for constant strings

### PR DESCRIPTION
**Pull request by rvanvelzen**
Fix phpstan/phpstan#7391

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you! Please also open a PR with that namespace slice fix 😊

**Comment by mvorisek** [comment]
Although the reported https://phpstan.org/r/89fb126f-4736-4208-b599-a5264d181e18 demo is fixed, I still need the following fix in my code /w phpstan 1.7.14:
```diff
    /**
     * @param MethodCall|StaticCall $methodCall
     */
    protected function getMethodCallScopeType(CallLike $methodCall, Scope $scope): Type
    {
        if ($methodCall instanceof StaticCall) {
+            // while loop needed to fix https://github.com/phpstan/phpstan/issues/7391
            $clExpr = $methodCall->class;
+            while ($clExpr instanceof ClassConstFetch && $clExpr->name instanceof Identifier && strtolower($clExpr->name->name) === 'class') {
+                $clExpr = $clExpr->class;
+            }
            $classNameType = $scope->getType(new ClassConstFetch($clExpr, 'class'));
            if ($classNameType instanceof ConstantStringType) {
                return new ObjectType($classNameType->getValue());
            } elseif ($classNameType instanceof GenericClassStringType) {
                return $classNameType->getGenericType();
            }

            throw new \Exception('Unexpected scope class name class: ' . get_class($classNameType));
        }

        return $scope->getType($methodCall->var);
    }
```

**Comment by rvanvelzen** [comment]
Please create a new issue showing exactly what you're trying to accomplish. I though it was about `'Foo'::class` which is resolved by phpstan/phpstan-src#1425 but your code is not related to that at all.

**Comment by mvorisek** [comment]
In custom phpstan extension, I need this code to resolve method class from `(static::class)::createEntity()` call.

**Comment by rvanvelzen** [comment]
You can use `$scope->resolveTypeByName()` in case `$methodCall->class` is a `Name`:
https://github.com/phpstan/phpstan-src/blob/c4a662ac6c3ec63f063238880b243b5399c34fcc/src/Analyser/MutatingScope.php#L1732-L1750

**Comment by mvorisek** [comment]
I tried, but the `$methodCall->class` is instanceof `PhpParser\Node\Expr\ClassConstFetch`. I would expect `$scope->getType(new ClassConstFetch($methodCall->class, 'class'))` to resolve it, but as written above, it currently needs the while loop to unnest the `ClassConstFetch`.

**Pull request merged**
