### PR TITLE
Handle throwTag in stub file

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/phpstan/phpstan/issues/7552

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Tests are working locally
image

Do you know what could be different with the CI @ondrejmirtes ?

**Comment by ondrejmirtes** [comment]
No idea, feels like I'm going crazy here too, works on my machine as well.

**Comment by VincentLanglet** [comment]
> No idea, feels like I'm going crazy here too, works on my machine as well.

I'm pretty sure you won't like this but...
Should I provide a PR without the test then ? It will at least fix the bug.

**Comment by ondrejmirtes** [comment]
No, we have to find the root cause. It's entirely possible our two computers are the only ones in the world where it works, and it wouldn't work for anyone else ;)

**Comment by ondrejmirtes** [comment]
An idea: try running `vendor/bin/phpunit` locally (whole test suite) instead of `make tests` (paratest)

**Comment by VincentLanglet** [comment]
> An idea: try running `vendor/bin/phpunit` locally (whole test suite) instead of `make tests` (paratest)

Seems like the `src/Reflection/SignatureMap/NativeFunctionReflectionProvider.php` file is not used for every tests.

You can see that the test `LegacyNodeScopeResolverTest::testArrayFunctions ` logs something here https://github.com/phpstan/phpstan-src/runs/7138131794?check_suite_focus=true,
then if I comment, it's `EchoRuleTest::testEchoRule` here https://github.com/phpstan/phpstan-src/runs/7138206618?check_suite_focus=true

And so on https://github.com/phpstan/phpstan-src/runs/7138300559?check_suite_focus=true

I start to believe that once the `random_int` definition is loaded, it's not loaded anymore for others tests.

**Comment by VincentLanglet** [comment]
It works fine with another function https://github.com/phpstan/phpstan-src/pull/1487 ; so the bugfix works ;)

**Pull request closed without merging**
