### PR TITLE
implemented `str_contains` FunctionTypeSpecifyingExtension

### PR DESCRIPTION
**Pull request by staabm**
first str-family-function to infer `non-empty-string` type. 

Initially had the idea of putting everything into a single StrFamily* extension, but then figured that the semantics between substr, substring, strpos, stripos, str_contains etc are too different, and it would be more readable to put each of them into a separate extension.

therefore this is the first PR. if merged, I will work on similar semantics for the remaining functions

refs https://github.com/phpstan/phpstan/issues/6792

### CODE REVIEW

**Comment by herndlm** [comment]
Nice! The minute this is merged I'm going to add the correspondent phpstan-webmozart-assert support :)

**Comment by ondrejmirtes** [comment]
Hi, if you base this on 1.4.x, it's gonna be released sooner 😊

**Comment by staabm** [comment]
Ohh I see. Thought 1.4.x is meant for bugfix only and 1.5.x for new features

**Comment by ondrejmirtes** [comment]
That line is blurred here - you could look at this and consider it a bugfix too.

**Comment by staabm** [comment]
mixed it up a bit. re-opened as a new PR for 1.4.x in https://github.com/phpstan/phpstan-src/pull/1068

**Pull request closed without merging**
