### PR TITLE
more precise getTrace() return-type

### PR DESCRIPTION
**Pull request by staabm**
inspired by https://github.com/vimeo/psalm/pull/7798/
see https://www.php.net/manual/en/function.debug-backtrace.php

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by ondrejmirtes** [comment]
FYI this has been wrong for two years and I have no idea why anyone didn't notice this: https://github.com/phpstan/phpstan-src/commit/492cd89932d873147cdf7acf49c88d432cbce69f

**Comment by staabm** [comment]
Thanks for noting. 

It seems the types were wrong even before this PR as the fixes you did is not something which changed here. 

Puzzling, indeed that noone noticed it.

**Comment by staabm** [comment]
the actual error was introduced in https://github.com/phpstan/phpstan-src/pull/914

**Comment by thg2k** [comment]
I'm super confused by this. Please help me understand:
1) How did you notice? If I dump the type before and after this fix nothing changes, I get: `array<int, array{function: string, line?: int, file?: string, class?: class-string, type?: '->'|'::', args?: array, object?: object}>` in both cases
2) Why do we need the signature for all those classes as they all implement Throwable? Shouldn't they inherit it anyway?

Maybe no one noticed cause this change is a no-op 😄

**Comment by ondrejmirtes** [comment]
Yeah, my fix might actually be a no-op because it's already been done correctly in https://github.com/phpstan/phpstan-src/blob/1.11.x/stubs/Exception.stub.

To answer your question generally: https://phpstan.org/user-guide/troubleshooting-types

> The way these are combined together to offer the full picture is a very complex logic and subject to frequent change as bugs are getting fixed and improvements made.

**Comment by thg2k** [comment]
> To answer your question generally: https://phpstan.org/user-guide/troubleshooting-types
> 

By now I have a decent grasp on how the type is determined, but I still don't understand why we need the signatures for all those classes that implement Throwable.

Can we get rid of those from the functionMap.php file?

**Comment by ondrejmirtes** [comment]
Some stuff could probably be cleaned from functionMap, but most of it can't.

**Pull request merged**
