### PR TITLE
Update `AppendIterator` stub.

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- [x] Update the typing information of the `AppendIterator` stub.

Example on 3v4l: https://3v4l.org/gSPtO#v8.1.8
False positive on PHPstan: https://phpstan.org/r/36c91b68-01f7-404f-9fba-7a9e03d28953

### CODE REVIEW

**Comment by staabm** [comment]
could you add the phpstan.org/try sample as NodeScopeResolver test?

**Comment by drupol** [comment]
> NodeScopeResolver

I just added it, but I'm not convinced. The test pass in 1.8.x and this branch. I guess my modifications doesn't have any impact here. Weird.

**Comment by staabm** [comment]
Sorry my mistake: we don't need a NodeResolverTest but one for the rule which emits the errors which can be seen in your snippet

> Parameter #1 $iterator of method AppendIterator<(int|string),mixed,Iterator<TKey of (int|string), TValue>>::append() expects Iterator<TKey of (int|string), bool>, Generator<false, false, mixed, void> given.

**Comment by drupol** [comment]
Ok, going to remove the test.

**Comment by staabm** [comment]
the error we see in the phpstan sandbox is emitted here:
https://github.com/phpstan/phpstan-src/blob/c6b7ee92503da5f7f21d976fe53014b4a66ae1cc/src/Rules/Methods/CallMethodsRule.php#L64

therefore the repro case should be in `CallMethodsRuleTest`

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
