### PR TITLE
mark readline* function having side-effects

### PR DESCRIPTION
**Pull request by staabm**
see https://www.php.net/manual/de/book.readline.php

inspired by https://github.com/vimeo/psalm/pull/7828

### CODE REVIEW

**Comment by staabm** [comment]
btw: I am wondering why phpstan does not report errors atm https://phpstan.org/r/91377db4-0029-494f-935b-83c619fa5f06
but psalm does https://psalm.dev/r/eb33a31483

**Comment by staabm** [comment]
This needs to be adjusted like described by ondrey in https://github.com/phpstan/phpstan-src/pull/698#issuecomment-934392606

**Comment by staabm** [comment]
added the instructions from https://github.com/phpstan/phpstan-src/pull/698#issuecomment-934392606 into the generated file, to hopefully ease the contributor experience

**Comment by ondrejmirtes** [comment]
Hi, can you please first verify that these records actually need to be added by some tests? Ideally NodeScopeResolverTest + CallToFunctionStatementWithoutSideEffectsRule. It's possible that PHPStan already knows exactly what's going on.

Also the "generated" message in the generated file should be in a separate PR if we decide the readline changes in this one aren't needed :)

**Comment by staabm** [comment]
> It's possible that PHPStan already knows exactly what's going on.

hmm ok.. this might explain, why I don't see errors in the background, even this entries are missing.

> btw: I am wondering why phpstan does not report errors atm [phpstan.org/r/91377db4-0029-494f-935b-83c619fa5f06](https://phpstan.org/r/91377db4-0029-494f-935b-83c619fa5f06)

-----

> Also the "generated" message in the generated file should be in a separate PR if we decide the readline changes in this one aren't needed :)

I will adjust this PR to only include the generated-file-comment (I will not change the PR title accordingly)

**Comment by ondrejmirtes** [comment]
Thank you.

**Pull request merged**
