### PR TITLE
Validate the params of array functions

### PR DESCRIPTION
**Pull request by BackEndTea**
Fixes: https://github.com/phpstan/phpstan/issues/3883

This isn't all array functions, but i'm mostly presenting it as is to see if this is the right direction to go in.

If this is the desired way to solve this then i'll add the other array functions too.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, instead of adding rules like this, it'd be better to:

1) Try to construct userland functions on phpstan.org with generic PHPDocs that do the same thing.
2) See if calling such functions with wrong arguments leads to reported errors by the `CallToFunctionParametersRule` rule.
3) If not, we need to improve [generics](https://github.com/phpstan/phpstan/milestone/9) implementation so that such generic signatures work like we want them to.
4) If yes, we need to add support in [stub files](https://phpstan.org/user-guide/stub-files) to allow overriding PHPDocs in built-in functions, and then add stub files for said functions.

That way, we can leverage the rules that are already implemented, and possibly include other benefits as well.

**Comment by BackEndTea** [comment]
I created the following function, which does lead to an error:
https://phpstan.org/r/611bccea-0e28-45eb-a9b6-7b5123a3c35f

However this error is (partially) wrong, as it tries to make a union type of `T`, while the `T` of calalble should be the same as the `T` in the array. This also means the error gets reported at level 7 instead of level 5.

If we move things to a class its a lot easier to first bind T, and then make sure the stays the same: https://phpstan.org/r/287a5667-9b5e-4e57-bfe2-54c7f818360e

**Comment by ondrejmirtes** [comment]
> However this error is (partially) wrong, as it tries to make a union type of T

For normal situations when we have `@param T $a` and `@param T $b` the union is expected. In case of callables and `T` as a parameter, it should probably be used as an "upper bound" so that the union doesn't happen. But for me this is a smaller issue and mostly cosmetic.

If you want to tackle that, you should get yourself familiar with `GenericParametersAcceptorResolver` and `Type::inferTemplateTypes()` as it will need some change there. From the top of my head, I'm not sure what exactly needs to be done, I'd have to dive into it for several hours. At the minimum I'm sure should be proficient in `Type::isSuperTypeOf()` and `TypeCombinator::union()` vs. `intersect()` to tackle that :)

If you want to add support for stub files for native functions, look at places where `StubPhpDocProvider::findFunctionPhpDoc()` is currently called and how it's used. It needs to be integrated in NativeFunctionReflectionProvider, so that instead of `new FunctionVariant`, there should be `new FunctionVariantWithPhpDocs`, and NativeParameterReflection needs to implement ParameterReflectionWithPhpDocs. You can test it by adding stubs for some array functions and test their calls in CallToFunctionParametersRuleTest. This is mostly routine and mechanical change, there shouldn't be obstacle in that :)

**Comment by ondrejmirtes** [comment]
If I'm not clear enough, I'd prefer just the last paragraph as it can get us closer to the goal in a straight way without surprises. Changing anything about generics requires a lot more expertise.

**Comment by ondrejmirtes** [comment]
Closing this PR since the direction should be completely different :)

**Pull request closed without merging**
