### PR TITLE
Revert "Resolve deprecated tag also from parents"

### PR DESCRIPTION
**Pull request by ossinkine**
This reverts https://github.com/phpstan/phpstan-src/pull/792, see https://github.com/phpstan/phpstan-src/pull/792#issuecomment-1043002422

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Sorry, I like the new behaviour more, it makes more sense to me.

**Comment by ossinkine** [comment]
Сlass can have its own methods (not inherited from an abstract class or interface). If a method is deprecated in an interface, but the class still wants to have such a method (without implementing the interface), what should be done in this case? According to your logic, such a method should also be deprecated and the class cannot have it on its own. If a class has a method that only implements an interface, then the method in the class must also be marked as deprecated, because it will be removed in the next major release.

I have already given an example with Doctrine. In the next major release [`Doctrine\Persistence\Event\LifecycleEventArgs::getEntity`](https://github.com/doctrine/persistence/blob/0130920efd696cf5480744f499672b2d4ca47c85/lib/Doctrine/Persistence/Event/LifecycleEventArgs.php#L36) will be deleted but [`Doctrine\ORM\Event\LifecycleEventArgs::getEntity`](https://github.com/doctrine/orm/blob/152c04c03d68d39f485d367713dd69dec0f4106d/lib/Doctrine/ORM/Event/LifecycleEventArgs.php#L23) is not, so why it should be deprecated?

Symfony following the same way - if the method is deprecated in the implemented interface and won't be used itself it either marked as deprecated (f.e. [`Symfony\Component\Security\Http\Authenticator\HttpBasicAuthenticator::createAuthenticatedToken`](https://github.com/symfony/symfony/blob/1f68723f3f3dbec9f074cf971c9002d9447f2f8c/src/Symfony/Component/Security/Http/Authenticator/HttpBasicAuthenticator.php#L89)) or marked as inheritdoc that also implies that it is deprecated (f.e. [`Symfony\Component\Security\Core\User\ChainUserProvider::loadUserByUsername`](https://github.com/symfony/symfony/blob/1f68723f3f3dbec9f074cf971c9002d9447f2f8c/src/Symfony/Component/Security/Core/User/ChainUserProvider.php#L52)).

@ondrejmirtes could you explain your point?

**Comment by eiriksm** [comment]
Hi there.

I must say it sounds strange to me to implement a method that is marked as deprecated, and then expect that method itself to not be deprecated. I see your examples, and I understand that it happens and is technically possible. But it sounds strange to me, and I would personally refrain from using a method that is deprecated on the interface level (for example the ones in your examples)

I can agree that a middle ground would be to only expect it when the class specifies inheritdoc from the (deprecated) interface method. But I disagree with removing it altogether. I would expect these cases to be few enough that you can simply ignore them in your phpstan config?

I can also contribute my own story about this (and why I contributed the code in the first place). I was working on a Drupal project where the TermInterface::getVocabularyId method was deprecated in Drupal 8. The code in question was type hinting an implementation (Term class). When this project was upgraded to Drupal 9 this method very surprisingly was not existing. Why on earth did I not get a warning, was it not deprecated, I thought? Well it was. Then why didn't phpstan warn me? Well... Hence the PR. In drupal it's most common to deprecate methods on the interface and then remove them. So yeah, I need this 🤓

**Comment by ondrejmirtes** [comment]
I agree with @eiriksm here. I suggest @ossinkine to rename the `getEntity` method to something else to note that it has nothing in common with the deprecated one.

**Pull request closed without merging**
